/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Company

class CompanyTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Company
        //val modelInstance = Company()

        // to test the property `active` - Indicates if the security is actively listed.  If false, this means the company is no longer listed and cannot be traded.
        should("test active") {
            // uncomment below to test the property
            //modelInstance.active shouldBe ("TODO")
        }

        // to test the property `bloomberg` - The Bloomberg guid for the symbol.
        should("test bloomberg") {
            // uncomment below to test the property
            //modelInstance.bloomberg shouldBe ("TODO")
        }

        // to test the property `ceo` - The name of the company's current CEO.
        should("test ceo") {
            // uncomment below to test the property
            //modelInstance.ceo shouldBe ("TODO")
        }

        // to test the property `cik` - The official CIK guid used for SEC database/filings.
        should("test cik") {
            // uncomment below to test the property
            //modelInstance.cik shouldBe ("TODO")
        }

        // to test the property `country` - The country in which the company is registered.
        should("test country") {
            // uncomment below to test the property
            //modelInstance.country shouldBe ("TODO")
        }

        // to test the property `description` - A description of the company and what they do/offer.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `employees` - The approximate number of employees for the company.
        should("test employees") {
            // uncomment below to test the property
            //modelInstance.employees shouldBe ("TODO")
        }

        // to test the property `exchange` - The symbol's primary exchange.
        should("test exchange") {
            // uncomment below to test the property
            //modelInstance.exchange shouldBe ("TODO")
        }

        // to test the property `exchangeSymbol` - The exchange code (id) of the symbol's primary exchange.
        should("test exchangeSymbol") {
            // uncomment below to test the property
            //modelInstance.exchangeSymbol shouldBe ("TODO")
        }

        // to test the property `figi` - The OpenFigi project guid for the symbol. (<a rel=\"nofollow\" target=\"_blank\" href=\"https://openfigi.com/\">https://openfigi.com/</a>)
        should("test figi") {
            // uncomment below to test the property
            //modelInstance.figi shouldBe ("TODO")
        }

        // to test the property `hqAddress` - The street address for the company's headquarters.
        should("test hqAddress") {
            // uncomment below to test the property
            //modelInstance.hqAddress shouldBe ("TODO")
        }

        // to test the property `hqCountry` - The country in which the company's headquarters is located.
        should("test hqCountry") {
            // uncomment below to test the property
            //modelInstance.hqCountry shouldBe ("TODO")
        }

        // to test the property `hqState` - The state in which the company's headquarters is located.
        should("test hqState") {
            // uncomment below to test the property
            //modelInstance.hqState shouldBe ("TODO")
        }

        // to test the property `industry` - The industry in which the company operates.
        should("test industry") {
            // uncomment below to test the property
            //modelInstance.industry shouldBe ("TODO")
        }

        // to test the property `lei` - The Legal Entity Identifier (LEI) guid for the symbol. (<a rel=\"nofollow\" target=\"_blank\" href=\"https://en.wikipedia.org/wiki/Legal_Entity_Identifier\">https://en.wikipedia.org/wiki/Legal_Entity_Identifier</a>)
        should("test lei") {
            // uncomment below to test the property
            //modelInstance.lei shouldBe ("TODO")
        }

        // to test the property `listdate` - The date that the symbol was listed on the exchange.
        should("test listdate") {
            // uncomment below to test the property
            //modelInstance.listdate shouldBe ("TODO")
        }

        // to test the property `logo` - The URL of the entity's logo.
        should("test logo") {
            // uncomment below to test the property
            //modelInstance.logo shouldBe ("TODO")
        }

        // to test the property `marketcap` - The current market cap for the company.
        should("test marketcap") {
            // uncomment below to test the property
            //modelInstance.marketcap shouldBe ("TODO")
        }

        // to test the property `name` - The name of the company/entity.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `phone` - The phone number for the company. This is usually a corporate contact number.
        should("test phone") {
            // uncomment below to test the property
            //modelInstance.phone shouldBe ("TODO")
        }

        // to test the property `sector` - The sector of the indsutry in which the symbol operates.
        should("test sector") {
            // uncomment below to test the property
            //modelInstance.sector shouldBe ("TODO")
        }

        // to test the property `sic` - Standard Industrial Classification (SIC) id for the symbol. (<a rel=\"nofollow\" target=\"_blank\" href=\"https://en.wikipedia.org/wiki/Standard_Industrial_Classification\">https://en.wikipedia.org/wiki/Legal_Entity_Identifier</a>)
        should("test sic") {
            // uncomment below to test the property
            //modelInstance.sic shouldBe ("TODO")
        }

        // to test the property `similar` - A list of ticker symbols for similar companies.
        should("test similar") {
            // uncomment below to test the property
            //modelInstance.similar shouldBe ("TODO")
        }

        // to test the property `symbol` - The exchange symbol that this item is traded under.
        should("test symbol") {
            // uncomment below to test the property
            //modelInstance.symbol shouldBe ("TODO")
        }

        // to test the property `tags`
        should("test tags") {
            // uncomment below to test the property
            //modelInstance.tags shouldBe ("TODO")
        }

        // to test the property `type` - The type or class of the security.  (<a alt=\"Full List of Ticker Types\" href=\"https://polygon.io/docs/stocks/get_v3_reference_tickers_types\">Full List of Ticker Types</a>)
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `updated` - The last time this company record was updated.
        should("test updated") {
            // uncomment below to test the property
            //modelInstance.updated shouldBe ("TODO")
        }

        // to test the property `url` - The URL of the company's website
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

    }
}
