/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CryptoLastTradeLast

class CryptoLastTradeLastTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CryptoLastTradeLast
        //val modelInstance = CryptoLastTradeLast()

        // to test the property `conditions` - A list of condition codes. 
        should("test conditions") {
            // uncomment below to test the property
            //modelInstance.conditions shouldBe ("TODO")
        }

        // to test the property `exchange` - The exchange that this crypto trade happened on.   See <a href=\"https://massive.com/docs/rest/crypto/market-operations/exchanges\">Exchanges</a> for a mapping of exchanges to IDs. 
        should("test exchange") {
            // uncomment below to test the property
            //modelInstance.exchange shouldBe ("TODO")
        }

        // to test the property `price` - The price of the trade. This is the actual dollar value per whole share of this trade. A trade of 100 shares with a price of $2.00 would be worth a total dollar value of $200.00. 
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

        // to test the property `propertySize` - The size of a trade (also known as volume). 
        should("test propertySize") {
            // uncomment below to test the property
            //modelInstance.propertySize shouldBe ("TODO")
        }

        // to test the property `timestamp` - The Unix millisecond timestamp for the start of the aggregate window.
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

    }
}
