/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.DailySchedules200Response
import org.openapitools.client.models.ProductSchedules200ResponseResultsInner

class DailySchedules200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DailySchedules200Response
        //val modelInstance = DailySchedules200Response()

        // to test the property `requestId` - The unique identifier for this request.
        should("test requestId") {
            // uncomment below to test the property
            //modelInstance.requestId shouldBe ("TODO")
        }

        // to test the property `status` - The status of the response.
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `nextUrl` - The URL for the next page of results.
        should("test nextUrl") {
            // uncomment below to test the property
            //modelInstance.nextUrl shouldBe ("TODO")
        }

        // to test the property `results` - A list of schedules for each product.
        should("test results") {
            // uncomment below to test the property
            //modelInstance.results shouldBe ("TODO")
        }

    }
}
