/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.DeprecatedGetHistoricCryptoTrades200Response
import org.openapitools.client.models.DeprecatedGetHistoricCryptoTrades200ResponseAllOfTicksInner

class DeprecatedGetHistoricCryptoTrades200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeprecatedGetHistoricCryptoTrades200Response
        //val modelInstance = DeprecatedGetHistoricCryptoTrades200Response()

        // to test the property `day` - The date that was evaluated from the request.
        should("test day") {
            // uncomment below to test the property
            //modelInstance.day shouldBe ("TODO")
        }

        // to test the property `map` - A map for shortened result keys.
        should("test map") {
            // uncomment below to test the property
            //modelInstance.map shouldBe ("TODO")
        }

        // to test the property `msLatency` - The milliseconds of latency for the query results.
        should("test msLatency") {
            // uncomment below to test the property
            //modelInstance.msLatency shouldBe ("TODO")
        }

        // to test the property `symbol` - The symbol pair that was evaluated from the request.
        should("test symbol") {
            // uncomment below to test the property
            //modelInstance.symbol shouldBe ("TODO")
        }

        // to test the property `ticks`
        should("test ticks") {
            // uncomment below to test the property
            //modelInstance.ticks shouldBe ("TODO")
        }

    }
}
