/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.DeprecatedGetCryptoSnapshotTickerBook200ResponseAllOfData
import org.openapitools.client.models.DeprecatedGetCryptoSnapshotTickerBook200ResponseAllOfDataAsksInner

class DeprecatedGetCryptoSnapshotTickerBook200ResponseAllOfDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeprecatedGetCryptoSnapshotTickerBook200ResponseAllOfData
        //val modelInstance = DeprecatedGetCryptoSnapshotTickerBook200ResponseAllOfData()

        // to test the property `askCount` - The combined total number of asks in the book.
        should("test askCount") {
            // uncomment below to test the property
            //modelInstance.askCount shouldBe ("TODO")
        }

        // to test the property `asks`
        should("test asks") {
            // uncomment below to test the property
            //modelInstance.asks shouldBe ("TODO")
        }

        // to test the property `bidCount` - The combined total number of bids in the book.
        should("test bidCount") {
            // uncomment below to test the property
            //modelInstance.bidCount shouldBe ("TODO")
        }

        // to test the property `bids`
        should("test bids") {
            // uncomment below to test the property
            //modelInstance.bids shouldBe ("TODO")
        }

        // to test the property `spread` - The difference between the best bid and the best ask price across exchanges.
        should("test spread") {
            // uncomment below to test the property
            //modelInstance.spread shouldBe ("TODO")
        }

        // to test the property `ticker` - The exchange symbol that this item is traded under.
        should("test ticker") {
            // uncomment below to test the property
            //modelInstance.ticker shouldBe ("TODO")
        }

        // to test the property `updated` - The last updated timestamp.
        should("test updated") {
            // uncomment below to test the property
            //modelInstance.updated shouldBe ("TODO")
        }

    }
}
