/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.DeprecatedGetCryptoSnapshotTickerBook200ResponseAllOfDataAsksInner

class DeprecatedGetCryptoSnapshotTickerBook200ResponseAllOfDataAsksInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeprecatedGetCryptoSnapshotTickerBook200ResponseAllOfDataAsksInner
        //val modelInstance = DeprecatedGetCryptoSnapshotTickerBook200ResponseAllOfDataAsksInner()

        // to test the property `p` - The price of this book level.
        should("test p") {
            // uncomment below to test the property
            //modelInstance.p shouldBe ("TODO")
        }

        // to test the property `x` - A map of the exchange ID to number of shares at this price level. <br /> <br /> **Example:** <br /> `{   \"p\": 16302.94,   \"x\": {     \"1\": 0.02859424,     \"6\": 0.023455   } }` <br /> <br /> In this example, exchange ID 1 has 0.02859424 shares available at $16,302.94, and exchange ID 6 has 0.023455 shares at the same price level. 
        should("test x") {
            // uncomment below to test the property
            //modelInstance.x shouldBe ("TODO")
        }

    }
}
