/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ExchangeInner

class ExchangeInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExchangeInner
        //val modelInstance = ExchangeInner()

        // to test the property `code` - A unique identifier for the exchange internal to Massive.  This is not an industry code or ISO standard.
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

        // to test the property `id` - The ID of the exchange.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `market` - The market data type that this exchange contains.
        should("test market") {
            // uncomment below to test the property
            //modelInstance.market shouldBe ("TODO")
        }

        // to test the property `mic` - The Market Identification Code or MIC as defined in ISO 10383 (<a rel=\"nofollow\" target=\"_blank\" href=\"https://en.wikipedia.org/wiki/Market_Identifier_Code\">https://en.wikipedia.org/wiki/Market_Identifier_Code</a>).
        should("test mic") {
            // uncomment below to test the property
            //modelInstance.mic shouldBe ("TODO")
        }

        // to test the property `name` - The name of the exchange.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `tape` - The tape id of the exchange.
        should("test tape") {
            // uncomment below to test the property
            //modelInstance.tape shouldBe ("TODO")
        }

        // to test the property `type` - The type of exchange. - TRF = Trade Reporting Facility - exchange = Reporting exchange on the tape 
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

    }
}
