/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Financial

class FinancialTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Financial
        //val modelInstance = Financial()

        // to test the property `reportDate` - Report Date
        should("test reportDate") {
            // uncomment below to test the property
            //modelInstance.reportDate shouldBe ("TODO")
        }

        // to test the property `reportDateStr` - Report date as non date format
        should("test reportDateStr") {
            // uncomment below to test the property
            //modelInstance.reportDateStr shouldBe ("TODO")
        }

        // to test the property `symbol` - Stock Symbol
        should("test symbol") {
            // uncomment below to test the property
            //modelInstance.symbol shouldBe ("TODO")
        }

        // to test the property `cashChange`
        should("test cashChange") {
            // uncomment below to test the property
            //modelInstance.cashChange shouldBe ("TODO")
        }

        // to test the property `cashFlow`
        should("test cashFlow") {
            // uncomment below to test the property
            //modelInstance.cashFlow shouldBe ("TODO")
        }

        // to test the property `costOfRevenue`
        should("test costOfRevenue") {
            // uncomment below to test the property
            //modelInstance.costOfRevenue shouldBe ("TODO")
        }

        // to test the property `currentAssets`
        should("test currentAssets") {
            // uncomment below to test the property
            //modelInstance.currentAssets shouldBe ("TODO")
        }

        // to test the property `currentCash`
        should("test currentCash") {
            // uncomment below to test the property
            //modelInstance.currentCash shouldBe ("TODO")
        }

        // to test the property `currentDebt`
        should("test currentDebt") {
            // uncomment below to test the property
            //modelInstance.currentDebt shouldBe ("TODO")
        }

        // to test the property `grossProfit`
        should("test grossProfit") {
            // uncomment below to test the property
            //modelInstance.grossProfit shouldBe ("TODO")
        }

        // to test the property `netIncome`
        should("test netIncome") {
            // uncomment below to test the property
            //modelInstance.netIncome shouldBe ("TODO")
        }

        // to test the property `operatingExpense`
        should("test operatingExpense") {
            // uncomment below to test the property
            //modelInstance.operatingExpense shouldBe ("TODO")
        }

        // to test the property `operatingGainsLosses`
        should("test operatingGainsLosses") {
            // uncomment below to test the property
            //modelInstance.operatingGainsLosses shouldBe ("TODO")
        }

        // to test the property `operatingIncome`
        should("test operatingIncome") {
            // uncomment below to test the property
            //modelInstance.operatingIncome shouldBe ("TODO")
        }

        // to test the property `operatingRevenue`
        should("test operatingRevenue") {
            // uncomment below to test the property
            //modelInstance.operatingRevenue shouldBe ("TODO")
        }

        // to test the property `researchAndDevelopment`
        should("test researchAndDevelopment") {
            // uncomment below to test the property
            //modelInstance.researchAndDevelopment shouldBe ("TODO")
        }

        // to test the property `shareholderEquity`
        should("test shareholderEquity") {
            // uncomment below to test the property
            //modelInstance.shareholderEquity shouldBe ("TODO")
        }

        // to test the property `totalAssets`
        should("test totalAssets") {
            // uncomment below to test the property
            //modelInstance.totalAssets shouldBe ("TODO")
        }

        // to test the property `totalCash`
        should("test totalCash") {
            // uncomment below to test the property
            //modelInstance.totalCash shouldBe ("TODO")
        }

        // to test the property `totalDebt`
        should("test totalDebt") {
            // uncomment below to test the property
            //modelInstance.totalDebt shouldBe ("TODO")
        }

        // to test the property `totalLiabilities`
        should("test totalLiabilities") {
            // uncomment below to test the property
            //modelInstance.totalLiabilities shouldBe ("TODO")
        }

        // to test the property `totalRevenue`
        should("test totalRevenue") {
            // uncomment below to test the property
            //modelInstance.totalRevenue shouldBe ("TODO")
        }

    }
}
