/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetBenzingaV2News200ResponseResultsInner

class GetBenzingaV2News200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetBenzingaV2News200ResponseResultsInner
        //val modelInstance = GetBenzingaV2News200ResponseResultsInner()

        // to test the property `author` - The name of the journalist or entity that authored the news article.
        should("test author") {
            // uncomment below to test the property
            //modelInstance.author shouldBe ("TODO")
        }

        // to test the property `benzingaId` - The identifer used by Benzinga for this record.
        should("test benzingaId") {
            // uncomment below to test the property
            //modelInstance.benzingaId shouldBe ("TODO")
        }

        // to test the property `lastUpdated` - The timestamp (formatted as an ISO 8601 timestamp) when the news article was last updated in the system.
        should("test lastUpdated") {
            // uncomment below to test the property
            //modelInstance.lastUpdated shouldBe ("TODO")
        }

        // to test the property `published` - The timestamp (formatted as an ISO 8601 timestamp) when the news article was originally published.
        should("test published") {
            // uncomment below to test the property
            //modelInstance.published shouldBe ("TODO")
        }

        // to test the property `title` - The headline of the news article.
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `url` - The direct link to the source of the news article.
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `body` - The full text content of the news article.
        should("test body") {
            // uncomment below to test the property
            //modelInstance.body shouldBe ("TODO")
        }

        // to test the property `channels` - A list of categories or topics that the article belongs to (e.g., 'News', 'Price Target').
        should("test channels") {
            // uncomment below to test the property
            //modelInstance.channels shouldBe ("TODO")
        }

        // to test the property `images` - A list of images associated with the article.
        should("test images") {
            // uncomment below to test the property
            //modelInstance.images shouldBe ("TODO")
        }

        // to test the property `tags` - A list of tags that describe the themes or content of the article.
        should("test tags") {
            // uncomment below to test the property
            //modelInstance.tags shouldBe ("TODO")
        }

        // to test the property `teaser` - A short summary or lead-in to the news article's content.
        should("test teaser") {
            // uncomment below to test the property
            //modelInstance.teaser shouldBe ("TODO")
        }

        // to test the property `tickers` - A list of stock or crypto tickers mentioned in the article.
        should("test tickers") {
            // uncomment below to test the property
            //modelInstance.tickers shouldBe ("TODO")
        }

    }
}
