/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetBenzingaV1Ratings200ResponseResultsInner

class GetBenzingaV1Ratings200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetBenzingaV1Ratings200ResponseResultsInner
        //val modelInstance = GetBenzingaV1Ratings200ResponseResultsInner()

        // to test the property `adjustedPriceTarget` - The current price target adjusted for stock splits and dividends.
        should("test adjustedPriceTarget") {
            // uncomment below to test the property
            //modelInstance.adjustedPriceTarget shouldBe ("TODO")
        }

        // to test the property `analyst` - The name of the individual analyst who issued the rating.
        should("test analyst") {
            // uncomment below to test the property
            //modelInstance.analyst shouldBe ("TODO")
        }

        // to test the property `benzingaAnalystId`
        should("test benzingaAnalystId") {
            // uncomment below to test the property
            //modelInstance.benzingaAnalystId shouldBe ("TODO")
        }

        // to test the property `benzingaCalendarUrl` - A link to the Benzinga calendar page for this ticker
        should("test benzingaCalendarUrl") {
            // uncomment below to test the property
            //modelInstance.benzingaCalendarUrl shouldBe ("TODO")
        }

        // to test the property `benzingaFirmId`
        should("test benzingaFirmId") {
            // uncomment below to test the property
            //modelInstance.benzingaFirmId shouldBe ("TODO")
        }

        // to test the property `benzingaId` - The identifer used by Benzinga for this record.
        should("test benzingaId") {
            // uncomment below to test the property
            //modelInstance.benzingaId shouldBe ("TODO")
        }

        // to test the property `benzingaNewsUrl` - A link to the Benzinga articles page for this ticker
        should("test benzingaNewsUrl") {
            // uncomment below to test the property
            //modelInstance.benzingaNewsUrl shouldBe ("TODO")
        }

        // to test the property `companyName` - The name of the company being rated.
        should("test companyName") {
            // uncomment below to test the property
            //modelInstance.companyName shouldBe ("TODO")
        }

        // to test the property `currency` - The ISO 4217 currency code in which the price target is denominated.
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `date` - The calendar date (formatted as YYYY-MM-DD) when the rating was issued.
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

        // to test the property `firm` - The name of the research firm or investment bank issuing the rating.
        should("test firm") {
            // uncomment below to test the property
            //modelInstance.firm shouldBe ("TODO")
        }

        // to test the property `importance` - A subjective indicator of the importance of the earnings event, on a scale from 0 (lowest) to 5 (highest).
        should("test importance") {
            // uncomment below to test the property
            //modelInstance.importance shouldBe ("TODO")
        }

        // to test the property `lastUpdated` - The timestamp (formatted as an ISO 8601 timestamp) when the rating was last updated in the system.
        should("test lastUpdated") {
            // uncomment below to test the property
            //modelInstance.lastUpdated shouldBe ("TODO")
        }

        // to test the property `notes` - Additional context or commentary.
        should("test notes") {
            // uncomment below to test the property
            //modelInstance.notes shouldBe ("TODO")
        }

        // to test the property `previousAdjustedPriceTarget` - The previous price target adjusted for stock splits and dividends.
        should("test previousAdjustedPriceTarget") {
            // uncomment below to test the property
            //modelInstance.previousAdjustedPriceTarget shouldBe ("TODO")
        }

        // to test the property `previousPriceTarget` - The previous price target set by the analyst.
        should("test previousPriceTarget") {
            // uncomment below to test the property
            //modelInstance.previousPriceTarget shouldBe ("TODO")
        }

        // to test the property `previousRating` - The previous rating set by the analyst.
        should("test previousRating") {
            // uncomment below to test the property
            //modelInstance.previousRating shouldBe ("TODO")
        }

        // to test the property `pricePercentChange`
        should("test pricePercentChange") {
            // uncomment below to test the property
            //modelInstance.pricePercentChange shouldBe ("TODO")
        }

        // to test the property `priceTarget` - The current price target set by the analyst.
        should("test priceTarget") {
            // uncomment below to test the property
            //modelInstance.priceTarget shouldBe ("TODO")
        }

        // to test the property `priceTargetAction` - The description of the directional change in price target. Possible values include: raises, lowers, maintains, announces, sets.
        should("test priceTargetAction") {
            // uncomment below to test the property
            //modelInstance.priceTargetAction shouldBe ("TODO")
        }

        // to test the property `rating` - The current rating set by the analyst.
        should("test rating") {
            // uncomment below to test the property
            //modelInstance.rating shouldBe ("TODO")
        }

        // to test the property `ratingAction` - The description of the change in rating from the firm's last rating. Possible values include: downgrades, maintains, reinstates, reiterates, upgrades, assumes, initiates_coverage_on, terminates_coverage_on, removes, suspends, firm_dissolved.
        should("test ratingAction") {
            // uncomment below to test the property
            //modelInstance.ratingAction shouldBe ("TODO")
        }

        // to test the property `ticker` - The stock symbol of the company being rated.
        should("test ticker") {
            // uncomment below to test the property
            //modelInstance.ticker shouldBe ("TODO")
        }

        // to test the property `time` - The time (formatted as 24-hour HH:MM:SS UTC) when the rating was issued.
        should("test time") {
            // uncomment below to test the property
            //modelInstance.time shouldBe ("TODO")
        }

    }
}
