/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetBenzingaV1Analysts200ResponseResultsInner

class GetBenzingaV1Analysts200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetBenzingaV1Analysts200ResponseResultsInner
        //val modelInstance = GetBenzingaV1Analysts200ResponseResultsInner()

        // to test the property `benzingaFirmId` - The unique identifier assigned by Benzinga to the research firm or investment bank.
        should("test benzingaFirmId") {
            // uncomment below to test the property
            //modelInstance.benzingaFirmId shouldBe ("TODO")
        }

        // to test the property `benzingaId` - The identifier used by Benzinga for this record.
        should("test benzingaId") {
            // uncomment below to test the property
            //modelInstance.benzingaId shouldBe ("TODO")
        }

        // to test the property `firmName` - The name of the research firm or investment bank issuing the ratings.
        should("test firmName") {
            // uncomment below to test the property
            //modelInstance.firmName shouldBe ("TODO")
        }

        // to test the property `fullName` - The full name of the analyst associated with the ratings.
        should("test fullName") {
            // uncomment below to test the property
            //modelInstance.fullName shouldBe ("TODO")
        }

        // to test the property `lastUpdated` - The timestamp (formatted as an ISO 8601 timestamp) when the analyst record was last updated in the system.
        should("test lastUpdated") {
            // uncomment below to test the property
            //modelInstance.lastUpdated shouldBe ("TODO")
        }

        // to test the property `overallAvgReturn` - The average percent price difference per rating since the date of recommendation.
        should("test overallAvgReturn") {
            // uncomment below to test the property
            //modelInstance.overallAvgReturn shouldBe ("TODO")
        }

        // to test the property `overallAvgReturnPercentile` - The analyst's percentile rank based on average return, relative to other analysts.
        should("test overallAvgReturnPercentile") {
            // uncomment below to test the property
            //modelInstance.overallAvgReturnPercentile shouldBe ("TODO")
        }

        // to test the property `overallSuccessRate` - The percentage of gain/loss ratings that resulted in a gain overall.
        should("test overallSuccessRate") {
            // uncomment below to test the property
            //modelInstance.overallSuccessRate shouldBe ("TODO")
        }

        // to test the property `smartScore` - A weighted average of the total_ratings_percentile, overall_avg_return_percentile, and overall_success_rate.
        should("test smartScore") {
            // uncomment below to test the property
            //modelInstance.smartScore shouldBe ("TODO")
        }

        // to test the property `totalRatings` - The total number of ratings issued by the analyst included in the performance calculation.
        should("test totalRatings") {
            // uncomment below to test the property
            //modelInstance.totalRatings shouldBe ("TODO")
        }

        // to test the property `totalRatingsPercentile` - The analyst's percentile rank based on the total number of ratings issued, relative to other analysts.
        should("test totalRatingsPercentile") {
            // uncomment below to test the property
            //modelInstance.totalRatingsPercentile shouldBe ("TODO")
        }

    }
}
