/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetCryptoTrades200ResponseResultsInner

class GetCryptoTrades200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetCryptoTrades200ResponseResultsInner
        //val modelInstance = GetCryptoTrades200ResponseResultsInner()

        // to test the property `exchange` - The exchange ID. See <a href=\"https://massive.com/docs/crypto/get_v3_reference_exchanges\" alt=\"Exchanges\">Exchanges</a> for Massive.com's mapping of exchange IDs.
        should("test exchange") {
            // uncomment below to test the property
            //modelInstance.exchange shouldBe ("TODO")
        }

        // to test the property `price` - The price of the trade in the base currency of the crypto pair.
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

        // to test the property `propertySize` - The size of a trade (also known as volume).
        should("test propertySize") {
            // uncomment below to test the property
            //modelInstance.propertySize shouldBe ("TODO")
        }

        // to test the property `conditions` - A list of condition codes.
        should("test conditions") {
            // uncomment below to test the property
            //modelInstance.conditions shouldBe ("TODO")
        }

        // to test the property `id` - The Trade ID which uniquely identifies a trade on the exchange that the trade happened on.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `participantTimestamp` - The nanosecond Exchange Unix Timestamp. This is the timestamp of when the trade was generated at the exchange.
        should("test participantTimestamp") {
            // uncomment below to test the property
            //modelInstance.participantTimestamp shouldBe ("TODO")
        }

    }
}
