/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetCryptoAggregates200ResponseAllOfResultsInner

class GetCryptoAggregates200ResponseAllOfResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetCryptoAggregates200ResponseAllOfResultsInner
        //val modelInstance = GetCryptoAggregates200ResponseAllOfResultsInner()

        // to test the property `c` - The close price for the symbol in the given time period.
        should("test c") {
            // uncomment below to test the property
            //modelInstance.c shouldBe ("TODO")
        }

        // to test the property `h` - The highest price for the symbol in the given time period.
        should("test h") {
            // uncomment below to test the property
            //modelInstance.h shouldBe ("TODO")
        }

        // to test the property `l` - The lowest price for the symbol in the given time period.
        should("test l") {
            // uncomment below to test the property
            //modelInstance.l shouldBe ("TODO")
        }

        // to test the property `o` - The open price for the symbol in the given time period.
        should("test o") {
            // uncomment below to test the property
            //modelInstance.o shouldBe ("TODO")
        }

        // to test the property `t` - The Unix millisecond timestamp for the start of the aggregate window.
        should("test t") {
            // uncomment below to test the property
            //modelInstance.t shouldBe ("TODO")
        }

        // to test the property `v` - The trading volume of the symbol in the given time period.
        should("test v") {
            // uncomment below to test the property
            //modelInstance.v shouldBe ("TODO")
        }

        // to test the property `n` - The number of transactions in the aggregate window.
        should("test n") {
            // uncomment below to test the property
            //modelInstance.n shouldBe ("TODO")
        }

        // to test the property `vw` - The volume weighted average price.
        should("test vw") {
            // uncomment below to test the property
            //modelInstance.vw shouldBe ("TODO")
        }

    }
}
