/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetEtfGlobalV1Taxonomies200ResponseResultsInner

class GetEtfGlobalV1Taxonomies200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetEtfGlobalV1Taxonomies200ResponseResultsInner
        //val modelInstance = GetEtfGlobalV1Taxonomies200ResponseResultsInner()

        // to test the property `leverageStyle` - Indicates whether the ETF uses leverage to amplify returns ('leveraged'), or does not use leverage ('unleveraged').
        should("test leverageStyle") {
            // uncomment below to test the property
            //modelInstance.leverageStyle shouldBe ("TODO")
        }

        // to test the property `managementClassification` - Defines whether an ETF is considered active under SEC rules, with managers making investment decisions, or passive, tracking an index.
        should("test managementClassification") {
            // uncomment below to test the property
            //modelInstance.managementClassification shouldBe ("TODO")
        }

        // to test the property `productType` - Indicates whether the product is an Exchange-Traded Note ('etn') or an Exchange-Traded Fund ('etf').
        should("test productType") {
            // uncomment below to test the property
            //modelInstance.productType shouldBe ("TODO")
        }

        // to test the property `assetClass` - The primary type of assets held by the ETF, such as equities, bonds, commodities, or other securities.
        should("test assetClass") {
            // uncomment below to test the property
            //modelInstance.assetClass shouldBe ("TODO")
        }

        // to test the property `category` - The broad investment category that describes the ETF's investment focus and strategy.
        should("test category") {
            // uncomment below to test the property
            //modelInstance.category shouldBe ("TODO")
        }

        // to test the property `compositeTicker` - The stock ticker symbol used to identify this ETF product on exchanges.
        should("test compositeTicker") {
            // uncomment below to test the property
            //modelInstance.compositeTicker shouldBe ("TODO")
        }

        // to test the property `country` - The specific country focus of the ETF, if applicable.
        should("test country") {
            // uncomment below to test the property
            //modelInstance.country shouldBe ("TODO")
        }

        // to test the property `creditQualityRating` - Credit quality rating for fixed income ETFs.
        should("test creditQualityRating") {
            // uncomment below to test the property
            //modelInstance.creditQualityRating shouldBe ("TODO")
        }

        // to test the property `description` - The official name and description of the ETF product.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `developmentClass` - The economic development classification of the markets the ETF invests in, such as developed, emerging, or frontier markets.
        should("test developmentClass") {
            // uncomment below to test the property
            //modelInstance.developmentClass shouldBe ("TODO")
        }

        // to test the property `duration` - The duration characteristics for fixed income ETFs.
        should("test duration") {
            // uncomment below to test the property
            //modelInstance.duration shouldBe ("TODO")
        }

        // to test the property `effectiveDate` - The date showing when the information was accurate or valid; some issuers, such as Vanguard, release their data on a delay, so the effective_date can be several weeks earlier than the processed_date.
        should("test effectiveDate") {
            // uncomment below to test the property
            //modelInstance.effectiveDate shouldBe ("TODO")
        }

        // to test the property `esg` - Environmental, Social, and Governance characteristics.
        should("test esg") {
            // uncomment below to test the property
            //modelInstance.esg shouldBe ("TODO")
        }

        // to test the property `exposureMechanism` - The mechanism used to achieve exposure.
        should("test exposureMechanism") {
            // uncomment below to test the property
            //modelInstance.exposureMechanism shouldBe ("TODO")
        }

        // to test the property `factor` - Factor exposure characteristics of the ETF.
        should("test factor") {
            // uncomment below to test the property
            //modelInstance.factor shouldBe ("TODO")
        }

        // to test the property `focus` - The specific investment focus or exposure that the ETF provides, such as sector, geography, or investment style.
        should("test focus") {
            // uncomment below to test the property
            //modelInstance.focus shouldBe ("TODO")
        }

        // to test the property `hedgeReset` - The frequency of hedge reset, if applicable.
        should("test hedgeReset") {
            // uncomment below to test the property
            //modelInstance.hedgeReset shouldBe ("TODO")
        }

        // to test the property `holdingsDisclosureFrequency` - How frequently holdings are disclosed.
        should("test holdingsDisclosureFrequency") {
            // uncomment below to test the property
            //modelInstance.holdingsDisclosureFrequency shouldBe ("TODO")
        }

        // to test the property `inceptionDate` - The date when this ETF was first launched and became available for trading.
        should("test inceptionDate") {
            // uncomment below to test the property
            //modelInstance.inceptionDate shouldBe ("TODO")
        }

        // to test the property `isin` - The International Securities Identification Number, a global standard code for uniquely identifying this ETF worldwide.
        should("test isin") {
            // uncomment below to test the property
            //modelInstance.isin shouldBe ("TODO")
        }

        // to test the property `issuer` - The financial institution or fund company that created and sponsors this ETF.
        should("test issuer") {
            // uncomment below to test the property
            //modelInstance.issuer shouldBe ("TODO")
        }

        // to test the property `leverageReset` - The frequency of leverage reset, if applicable.
        should("test leverageReset") {
            // uncomment below to test the property
            //modelInstance.leverageReset shouldBe ("TODO")
        }

        // to test the property `leveredAmount` - The leverage multiplier applied by the ETF, where positive numbers indicate leveraged exposure and negative numbers indicate inverse exposure.
        should("test leveredAmount") {
            // uncomment below to test the property
            //modelInstance.leveredAmount shouldBe ("TODO")
        }

        // to test the property `managementStyle` - Indicates whether an ETF is managed actively or passively, and the level of transparency or replication method used.
        should("test managementStyle") {
            // uncomment below to test the property
            //modelInstance.managementStyle shouldBe ("TODO")
        }

        // to test the property `maturity` - The maturity profile for fixed income ETFs.
        should("test maturity") {
            // uncomment below to test the property
            //modelInstance.maturity shouldBe ("TODO")
        }

        // to test the property `objective` - The primary investment objective of the ETF.
        should("test objective") {
            // uncomment below to test the property
            //modelInstance.objective shouldBe ("TODO")
        }

        // to test the property `primaryBenchmark` - The main index or benchmark that this ETF is designed to track or replicate.
        should("test primaryBenchmark") {
            // uncomment below to test the property
            //modelInstance.primaryBenchmark shouldBe ("TODO")
        }

        // to test the property `processedDate` - The date showing when ETF Global received and processed the data.
        should("test processedDate") {
            // uncomment below to test the property
            //modelInstance.processedDate shouldBe ("TODO")
        }

        // to test the property `rebalanceFrequency` - How frequently the ETF rebalances its holdings.
        should("test rebalanceFrequency") {
            // uncomment below to test the property
            //modelInstance.rebalanceFrequency shouldBe ("TODO")
        }

        // to test the property `reconstitutionFrequency` - How frequently the index is reconstituted.
        should("test reconstitutionFrequency") {
            // uncomment below to test the property
            //modelInstance.reconstitutionFrequency shouldBe ("TODO")
        }

        // to test the property `region` - The geographic region or area of the world where the ETF concentrates its investments.
        should("test region") {
            // uncomment below to test the property
            //modelInstance.region shouldBe ("TODO")
        }

        // to test the property `secondaryObjective` - The secondary investment objective, if applicable.
        should("test secondaryObjective") {
            // uncomment below to test the property
            //modelInstance.secondaryObjective shouldBe ("TODO")
        }

        // to test the property `selectionMethodology` - The methodology used to select securities.
        should("test selectionMethodology") {
            // uncomment below to test the property
            //modelInstance.selectionMethodology shouldBe ("TODO")
        }

        // to test the property `selectionUniverse` - The universe from which securities are selected.
        should("test selectionUniverse") {
            // uncomment below to test the property
            //modelInstance.selectionUniverse shouldBe ("TODO")
        }

        // to test the property `strategicFocus` - The strategic investment focus of the ETF.
        should("test strategicFocus") {
            // uncomment below to test the property
            //modelInstance.strategicFocus shouldBe ("TODO")
        }

        // to test the property `targetedFocus` - The targeted investment focus of the ETF.
        should("test targetedFocus") {
            // uncomment below to test the property
            //modelInstance.targetedFocus shouldBe ("TODO")
        }

        // to test the property `taxClassification` - The tax structure of the ETF, determining whether investors receive 1099 or K1 tax forms (RIC, Partnership, or UIT).
        should("test taxClassification") {
            // uncomment below to test the property
            //modelInstance.taxClassification shouldBe ("TODO")
        }

        // to test the property `usCode` - A unique identifier code that identifies this ETF in US markets.
        should("test usCode") {
            // uncomment below to test the property
            //modelInstance.usCode shouldBe ("TODO")
        }

        // to test the property `weightingMethodology` - The methodology used to weight holdings.
        should("test weightingMethodology") {
            // uncomment below to test the property
            //modelInstance.weightingMethodology shouldBe ("TODO")
        }

    }
}
