/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetEtfGlobalV1Constituents200ResponseResultsInner

class GetEtfGlobalV1Constituents200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetEtfGlobalV1Constituents200ResponseResultsInner
        //val modelInstance = GetEtfGlobalV1Constituents200ResponseResultsInner()

        // to test the property `assetClass` - The broad category of asset type, such as Equity, Corporate Bond, Municipal Bond, etc.
        should("test assetClass") {
            // uncomment below to test the property
            //modelInstance.assetClass shouldBe ("TODO")
        }

        // to test the property `compositeTicker` - The stock ticker symbol of the ETF that holds these constituent securities.
        should("test compositeTicker") {
            // uncomment below to test the property
            //modelInstance.compositeTicker shouldBe ("TODO")
        }

        // to test the property `constituentName` - The full company or security name of the constituent holding.
        should("test constituentName") {
            // uncomment below to test the property
            //modelInstance.constituentName shouldBe ("TODO")
        }

        // to test the property `constituentTicker` - The stock ticker symbol of the individual security held within the ETF.
        should("test constituentTicker") {
            // uncomment below to test the property
            //modelInstance.constituentTicker shouldBe ("TODO")
        }

        // to test the property `countryOfExchange` - The country where the exchange that lists this constituent security is located.
        should("test countryOfExchange") {
            // uncomment below to test the property
            //modelInstance.countryOfExchange shouldBe ("TODO")
        }

        // to test the property `currencyTraded` - The local currency in which this constituent security is denominated and traded.
        should("test currencyTraded") {
            // uncomment below to test the property
            //modelInstance.currencyTraded shouldBe ("TODO")
        }

        // to test the property `effectiveDate` - The date showing when the information was accurate or valid; some issuers, such as Vanguard, release their data on a delay, so the effective_date can be several weeks earlier than the processed_date.
        should("test effectiveDate") {
            // uncomment below to test the property
            //modelInstance.effectiveDate shouldBe ("TODO")
        }

        // to test the property `exchange` - The name of the stock exchange where this constituent security is primarily traded.
        should("test exchange") {
            // uncomment below to test the property
            //modelInstance.exchange shouldBe ("TODO")
        }

        // to test the property `figi` - The Financial Instrument Global Identifier, an open standard for uniquely identifying financial instruments.
        should("test figi") {
            // uncomment below to test the property
            //modelInstance.figi shouldBe ("TODO")
        }

        // to test the property `isin` - The International Securities Identification Number, a global standard for identifying securities.
        should("test isin") {
            // uncomment below to test the property
            //modelInstance.isin shouldBe ("TODO")
        }

        // to test the property `marketValue` - The total market value of this constituent position held by the ETF.
        should("test marketValue") {
            // uncomment below to test the property
            //modelInstance.marketValue shouldBe ("TODO")
        }

        // to test the property `processedDate` - The date showing when ETF Global received and processed the data.
        should("test processedDate") {
            // uncomment below to test the property
            //modelInstance.processedDate shouldBe ("TODO")
        }

        // to test the property `securityType` - The specific classification of security type using ETF Global's taxonomy, such as Common Equity, Domestic, Global, etc.
        should("test securityType") {
            // uncomment below to test the property
            //modelInstance.securityType shouldBe ("TODO")
        }

        // to test the property `sedol` - The Stock Exchange Daily Official List code, primarily used for securities trading in the UK.
        should("test sedol") {
            // uncomment below to test the property
            //modelInstance.sedol shouldBe ("TODO")
        }

        // to test the property `sharesHeld` - The number of shares of this constituent security that the ETF currently owns.
        should("test sharesHeld") {
            // uncomment below to test the property
            //modelInstance.sharesHeld shouldBe ("TODO")
        }

        // to test the property `usCode` - A unique identifier code for the constituent security in US markets.
        should("test usCode") {
            // uncomment below to test the property
            //modelInstance.usCode shouldBe ("TODO")
        }

        // to test the property `weight` - The percentage weight of this constituent security within the ETF's total portfolio.
        should("test weight") {
            // uncomment below to test the property
            //modelInstance.weight shouldBe ("TODO")
        }

    }
}
