/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetEtfGlobalV1Profiles200ResponseResultsInner
import org.openapitools.client.models.GetEtfGlobalV1Profiles200ResponseResultsInnerCouponExposureInner

class GetEtfGlobalV1Profiles200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetEtfGlobalV1Profiles200ResponseResultsInner
        //val modelInstance = GetEtfGlobalV1Profiles200ResponseResultsInner()

        // to test the property `leverageStyle` - Indicates whether the ETF uses leverage to amplify returns ('leveraged'), or does not use leverage ('unleveraged').
        should("test leverageStyle") {
            // uncomment below to test the property
            //modelInstance.leverageStyle shouldBe ("TODO")
        }

        // to test the property `managementClassification` - Defines whether an ETF is considered active under SEC rules, with managers making investment decisions, or passive, tracking an index.
        should("test managementClassification") {
            // uncomment below to test the property
            //modelInstance.managementClassification shouldBe ("TODO")
        }

        // to test the property `productType` - Indicates whether the product is an Exchange-Traded Note ('etn') or an Exchange-Traded Fund ('etf').
        should("test productType") {
            // uncomment below to test the property
            //modelInstance.productType shouldBe ("TODO")
        }

        // to test the property `administrator` - The administrator of the ETF.
        should("test administrator") {
            // uncomment below to test the property
            //modelInstance.administrator shouldBe ("TODO")
        }

        // to test the property `advisor` - The investment advisor of the ETF.
        should("test advisor") {
            // uncomment below to test the property
            //modelInstance.advisor shouldBe ("TODO")
        }

        // to test the property `assetClass` - The primary type of assets held by the ETF, such as equities, bonds, commodities, or other securities.
        should("test assetClass") {
            // uncomment below to test the property
            //modelInstance.assetClass shouldBe ("TODO")
        }

        // to test the property `aum` - The total assets under management, representing the current market value of all assets held by the ETF.
        should("test aum") {
            // uncomment below to test the property
            //modelInstance.aum shouldBe ("TODO")
        }

        // to test the property `avgDailyTradingVolume` - The average number of shares traded daily over the past month, indicating liquidity and investor interest.
        should("test avgDailyTradingVolume") {
            // uncomment below to test the property
            //modelInstance.avgDailyTradingVolume shouldBe ("TODO")
        }

        // to test the property `bidAskSpread` - The average intraday bid-ask spread as a percentage, calculated by dividing the spread by the lowest ask price sampled during the day.
        should("test bidAskSpread") {
            // uncomment below to test the property
            //modelInstance.bidAskSpread shouldBe ("TODO")
        }

        // to test the property `callVolume` - Call options volume.
        should("test callVolume") {
            // uncomment below to test the property
            //modelInstance.callVolume shouldBe ("TODO")
        }

        // to test the property `category` - The broad investment category that describes the ETF's investment focus and strategy.
        should("test category") {
            // uncomment below to test the property
            //modelInstance.category shouldBe ("TODO")
        }

        // to test the property `compositeTicker` - The stock ticker symbol used to identify this ETF product on exchanges.
        should("test compositeTicker") {
            // uncomment below to test the property
            //modelInstance.compositeTicker shouldBe ("TODO")
        }

        // to test the property `couponExposure` - Coupon exposure breakdown for fixed income ETFs.
        should("test couponExposure") {
            // uncomment below to test the property
            //modelInstance.couponExposure shouldBe ("TODO")
        }

        // to test the property `creationFee` - The fee for creating new shares of the ETF.
        should("test creationFee") {
            // uncomment below to test the property
            //modelInstance.creationFee shouldBe ("TODO")
        }

        // to test the property `creationUnitSize` - The size of creation units for the ETF.
        should("test creationUnitSize") {
            // uncomment below to test the property
            //modelInstance.creationUnitSize shouldBe ("TODO")
        }

        // to test the property `currencyExposure` - Currency exposure breakdown of the ETF.
        should("test currencyExposure") {
            // uncomment below to test the property
            //modelInstance.currencyExposure shouldBe ("TODO")
        }

        // to test the property `custodian` - The custodian of the ETF assets.
        should("test custodian") {
            // uncomment below to test the property
            //modelInstance.custodian shouldBe ("TODO")
        }

        // to test the property `description` - The official name and description of the ETF product.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `developmentClass` - The economic development classification of the markets the ETF invests in, such as developed, emerging, or frontier markets.
        should("test developmentClass") {
            // uncomment below to test the property
            //modelInstance.developmentClass shouldBe ("TODO")
        }

        // to test the property `discountPremium` - Discount or premium to net asset value.
        should("test discountPremium") {
            // uncomment below to test the property
            //modelInstance.discountPremium shouldBe ("TODO")
        }

        // to test the property `distributionFrequency` - How frequently the ETF makes distributions.
        should("test distributionFrequency") {
            // uncomment below to test the property
            //modelInstance.distributionFrequency shouldBe ("TODO")
        }

        // to test the property `distributor` - The distributor of the ETF.
        should("test distributor") {
            // uncomment below to test the property
            //modelInstance.distributor shouldBe ("TODO")
        }

        // to test the property `effectiveDate` - The date showing when the information was accurate or valid; some issuers, such as Vanguard, release their data on a delay, so the effective_date can be several weeks earlier than the processed_date.
        should("test effectiveDate") {
            // uncomment below to test the property
            //modelInstance.effectiveDate shouldBe ("TODO")
        }

        // to test the property `feeWaivers` - Any fee waivers applied to the ETF.
        should("test feeWaivers") {
            // uncomment below to test the property
            //modelInstance.feeWaivers shouldBe ("TODO")
        }

        // to test the property `fiscalYearEnd` - The fiscal year end date for the ETF.
        should("test fiscalYearEnd") {
            // uncomment below to test the property
            //modelInstance.fiscalYearEnd shouldBe ("TODO")
        }

        // to test the property `focus` - The specific investment focus or exposure that the ETF provides, such as sector, geography, or investment style.
        should("test focus") {
            // uncomment below to test the property
            //modelInstance.focus shouldBe ("TODO")
        }

        // to test the property `futuresCommissionMerchant` - The futures commission merchant, if applicable.
        should("test futuresCommissionMerchant") {
            // uncomment below to test the property
            //modelInstance.futuresCommissionMerchant shouldBe ("TODO")
        }

        // to test the property `geographicExposure` - Geographic exposure breakdown of the ETF.
        should("test geographicExposure") {
            // uncomment below to test the property
            //modelInstance.geographicExposure shouldBe ("TODO")
        }

        // to test the property `inceptionDate` - The date when this ETF was first launched and became available for trading.
        should("test inceptionDate") {
            // uncomment below to test the property
            //modelInstance.inceptionDate shouldBe ("TODO")
        }

        // to test the property `industryExposure` - Industry exposure breakdown of the ETF.
        should("test industryExposure") {
            // uncomment below to test the property
            //modelInstance.industryExposure shouldBe ("TODO")
        }

        // to test the property `industryGroupExposure` - Industry group exposure breakdown of the ETF.
        should("test industryGroupExposure") {
            // uncomment below to test the property
            //modelInstance.industryGroupExposure shouldBe ("TODO")
        }

        // to test the property `issuer` - The financial institution or fund company that created and sponsors this ETF.
        should("test issuer") {
            // uncomment below to test the property
            //modelInstance.issuer shouldBe ("TODO")
        }

        // to test the property `leadMarketMaker` - The lead market maker for the ETF.
        should("test leadMarketMaker") {
            // uncomment below to test the property
            //modelInstance.leadMarketMaker shouldBe ("TODO")
        }

        // to test the property `leveredAmount` - The leverage multiplier applied by the ETF, where positive numbers indicate leveraged exposure and negative numbers indicate inverse exposure.
        should("test leveredAmount") {
            // uncomment below to test the property
            //modelInstance.leveredAmount shouldBe ("TODO")
        }

        // to test the property `listingExchange` - The primary exchange where the ETF is listed.
        should("test listingExchange") {
            // uncomment below to test the property
            //modelInstance.listingExchange shouldBe ("TODO")
        }

        // to test the property `managementFee` - The annual fee charged by the fund manager for managing the ETF's portfolio and operations.
        should("test managementFee") {
            // uncomment below to test the property
            //modelInstance.managementFee shouldBe ("TODO")
        }

        // to test the property `maturityExposure` - Maturity exposure breakdown for fixed income ETFs.
        should("test maturityExposure") {
            // uncomment below to test the property
            //modelInstance.maturityExposure shouldBe ("TODO")
        }

        // to test the property `netExpenses` - Net expenses after waivers.
        should("test netExpenses") {
            // uncomment below to test the property
            //modelInstance.netExpenses shouldBe ("TODO")
        }

        // to test the property `numHoldings` - Number of holdings in the ETF.
        should("test numHoldings") {
            // uncomment below to test the property
            //modelInstance.numHoldings shouldBe ("TODO")
        }

        // to test the property `optionsAvailable` - Availability of options on the ETF.
        should("test optionsAvailable") {
            // uncomment below to test the property
            //modelInstance.optionsAvailable shouldBe ("TODO")
        }

        // to test the property `optionsVolume` - Options trading volume for the ETF.
        should("test optionsVolume") {
            // uncomment below to test the property
            //modelInstance.optionsVolume shouldBe ("TODO")
        }

        // to test the property `otherExpenses` - Other expenses charged by the ETF.
        should("test otherExpenses") {
            // uncomment below to test the property
            //modelInstance.otherExpenses shouldBe ("TODO")
        }

        // to test the property `portfolioManager` - The portfolio manager of the ETF.
        should("test portfolioManager") {
            // uncomment below to test the property
            //modelInstance.portfolioManager shouldBe ("TODO")
        }

        // to test the property `primaryBenchmark` - The main index or benchmark that this ETF is designed to track or replicate.
        should("test primaryBenchmark") {
            // uncomment below to test the property
            //modelInstance.primaryBenchmark shouldBe ("TODO")
        }

        // to test the property `processedDate` - The date showing when ETF Global received and processed the data.
        should("test processedDate") {
            // uncomment below to test the property
            //modelInstance.processedDate shouldBe ("TODO")
        }

        // to test the property `putCallRatio` - Put/call ratio for options on the ETF.
        should("test putCallRatio") {
            // uncomment below to test the property
            //modelInstance.putCallRatio shouldBe ("TODO")
        }

        // to test the property `putVolume` - Put options volume.
        should("test putVolume") {
            // uncomment below to test the property
            //modelInstance.putVolume shouldBe ("TODO")
        }

        // to test the property `region` - The geographic region or area of the world where the ETF concentrates its investments.
        should("test region") {
            // uncomment below to test the property
            //modelInstance.region shouldBe ("TODO")
        }

        // to test the property `sectorExposure` - Sector exposure breakdown of the ETF.
        should("test sectorExposure") {
            // uncomment below to test the property
            //modelInstance.sectorExposure shouldBe ("TODO")
        }

        // to test the property `shortInterest` - Short interest in the ETF.
        should("test shortInterest") {
            // uncomment below to test the property
            //modelInstance.shortInterest shouldBe ("TODO")
        }

        // to test the property `subadvisor` - The subadvisor of the ETF, if applicable.
        should("test subadvisor") {
            // uncomment below to test the property
            //modelInstance.subadvisor shouldBe ("TODO")
        }

        // to test the property `subindustryExposure` - Sub-industry exposure breakdown of the ETF.
        should("test subindustryExposure") {
            // uncomment below to test the property
            //modelInstance.subindustryExposure shouldBe ("TODO")
        }

        // to test the property `taxClassification` - The tax structure of the ETF, determining whether investors receive 1099 or K1 tax forms (RIC, Partnership, or UIT).
        should("test taxClassification") {
            // uncomment below to test the property
            //modelInstance.taxClassification shouldBe ("TODO")
        }

        // to test the property `totalExpenses` - The total annual expense ratio of the ETF, including all fees and costs passed on to investors.
        should("test totalExpenses") {
            // uncomment below to test the property
            //modelInstance.totalExpenses shouldBe ("TODO")
        }

        // to test the property `transferAgent` - The transfer agent for the ETF.
        should("test transferAgent") {
            // uncomment below to test the property
            //modelInstance.transferAgent shouldBe ("TODO")
        }

        // to test the property `trustee` - The trustee of the ETF.
        should("test trustee") {
            // uncomment below to test the property
            //modelInstance.trustee shouldBe ("TODO")
        }

    }
}
