/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetEtfGlobalV1Profiles200ResponseResultsInnerCouponExposureInner

class GetEtfGlobalV1Profiles200ResponseResultsInnerCouponExposureInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetEtfGlobalV1Profiles200ResponseResultsInnerCouponExposureInner
        //val modelInstance = GetEtfGlobalV1Profiles200ResponseResultsInnerCouponExposureInner()

        // to test the property `key`
        should("test key") {
            // uncomment below to test the property
            //modelInstance.key shouldBe ("TODO")
        }

        // to test the property ``value``
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

    }
}
