/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetFuturesVXProductsNew200ResponseResultsInner

class GetFuturesVXProductsNew200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetFuturesVXProductsNew200ResponseResultsInner
        //val modelInstance = GetFuturesVXProductsNew200ResponseResultsInner()

        // to test the property `date` - A date string in the format YYYY-MM-DD. This parameter will return point-in-time information about products for the specified day.
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

        // to test the property `assetClass` - The asset class to which the product belongs.
        should("test assetClass") {
            // uncomment below to test the property
            //modelInstance.assetClass shouldBe ("TODO")
        }

        // to test the property `assetSubClass` - The asset sub-class to which the product belongs.
        should("test assetSubClass") {
            // uncomment below to test the property
            //modelInstance.assetSubClass shouldBe ("TODO")
        }

        // to test the property `displayFactor`
        should("test displayFactor") {
            // uncomment below to test the property
            //modelInstance.displayFactor shouldBe ("TODO")
        }

        // to test the property `groupCode`
        should("test groupCode") {
            // uncomment below to test the property
            //modelInstance.groupCode shouldBe ("TODO")
        }

        // to test the property `lastUpdated` - The date and time at which this product was last updated.
        should("test lastUpdated") {
            // uncomment below to test the property
            //modelInstance.lastUpdated shouldBe ("TODO")
        }

        // to test the property `name` - The full name of the product.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `priceQuotation` - The quoted price for this product.
        should("test priceQuotation") {
            // uncomment below to test the property
            //modelInstance.priceQuotation shouldBe ("TODO")
        }

        // to test the property `productCode` - The identifier for the product.
        should("test productCode") {
            // uncomment below to test the property
            //modelInstance.productCode shouldBe ("TODO")
        }

        // to test the property `sector` - The sector to which the product belongs.
        should("test sector") {
            // uncomment below to test the property
            //modelInstance.sector shouldBe ("TODO")
        }

        // to test the property `settlementCurrencyCode` - The currency in which this product settles.
        should("test settlementCurrencyCode") {
            // uncomment below to test the property
            //modelInstance.settlementCurrencyCode shouldBe ("TODO")
        }

        // to test the property `settlementMethod` - The method of settlement for this product (Financially Settled or Deliverable).
        should("test settlementMethod") {
            // uncomment below to test the property
            //modelInstance.settlementMethod shouldBe ("TODO")
        }

        // to test the property `settlementType` - The type of settlement for this product.
        should("test settlementType") {
            // uncomment below to test the property
            //modelInstance.settlementType shouldBe ("TODO")
        }

        // to test the property `subSector` - The sub-sector to which the product belongs.
        should("test subSector") {
            // uncomment below to test the property
            //modelInstance.subSector shouldBe ("TODO")
        }

        // to test the property `tradeCurrencyCode` - The currency in which this product's contracts trade.
        should("test tradeCurrencyCode") {
            // uncomment below to test the property
            //modelInstance.tradeCurrencyCode shouldBe ("TODO")
        }

        // to test the property `tradingVenue` - The trading venue (MIC) for the exchange on which this product's contracts trade.
        should("test tradingVenue") {
            // uncomment below to test the property
            //modelInstance.tradingVenue shouldBe ("TODO")
        }

        // to test the property `type` - The type of product, one of 'single' or 'combo'.
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `unitOfMeasure` - The unit of measure for this product.
        should("test unitOfMeasure") {
            // uncomment below to test the property
            //modelInstance.unitOfMeasure shouldBe ("TODO")
        }

        // to test the property `unitOfMeasureQty` - The quantity of the unit of measure for this product.
        should("test unitOfMeasureQty") {
            // uncomment below to test the property
            //modelInstance.unitOfMeasureQty shouldBe ("TODO")
        }

    }
}
