/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetFuturesVXContracts200ResponseResultsInner

class GetFuturesVXContracts200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetFuturesVXContracts200ResponseResultsInner
        //val modelInstance = GetFuturesVXContracts200ResponseResultsInner()

        // to test the property `active` - Whether or not a given contract was tradeable at the given point in time. Active is true when (first_trade_date <= date >= last_trade_date) and false otherwise.
        should("test active") {
            // uncomment below to test the property
            //modelInstance.active shouldBe ("TODO")
        }

        // to test the property `date` - A date string in the format YYYY-MM-DD. This parameter will return point-in-time information about contracts for the specified day.
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

        // to test the property `daysToMaturity` - The number of calendar days between the 'date' and the contract's final settlement date.
        should("test daysToMaturity") {
            // uncomment below to test the property
            //modelInstance.daysToMaturity shouldBe ("TODO")
        }

        // to test the property `firstTradeDate` - The first day on which the contract was tradeable.
        should("test firstTradeDate") {
            // uncomment below to test the property
            //modelInstance.firstTradeDate shouldBe ("TODO")
        }

        // to test the property `groupCode` - An identifier used to identify logical groups of products. The group_code is only populated for contracts listed for trading on CME Globex.
        should("test groupCode") {
            // uncomment below to test the property
            //modelInstance.groupCode shouldBe ("TODO")
        }

        // to test the property `lastTradeDate` - The last day on which the contract was tradeable.
        should("test lastTradeDate") {
            // uncomment below to test the property
            //modelInstance.lastTradeDate shouldBe ("TODO")
        }

        // to test the property `maxOrderQuantity` - The maximum order quantity.
        should("test maxOrderQuantity") {
            // uncomment below to test the property
            //modelInstance.maxOrderQuantity shouldBe ("TODO")
        }

        // to test the property `minOrderQuantity` - The minimum order quantity.
        should("test minOrderQuantity") {
            // uncomment below to test the property
            //modelInstance.minOrderQuantity shouldBe ("TODO")
        }

        // to test the property `name` - The name of this contract.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `productCode` - The identifier for the contract's product.
        should("test productCode") {
            // uncomment below to test the property
            //modelInstance.productCode shouldBe ("TODO")
        }

        // to test the property `settlementDate` - The date on which this contract settles.
        should("test settlementDate") {
            // uncomment below to test the property
            //modelInstance.settlementDate shouldBe ("TODO")
        }

        // to test the property `settlementTickSize` - The tick size for settlement.
        should("test settlementTickSize") {
            // uncomment below to test the property
            //modelInstance.settlementTickSize shouldBe ("TODO")
        }

        // to test the property `spreadTickSize` - The tick size for spreads.
        should("test spreadTickSize") {
            // uncomment below to test the property
            //modelInstance.spreadTickSize shouldBe ("TODO")
        }

        // to test the property `ticker` - The ticker for the contract.
        should("test ticker") {
            // uncomment below to test the property
            //modelInstance.ticker shouldBe ("TODO")
        }

        // to test the property `tradeTickSize` - The tick size for trades.
        should("test tradeTickSize") {
            // uncomment below to test the property
            //modelInstance.tradeTickSize shouldBe ("TODO")
        }

        // to test the property `tradingVenue` - The trading venue (MIC) for the exchange on which this contract trades.
        should("test tradingVenue") {
            // uncomment below to test the property
            //modelInstance.tradingVenue shouldBe ("TODO")
        }

        // to test the property `type` - The type of contract, one of 'single' or 'combo'. Leaving this filter blank will query for both 'single' and 'combo' types.
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

    }
}
