/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetFuturesVXSnapshot200ResponseResultsInner
import org.openapitools.client.models.GetFuturesVXSnapshot200ResponseResultsInnerDetails
import org.openapitools.client.models.GetFuturesVXSnapshot200ResponseResultsInnerLastMinute
import org.openapitools.client.models.GetFuturesVXSnapshot200ResponseResultsInnerLastQuote
import org.openapitools.client.models.GetFuturesVXSnapshot200ResponseResultsInnerLastTrade
import org.openapitools.client.models.GetFuturesVXSnapshot200ResponseResultsInnerSession

class GetFuturesVXSnapshot200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetFuturesVXSnapshot200ResponseResultsInner
        //val modelInstance = GetFuturesVXSnapshot200ResponseResultsInner()

        // to test the property `details`
        should("test details") {
            // uncomment below to test the property
            //modelInstance.details shouldBe ("TODO")
        }

        // to test the property `lastMinute`
        should("test lastMinute") {
            // uncomment below to test the property
            //modelInstance.lastMinute shouldBe ("TODO")
        }

        // to test the property `lastQuote`
        should("test lastQuote") {
            // uncomment below to test the property
            //modelInstance.lastQuote shouldBe ("TODO")
        }

        // to test the property `lastTrade`
        should("test lastTrade") {
            // uncomment below to test the property
            //modelInstance.lastTrade shouldBe ("TODO")
        }

        // to test the property `session`
        should("test session") {
            // uncomment below to test the property
            //modelInstance.session shouldBe ("TODO")
        }

    }
}
