/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetFuturesVXSnapshot200ResponseResultsInnerSession

class GetFuturesVXSnapshot200ResponseResultsInnerSessionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetFuturesVXSnapshot200ResponseResultsInnerSession
        //val modelInstance = GetFuturesVXSnapshot200ResponseResultsInnerSession()

        // to test the property `change` - The change in price during this session.
        should("test change") {
            // uncomment below to test the property
            //modelInstance.change shouldBe ("TODO")
        }

        // to test the property `changePercent` - The percentage change in price during this session.
        should("test changePercent") {
            // uncomment below to test the property
            //modelInstance.changePercent shouldBe ("TODO")
        }

        // to test the property `close` - The price at the end of the session.
        should("test close") {
            // uncomment below to test the property
            //modelInstance.close shouldBe ("TODO")
        }

        // to test the property `high` - The highest price reached in the session.
        should("test high") {
            // uncomment below to test the property
            //modelInstance.high shouldBe ("TODO")
        }

        // to test the property `low` - The lowest price reached in the session.
        should("test low") {
            // uncomment below to test the property
            //modelInstance.low shouldBe ("TODO")
        }

        // to test the property ``open`` - The opening price at the start of the session.
        should("test `open`") {
            // uncomment below to test the property
            //modelInstance.`open` shouldBe ("TODO")
        }

        // to test the property `previousSettlement` - The settlement price of the previous session.
        should("test previousSettlement") {
            // uncomment below to test the property
            //modelInstance.previousSettlement shouldBe ("TODO")
        }

        // to test the property `settlementPrice` - The final settlement price at the end of the session.
        should("test settlementPrice") {
            // uncomment below to test the property
            //modelInstance.settlementPrice shouldBe ("TODO")
        }

        // to test the property `volume` - The number of contracts traded in the session.
        should("test volume") {
            // uncomment below to test the property
            //modelInstance.volume shouldBe ("TODO")
        }

    }
}
