/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetFuturesTrades200Response
import org.openapitools.client.models.GetFuturesTrades200ResponseResultsInner

class GetFuturesTrades200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetFuturesTrades200Response
        //val modelInstance = GetFuturesTrades200Response()

        // to test the property `status` - The status of this request's response.
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `nextUrl` - If present, this value can be used to fetch the next page of data.
        should("test nextUrl") {
            // uncomment below to test the property
            //modelInstance.nextUrl shouldBe ("TODO")
        }

        // to test the property `results`
        should("test results") {
            // uncomment below to test the property
            //modelInstance.results shouldBe ("TODO")
        }

    }
}
