/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetFedV1InflationExpectations200ResponseResultsInner

class GetFedV1InflationExpectations200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetFedV1InflationExpectations200ResponseResultsInner
        //val modelInstance = GetFedV1InflationExpectations200ResponseResultsInner()

        // to test the property `date` - Calendar date of the observation (YYYY‑MM‑DD).
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

        // to test the property `forwardYears5To10` - 5-Year, 5-Year Forward Inflation Expectation Rate — the market's expectation of average annual inflation for the 5-year period beginning 5 years from now, based on the spread between forward nominal and real yields.
        should("test forwardYears5To10") {
            // uncomment below to test the property
            //modelInstance.forwardYears5To10 shouldBe ("TODO")
        }

        // to test the property `market10Year` - 10-Year Breakeven Inflation Rate — the market's expectation of average annual inflation over the next 10 years, based on the spread between 10-year nominal Treasury yields and 10-year TIPS yields.
        should("test market10Year") {
            // uncomment below to test the property
            //modelInstance.market10Year shouldBe ("TODO")
        }

        // to test the property `market5Year` - 5-Year Breakeven Inflation Rate — the market's expectation of average annual inflation over the next 5 years, based on the spread between 5-year nominal Treasury yields and 5-year TIPS yields.
        should("test market5Year") {
            // uncomment below to test the property
            //modelInstance.market5Year shouldBe ("TODO")
        }

        // to test the property `model10Year` - The Cleveland Fed’s 10-year inflation expectations data estimated expected inflation, risk premiums, and the real interest rate using a model based on Treasury yields, inflation data, swaps, and surveys.
        should("test model10Year") {
            // uncomment below to test the property
            //modelInstance.model10Year shouldBe ("TODO")
        }

        // to test the property `model1Year` - The Cleveland Fed’s 1-year inflation expectations data estimated expected inflation, risk premiums, and the real interest rate using a model based on Treasury yields, inflation data, swaps, and surveys.
        should("test model1Year") {
            // uncomment below to test the property
            //modelInstance.model1Year shouldBe ("TODO")
        }

        // to test the property `model30Year` - The Cleveland Fed’s 30-year inflation expectations data estimated expected inflation, risk premiums, and the real interest rate using a model based on Treasury yields, inflation data, swaps, and surveys.
        should("test model30Year") {
            // uncomment below to test the property
            //modelInstance.model30Year shouldBe ("TODO")
        }

        // to test the property `model5Year` - The Cleveland Fed’s 5-year inflation expectations data estimated expected inflation, risk premiums, and the real interest rate using a model based on Treasury yields, inflation data, swaps, and surveys.
        should("test model5Year") {
            // uncomment below to test the property
            //modelInstance.model5Year shouldBe ("TODO")
        }

    }
}
