/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetFuturesVXSnapshot200ResponseResultsInnerDetails

class GetFuturesVXSnapshot200ResponseResultsInnerDetailsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetFuturesVXSnapshot200ResponseResultsInnerDetails
        //val modelInstance = GetFuturesVXSnapshot200ResponseResultsInnerDetails()

        // to test the property `productCode`
        should("test productCode") {
            // uncomment below to test the property
            //modelInstance.productCode shouldBe ("TODO")
        }

        // to test the property `settlementDate` - The day that this contract is settled.
        should("test settlementDate") {
            // uncomment below to test the property
            //modelInstance.settlementDate shouldBe ("TODO")
        }

        // to test the property `ticker`
        should("test ticker") {
            // uncomment below to test the property
            //modelInstance.ticker shouldBe ("TODO")
        }

    }
}
