/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetFuturesTrades200ResponseResultsInner

class GetFuturesTrades200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetFuturesTrades200ResponseResultsInner
        //val modelInstance = GetFuturesTrades200ResponseResultsInner()

        // to test the property `price` - The price of the trade. This is the actual dollar value per whole contract of this trade. A trade of 100 contracts with a price of $2.00 would be worth a total dollar value of $200.00.
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

        // to test the property `sessionEndDate` - Also known as the trading date, the date of the end of the trading session, in YYYY-MM-DD format.
        should("test sessionEndDate") {
            // uncomment below to test the property
            //modelInstance.sessionEndDate shouldBe ("TODO")
        }

        // to test the property `propertySize` - The total number of contracts exchanged between buyers and sellers on a given trade.
        should("test propertySize") {
            // uncomment below to test the property
            //modelInstance.propertySize shouldBe ("TODO")
        }

        // to test the property `ticker` - ticker of the trade
        should("test ticker") {
            // uncomment below to test the property
            //modelInstance.ticker shouldBe ("TODO")
        }

        // to test the property `timestamp` - The time when the trade was generated at the exchange to nanosecond precision.
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

    }
}
