/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetFedV1Inflation200ResponseResultsInner

class GetFedV1Inflation200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetFedV1Inflation200ResponseResultsInner
        //val modelInstance = GetFedV1Inflation200ResponseResultsInner()

        // to test the property `cpi` - Consumer Price Index (CPI) for All Urban Consumers — a standard measure of headline inflation based on a fixed basket of goods and services, not seasonally adjusted.
        should("test cpi") {
            // uncomment below to test the property
            //modelInstance.cpi shouldBe ("TODO")
        }

        // to test the property `cpiCore` - Core Consumer Price Index — the CPI excluding food and energy, used to understand underlying inflation trends without short-term volatility.
        should("test cpiCore") {
            // uncomment below to test the property
            //modelInstance.cpiCore shouldBe ("TODO")
        }

        // to test the property `cpiYearOverYear` - Year-over-year percentage change in the headline CPI — the most commonly cited inflation rate in public discourse and economic policy.
        should("test cpiYearOverYear") {
            // uncomment below to test the property
            //modelInstance.cpiYearOverYear shouldBe ("TODO")
        }

        // to test the property `date` - Calendar date of the observation (YYYY‑MM‑DD).
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

        // to test the property `pce` - Personal Consumption Expenditures (PCE) Price Index — a broader measure of inflation used by the Federal Reserve, reflecting actual consumer spending patterns and updated basket weights.
        should("test pce") {
            // uncomment below to test the property
            //modelInstance.pce shouldBe ("TODO")
        }

        // to test the property `pceCore` - Core PCE Price Index — excludes food and energy prices from the PCE index, and is the Fed's preferred measure of underlying inflation.
        should("test pceCore") {
            // uncomment below to test the property
            //modelInstance.pceCore shouldBe ("TODO")
        }

        // to test the property `pceSpending` - Nominal Personal Consumption Expenditures — total dollar value of consumer spending in the U.S. economy, reported in billions of dollars and not adjusted for inflation.
        should("test pceSpending") {
            // uncomment below to test the property
            //modelInstance.pceSpending shouldBe ("TODO")
        }

    }
}
