/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetFuturesVXExchanges200ResponseResultsInner

class GetFuturesVXExchanges200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetFuturesVXExchanges200ResponseResultsInner
        //val modelInstance = GetFuturesVXExchanges200ResponseResultsInner()

        // to test the property `id` - Numeric identifier for the futures exchange or trading venue.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name` - Full official name of the futures exchange (e.g., 'Chicago Mercantile Exchange', 'New York Mercantile Exchange').
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `type` - Type of venue - 'exchange' for futures exchanges and derivatives trading platforms.
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `acronym` - Well-known acronym for the exchange (e.g., 'CME', 'NYMEX', 'CBOT', 'COMEX').
        should("test acronym") {
            // uncomment below to test the property
            //modelInstance.acronym shouldBe ("TODO")
        }

        // to test the property `locale` - Geographic location code where the exchange operates.
        should("test locale") {
            // uncomment below to test the property
            //modelInstance.locale shouldBe ("TODO")
        }

        // to test the property `mic` - Market Identifier Code (MIC) - ISO 10383 standard four-character code for the futures market.
        should("test mic") {
            // uncomment below to test the property
            //modelInstance.mic shouldBe ("TODO")
        }

        // to test the property `operatingMic` - Operating Market Identifier Code for the futures exchange.
        should("test operatingMic") {
            // uncomment below to test the property
            //modelInstance.operatingMic shouldBe ("TODO")
        }

        // to test the property `url` - Official website URL of the futures exchange organization.
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

    }
}
