/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetIndicesSnapshot200ResponseResultsInner
import org.openapitools.client.models.GetIndicesSnapshot200ResponseResultsInnerSession

class GetIndicesSnapshot200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetIndicesSnapshot200ResponseResultsInner
        //val modelInstance = GetIndicesSnapshot200ResponseResultsInner()

        // to test the property `ticker` - Ticker of asset queried.
        should("test ticker") {
            // uncomment below to test the property
            //modelInstance.ticker shouldBe ("TODO")
        }

        // to test the property `error` - The error while looking for this ticker.
        should("test error") {
            // uncomment below to test the property
            //modelInstance.error shouldBe ("TODO")
        }

        // to test the property `lastUpdated` - The nanosecond timestamp of when this information was updated.
        should("test lastUpdated") {
            // uncomment below to test the property
            //modelInstance.lastUpdated shouldBe ("TODO")
        }

        // to test the property `marketStatus` - The market status for the market that trades this ticker.
        should("test marketStatus") {
            // uncomment below to test the property
            //modelInstance.marketStatus shouldBe ("TODO")
        }

        // to test the property `message` - The error message while looking for this ticker.
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

        // to test the property `name` - Name of Index.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `session`
        should("test session") {
            // uncomment below to test the property
            //modelInstance.session shouldBe ("TODO")
        }

        // to test the property `timeframe` - The time relevance of the data.
        should("test timeframe") {
            // uncomment below to test the property
            //modelInstance.timeframe shouldBe ("TODO")
        }

        // to test the property `type` - The indices market.
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property ``value`` - Value of Index.
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

    }
}
