/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetIndicesSnapshot200ResponseResultsInnerSession

class GetIndicesSnapshot200ResponseResultsInnerSessionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetIndicesSnapshot200ResponseResultsInnerSession
        //val modelInstance = GetIndicesSnapshot200ResponseResultsInnerSession()

        // to test the property `change` - The value of the change for the index from the previous trading day.
        should("test change") {
            // uncomment below to test the property
            //modelInstance.change shouldBe ("TODO")
        }

        // to test the property `changePercent` - The percent of the change for the index from the previous trading day.
        should("test changePercent") {
            // uncomment below to test the property
            //modelInstance.changePercent shouldBe ("TODO")
        }

        // to test the property `close` - The closing value for the index of the day.
        should("test close") {
            // uncomment below to test the property
            //modelInstance.close shouldBe ("TODO")
        }

        // to test the property `high` - The highest value for the index of the day.
        should("test high") {
            // uncomment below to test the property
            //modelInstance.high shouldBe ("TODO")
        }

        // to test the property `low` - The lowest value for the index of the day.
        should("test low") {
            // uncomment below to test the property
            //modelInstance.low shouldBe ("TODO")
        }

        // to test the property ``open`` - The open value for the index of the day.
        should("test `open`") {
            // uncomment below to test the property
            //modelInstance.`open` shouldBe ("TODO")
        }

        // to test the property `previousClose` - The closing value for the index of previous trading day.
        should("test previousClose") {
            // uncomment below to test the property
            //modelInstance.previousClose shouldBe ("TODO")
        }

    }
}
