/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetLastCryptoTrade200Response
import org.openapitools.client.models.GetLastCryptoTrade200ResponseLast

class GetLastCryptoTrade200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetLastCryptoTrade200Response
        //val modelInstance = GetLastCryptoTrade200Response()

        // to test the property `requestId` - A request id assigned by the server.
        should("test requestId") {
            // uncomment below to test the property
            //modelInstance.requestId shouldBe ("TODO")
        }

        // to test the property `status` - The status of this request's response.
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `symbol` - The symbol pair that was evaluated from the request.
        should("test symbol") {
            // uncomment below to test the property
            //modelInstance.symbol shouldBe ("TODO")
        }

        // to test the property `last`
        should("test last") {
            // uncomment below to test the property
            //modelInstance.last shouldBe ("TODO")
        }

    }
}
