/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetOptionsV1Exchanges200ResponseResultsInner

class GetOptionsV1Exchanges200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetOptionsV1Exchanges200ResponseResultsInner
        //val modelInstance = GetOptionsV1Exchanges200ResponseResultsInner()

        // to test the property `id` - Numeric identifier for the options trading venue or exchange.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name` - Full official name of the options exchange or trading venue.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `type` - Type of venue: 'exchange' for options exchanges, 'SIP' for Securities Information Processors like OPRA (Options Price Reporting Authority).
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `acronym` - Exchange acronym or short name (e.g., 'ISE', 'GEMX') - may be null for some venues.
        should("test acronym") {
            // uncomment below to test the property
            //modelInstance.acronym shouldBe ("TODO")
        }

        // to test the property `locale` - Geographic location code.
        should("test locale") {
            // uncomment below to test the property
            //modelInstance.locale shouldBe ("TODO")
        }

        // to test the property `mic` - Market Identifier Code (MIC) - ISO 10383 standard four-character code identifying the specific options market.
        should("test mic") {
            // uncomment below to test the property
            //modelInstance.mic shouldBe ("TODO")
        }

        // to test the property `operatingMic` - Operating Market Identifier Code - identifies the parent organization or operating entity.
        should("test operatingMic") {
            // uncomment below to test the property
            //modelInstance.operatingMic shouldBe ("TODO")
        }

        // to test the property `participantId` - Single-character participant identifier used in consolidator market data feeds and options trade reporting.
        should("test participantId") {
            // uncomment below to test the property
            //modelInstance.participantId shouldBe ("TODO")
        }

        // to test the property `url` - Official website URL of the organization operating the options exchange.
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

    }
}
