/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetSnapshots200ResponseResultsInnerLastQuote

class GetSnapshots200ResponseResultsInnerLastQuoteTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetSnapshots200ResponseResultsInnerLastQuote
        //val modelInstance = GetSnapshots200ResponseResultsInnerLastQuote()

        // to test the property `ask` - The ask price.
        should("test ask") {
            // uncomment below to test the property
            //modelInstance.ask shouldBe ("TODO")
        }

        // to test the property `bid` - The bid price.
        should("test bid") {
            // uncomment below to test the property
            //modelInstance.bid shouldBe ("TODO")
        }

        // to test the property `lastUpdated` - The nanosecond timestamp of when this information was updated.
        should("test lastUpdated") {
            // uncomment below to test the property
            //modelInstance.lastUpdated shouldBe ("TODO")
        }

        // to test the property `timeframe` - The time relevance of the data.
        should("test timeframe") {
            // uncomment below to test the property
            //modelInstance.timeframe shouldBe ("TODO")
        }

        // to test the property `askExchange` - The ask side exchange ID. See <a href=\"https://polygon.io/docs/options/get_v3_reference_exchanges\" alt=\"Exchanges\">Exchanges</a> for Polygon.io's mapping of exchange IDs.
        should("test askExchange") {
            // uncomment below to test the property
            //modelInstance.askExchange shouldBe ("TODO")
        }

        // to test the property `askSize` - The ask size. This represents the number of round lot orders at the given ask price. The normal round lot size is 100 shares. An ask size of 2 means there are 200 shares available to purchase at the given ask price.
        should("test askSize") {
            // uncomment below to test the property
            //modelInstance.askSize shouldBe ("TODO")
        }

        // to test the property `bidExchange` - The bid side exchange ID. See <a href=\"https://polygon.io/docs/options/get_v3_reference_exchanges\" alt=\"Exchanges\">Exchanges</a> for Polygon.io's mapping of exchange IDs.
        should("test bidExchange") {
            // uncomment below to test the property
            //modelInstance.bidExchange shouldBe ("TODO")
        }

        // to test the property `bidSize` - The bid size. This represents the number of round lot orders at the given bid price. The normal round lot size is 100 shares. A bid size of 2 means there are 200 shares for purchase at the given bid price.
        should("test bidSize") {
            // uncomment below to test the property
            //modelInstance.bidSize shouldBe ("TODO")
        }

        // to test the property `midpoint` - The average of the bid and ask price.
        should("test midpoint") {
            // uncomment below to test the property
            //modelInstance.midpoint shouldBe ("TODO")
        }

    }
}
