/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetStocksV1ShortInterest200ResponseResultsInner

class GetStocksV1ShortInterest200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetStocksV1ShortInterest200ResponseResultsInner
        //val modelInstance = GetStocksV1ShortInterest200ResponseResultsInner()

        // to test the property `avgDailyVolume` - The average daily trading volume for the stock over a specified period, typically used to contextualize short interest.
        should("test avgDailyVolume") {
            // uncomment below to test the property
            //modelInstance.avgDailyVolume shouldBe ("TODO")
        }

        // to test the property `daysToCover` - Calculated as short_interest divided by avg_daily_volume, representing the estimated number of days it would take to cover all short positions based on average trading volume.
        should("test daysToCover") {
            // uncomment below to test the property
            //modelInstance.daysToCover shouldBe ("TODO")
        }

        // to test the property `settlementDate` - The date (formatted as YYYY-MM-DD) on which the short interest data is considered settled, typically based on exchange reporting schedules.
        should("test settlementDate") {
            // uncomment below to test the property
            //modelInstance.settlementDate shouldBe ("TODO")
        }

        // to test the property `shortInterest` - The total number of shares that have been sold short but have not yet been covered or closed out.
        should("test shortInterest") {
            // uncomment below to test the property
            //modelInstance.shortInterest shouldBe ("TODO")
        }

        // to test the property `ticker` - The primary ticker symbol for the stock.
        should("test ticker") {
            // uncomment below to test the property
            //modelInstance.ticker shouldBe ("TODO")
        }

    }
}
