/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetStocksQuotes200ResponseResultsInner

class GetStocksQuotes200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetStocksQuotes200ResponseResultsInner
        //val modelInstance = GetStocksQuotes200ResponseResultsInner()

        // to test the property `participantTimestamp` - The nanosecond accuracy Participant/Exchange Unix Timestamp. This is the timestamp of when the quote was actually generated at the exchange.
        should("test participantTimestamp") {
            // uncomment below to test the property
            //modelInstance.participantTimestamp shouldBe ("TODO")
        }

        // to test the property `sequenceNumber` - The sequence number represents the sequence in which quote events happened. These are increasing and unique per ticker symbol, but will not always be sequential (e.g., 1, 2, 6, 9, 10, 11). Values reset after each trading session/day.
        should("test sequenceNumber") {
            // uncomment below to test the property
            //modelInstance.sequenceNumber shouldBe ("TODO")
        }

        // to test the property `sipTimestamp` - The nanosecond accuracy SIP Unix Timestamp. This is the timestamp of when the SIP received this quote from the exchange which produced it.
        should("test sipTimestamp") {
            // uncomment below to test the property
            //modelInstance.sipTimestamp shouldBe ("TODO")
        }

        // to test the property `askExchange` - The ask exchange ID
        should("test askExchange") {
            // uncomment below to test the property
            //modelInstance.askExchange shouldBe ("TODO")
        }

        // to test the property `askPrice` - The ask price.
        should("test askPrice") {
            // uncomment below to test the property
            //modelInstance.askPrice shouldBe ("TODO")
        }

        // to test the property `askSize` - The ask size. This represents the number of round lot orders at the given ask price. The normal round lot size is 100 shares. An ask size of 2 means there are 200 shares available to purchase at the given ask price.
        should("test askSize") {
            // uncomment below to test the property
            //modelInstance.askSize shouldBe ("TODO")
        }

        // to test the property `bidExchange` - The bid exchange ID
        should("test bidExchange") {
            // uncomment below to test the property
            //modelInstance.bidExchange shouldBe ("TODO")
        }

        // to test the property `bidPrice` - The bid price.
        should("test bidPrice") {
            // uncomment below to test the property
            //modelInstance.bidPrice shouldBe ("TODO")
        }

        // to test the property `bidSize` - The bid size. This represents the number of round lot orders at the given bid price. The normal round lot size is 100 shares. A bid size of 2 means there are 200 shares for purchase at the given bid price.
        should("test bidSize") {
            // uncomment below to test the property
            //modelInstance.bidSize shouldBe ("TODO")
        }

        // to test the property `conditions` - A list of condition codes.
        should("test conditions") {
            // uncomment below to test the property
            //modelInstance.conditions shouldBe ("TODO")
        }

        // to test the property `indicators` - A list of indicator codes.
        should("test indicators") {
            // uncomment below to test the property
            //modelInstance.indicators shouldBe ("TODO")
        }

        // to test the property `tape` - There are 3 tapes which define which exchange the ticker is listed on. These are integers in our objects which represent the letter of the alphabet. Eg: 1 = A, 2 = B, 3 = C. * Tape A is NYSE listed securities * Tape B is NYSE ARCA / NYSE American * Tape C is NASDAQ
        should("test tape") {
            // uncomment below to test the property
            //modelInstance.tape shouldBe ("TODO")
        }

        // to test the property `trfTimestamp` - The nanosecond accuracy TRF (Trade Reporting Facility) Unix Timestamp. This is the timestamp of when the trade reporting facility received this quote.
        should("test trfTimestamp") {
            // uncomment below to test the property
            //modelInstance.trfTimestamp shouldBe ("TODO")
        }

    }
}
