/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetStocksMACD200ResponseResults
import org.openapitools.client.models.GetStocksEMA200ResponseResultsUnderlying
import org.openapitools.client.models.GetStocksMACD200ResponseResultsValuesInner

class GetStocksMACD200ResponseResultsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetStocksMACD200ResponseResults
        //val modelInstance = GetStocksMACD200ResponseResults()

        // to test the property `underlying`
        should("test underlying") {
            // uncomment below to test the property
            //modelInstance.underlying shouldBe ("TODO")
        }

        // to test the property `propertyValues` - Each entry in the values array represents MACD indicator data for a specific timestamp and includes:
        should("test propertyValues") {
            // uncomment below to test the property
            //modelInstance.propertyValues shouldBe ("TODO")
        }

    }
}
