/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetStocksFinancialsV1IncomeStatements200ResponseResultsInner

class GetStocksFinancialsV1IncomeStatements200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetStocksFinancialsV1IncomeStatements200ResponseResultsInner
        //val modelInstance = GetStocksFinancialsV1IncomeStatements200ResponseResultsInner()

        // to test the property `basicEarningsPerShare` - Earnings per share calculated using the weighted average number of basic shares outstanding. For TTM records, recalculated as TTM net income divided by average basic shares outstanding over the four quarters.
        should("test basicEarningsPerShare") {
            // uncomment below to test the property
            //modelInstance.basicEarningsPerShare shouldBe ("TODO")
        }

        // to test the property `basicSharesOutstanding` - Weighted average number of common shares outstanding during the period, used in basic EPS calculation. For TTM records, represents the average over the four most recent quarters.
        should("test basicSharesOutstanding") {
            // uncomment below to test the property
            //modelInstance.basicSharesOutstanding shouldBe ("TODO")
        }

        // to test the property `cik` - The company's Central Index Key (CIK), a unique identifier assigned by the U.S. Securities and Exchange Commission (SEC). You can look up a company’s CIK using the [SEC CIK Lookup tool](https://www.sec.gov/search-filings/cik-lookup).
        should("test cik") {
            // uncomment below to test the property
            //modelInstance.cik shouldBe ("TODO")
        }

        // to test the property `consolidatedNetIncomeLoss` - Total net income or loss for the consolidated entity including all subsidiaries.
        should("test consolidatedNetIncomeLoss") {
            // uncomment below to test the property
            //modelInstance.consolidatedNetIncomeLoss shouldBe ("TODO")
        }

        // to test the property `costOfRevenue` - Direct costs attributable to the production of goods or services sold, also known as cost of goods sold (COGS).
        should("test costOfRevenue") {
            // uncomment below to test the property
            //modelInstance.costOfRevenue shouldBe ("TODO")
        }

        // to test the property `depreciationDepletionAmortization` - Non-cash expenses representing the allocation of asset costs over their useful lives.
        should("test depreciationDepletionAmortization") {
            // uncomment below to test the property
            //modelInstance.depreciationDepletionAmortization shouldBe ("TODO")
        }

        // to test the property `dilutedEarningsPerShare` - Earnings per share calculated using diluted shares outstanding, including the effect of potentially dilutive securities. For TTM records, recalculated as TTM net income divided by average diluted shares outstanding over the four quarters.
        should("test dilutedEarningsPerShare") {
            // uncomment below to test the property
            //modelInstance.dilutedEarningsPerShare shouldBe ("TODO")
        }

        // to test the property `dilutedSharesOutstanding` - Weighted average number of shares outstanding including the dilutive effect of stock options, warrants, and convertible securities. For TTM records, represents the average over the four most recent quarters.
        should("test dilutedSharesOutstanding") {
            // uncomment below to test the property
            //modelInstance.dilutedSharesOutstanding shouldBe ("TODO")
        }

        // to test the property `discontinuedOperations` - After-tax results from business segments that have been or will be disposed of.
        should("test discontinuedOperations") {
            // uncomment below to test the property
            //modelInstance.discontinuedOperations shouldBe ("TODO")
        }

        // to test the property `ebitda` - Earnings before interest, taxes, depreciation, and amortization, a measure of operating performance.
        should("test ebitda") {
            // uncomment below to test the property
            //modelInstance.ebitda shouldBe ("TODO")
        }

        // to test the property `equityInAffiliates` - The company's share of income or losses from equity method investments in affiliated companies.
        should("test equityInAffiliates") {
            // uncomment below to test the property
            //modelInstance.equityInAffiliates shouldBe ("TODO")
        }

        // to test the property `extraordinaryItems` - Unusual and infrequent gains or losses that are both unusual in nature and infrequent in occurrence.
        should("test extraordinaryItems") {
            // uncomment below to test the property
            //modelInstance.extraordinaryItems shouldBe ("TODO")
        }

        // to test the property `filingDate` - The date when the financial statement was filed with the SEC.
        should("test filingDate") {
            // uncomment below to test the property
            //modelInstance.filingDate shouldBe ("TODO")
        }

        // to test the property `fiscalQuarter` - The fiscal quarter number (1, 2, 3, or 4) for the reporting period.
        should("test fiscalQuarter") {
            // uncomment below to test the property
            //modelInstance.fiscalQuarter shouldBe ("TODO")
        }

        // to test the property `fiscalYear` - The fiscal year for the reporting period.
        should("test fiscalYear") {
            // uncomment below to test the property
            //modelInstance.fiscalYear shouldBe ("TODO")
        }

        // to test the property `grossProfit` - Revenue minus cost of revenue, representing profit before operating expenses.
        should("test grossProfit") {
            // uncomment below to test the property
            //modelInstance.grossProfit shouldBe ("TODO")
        }

        // to test the property `incomeBeforeIncomeTaxes` - Pre-tax income calculated as operating income plus total other income/expense.
        should("test incomeBeforeIncomeTaxes") {
            // uncomment below to test the property
            //modelInstance.incomeBeforeIncomeTaxes shouldBe ("TODO")
        }

        // to test the property `incomeTaxes` - Income tax expense or benefit for the period.
        should("test incomeTaxes") {
            // uncomment below to test the property
            //modelInstance.incomeTaxes shouldBe ("TODO")
        }

        // to test the property `interestExpense` - Cost of borrowed funds, including interest on debt and other financing obligations.
        should("test interestExpense") {
            // uncomment below to test the property
            //modelInstance.interestExpense shouldBe ("TODO")
        }

        // to test the property `interestIncome` - Income earned from interest-bearing investments and cash equivalents.
        should("test interestIncome") {
            // uncomment below to test the property
            //modelInstance.interestIncome shouldBe ("TODO")
        }

        // to test the property `netIncomeLossAttributableCommonShareholders` - Net income or loss available to common shareholders after preferred dividends and noncontrolling interests.
        should("test netIncomeLossAttributableCommonShareholders") {
            // uncomment below to test the property
            //modelInstance.netIncomeLossAttributableCommonShareholders shouldBe ("TODO")
        }

        // to test the property `noncontrollingInterest` - The portion of net income attributable to minority shareholders in consolidated subsidiaries.
        should("test noncontrollingInterest") {
            // uncomment below to test the property
            //modelInstance.noncontrollingInterest shouldBe ("TODO")
        }

        // to test the property `operatingIncome` - Income from operations calculated as gross profit minus total operating expenses, excluding non-operating items.
        should("test operatingIncome") {
            // uncomment below to test the property
            //modelInstance.operatingIncome shouldBe ("TODO")
        }

        // to test the property `otherIncomeExpense` - Non-operating income and expenses not related to the company's core business operations.
        should("test otherIncomeExpense") {
            // uncomment below to test the property
            //modelInstance.otherIncomeExpense shouldBe ("TODO")
        }

        // to test the property `otherOperatingExpenses` - Operating expenses not classified in the main expense categories.
        should("test otherOperatingExpenses") {
            // uncomment below to test the property
            //modelInstance.otherOperatingExpenses shouldBe ("TODO")
        }

        // to test the property `periodEnd` - The last date of the reporting period (formatted as YYYY-MM-DD).
        should("test periodEnd") {
            // uncomment below to test the property
            //modelInstance.periodEnd shouldBe ("TODO")
        }

        // to test the property `preferredStockDividendsDeclared` - Dividends declared on preferred stock during the period.
        should("test preferredStockDividendsDeclared") {
            // uncomment below to test the property
            //modelInstance.preferredStockDividendsDeclared shouldBe ("TODO")
        }

        // to test the property `researchDevelopment` - Expenses incurred for research and development activities to create new products or improve existing ones.
        should("test researchDevelopment") {
            // uncomment below to test the property
            //modelInstance.researchDevelopment shouldBe ("TODO")
        }

        // to test the property `revenue` - Total revenue or net sales for the period, representing the company's gross income from operations.
        should("test revenue") {
            // uncomment below to test the property
            //modelInstance.revenue shouldBe ("TODO")
        }

        // to test the property `sellingGeneralAdministrative` - Expenses related to selling products and general administrative costs not directly tied to production.
        should("test sellingGeneralAdministrative") {
            // uncomment below to test the property
            //modelInstance.sellingGeneralAdministrative shouldBe ("TODO")
        }

        // to test the property `tickers` - A list of ticker symbols under which the company is listed. Multiple symbols may indicate different share classes for the same company.
        should("test tickers") {
            // uncomment below to test the property
            //modelInstance.tickers shouldBe ("TODO")
        }

        // to test the property `timeframe` - The reporting period type. Possible values include: quarterly, annual, trailing_twelve_months.
        should("test timeframe") {
            // uncomment below to test the property
            //modelInstance.timeframe shouldBe ("TODO")
        }

        // to test the property `totalOperatingExpenses` - Sum of all operating expenses including cost of revenue, SG&A, R&D, depreciation, and other operating expenses.
        should("test totalOperatingExpenses") {
            // uncomment below to test the property
            //modelInstance.totalOperatingExpenses shouldBe ("TODO")
        }

        // to test the property `totalOtherIncomeExpense` - Net total of all non-operating income and expenses including interest income, interest expense, and other items.
        should("test totalOtherIncomeExpense") {
            // uncomment below to test the property
            //modelInstance.totalOtherIncomeExpense shouldBe ("TODO")
        }

    }
}
