/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetTicker200ResponseResults
import org.openapitools.client.models.GetTicker200ResponseResultsAddress
import org.openapitools.client.models.GetTicker200ResponseResultsBranding

class GetTicker200ResponseResultsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetTicker200ResponseResults
        //val modelInstance = GetTicker200ResponseResults()

        // to test the property `active` - Whether or not the asset is actively traded. False means the asset has been delisted.
        should("test active") {
            // uncomment below to test the property
            //modelInstance.active shouldBe ("TODO")
        }

        // to test the property `currencyName` - The name of the currency that this asset is traded with.
        should("test currencyName") {
            // uncomment below to test the property
            //modelInstance.currencyName shouldBe ("TODO")
        }

        // to test the property `locale` - The locale of the asset.
        should("test locale") {
            // uncomment below to test the property
            //modelInstance.locale shouldBe ("TODO")
        }

        // to test the property `market` - The market type of the asset.
        should("test market") {
            // uncomment below to test the property
            //modelInstance.market shouldBe ("TODO")
        }

        // to test the property `name` - The name of the asset. For stocks/equities this will be the companies registered name. For crypto/fx this will be the name of the currency or coin pair.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `ticker` - The exchange symbol that this item is traded under.
        should("test ticker") {
            // uncomment below to test the property
            //modelInstance.ticker shouldBe ("TODO")
        }

        // to test the property `address`
        should("test address") {
            // uncomment below to test the property
            //modelInstance.address shouldBe ("TODO")
        }

        // to test the property `branding`
        should("test branding") {
            // uncomment below to test the property
            //modelInstance.branding shouldBe ("TODO")
        }

        // to test the property `cik` - The CIK number for this ticker. Find more information [here](https://en.wikipedia.org/wiki/Central_Index_Key).
        should("test cik") {
            // uncomment below to test the property
            //modelInstance.cik shouldBe ("TODO")
        }

        // to test the property `compositeFigi` - The composite OpenFIGI number for this ticker. Find more information [here](https://www.openfigi.com/about/figi)
        should("test compositeFigi") {
            // uncomment below to test the property
            //modelInstance.compositeFigi shouldBe ("TODO")
        }

        // to test the property `delistedUtc` - The last date that the asset was traded.
        should("test delistedUtc") {
            // uncomment below to test the property
            //modelInstance.delistedUtc shouldBe ("TODO")
        }

        // to test the property `description` - A description of the company and what they do/offer.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `homepageUrl` - The URL of the company's website homepage.
        should("test homepageUrl") {
            // uncomment below to test the property
            //modelInstance.homepageUrl shouldBe ("TODO")
        }

        // to test the property `listDate` - The date that the symbol was first publicly listed in the format YYYY-MM-DD.
        should("test listDate") {
            // uncomment below to test the property
            //modelInstance.listDate shouldBe ("TODO")
        }

        // to test the property `marketCap` - The most recent close price of the ticker multiplied by weighted outstanding shares.
        should("test marketCap") {
            // uncomment below to test the property
            //modelInstance.marketCap shouldBe ("TODO")
        }

        // to test the property `phoneNumber` - The phone number for the company behind this ticker.
        should("test phoneNumber") {
            // uncomment below to test the property
            //modelInstance.phoneNumber shouldBe ("TODO")
        }

        // to test the property `primaryExchange` - The ISO code of the primary listing exchange for this asset.
        should("test primaryExchange") {
            // uncomment below to test the property
            //modelInstance.primaryExchange shouldBe ("TODO")
        }

        // to test the property `roundLot` - Round lot size of this security.
        should("test roundLot") {
            // uncomment below to test the property
            //modelInstance.roundLot shouldBe ("TODO")
        }

        // to test the property `shareClassFigi` - The share Class OpenFIGI number for this ticker. Find more information [here](https://www.openfigi.com/about/figi)
        should("test shareClassFigi") {
            // uncomment below to test the property
            //modelInstance.shareClassFigi shouldBe ("TODO")
        }

        // to test the property `shareClassSharesOutstanding` - The recorded number of outstanding shares for this particular share class.
        should("test shareClassSharesOutstanding") {
            // uncomment below to test the property
            //modelInstance.shareClassSharesOutstanding shouldBe ("TODO")
        }

        // to test the property `sicCode` - The standard industrial classification code for this ticker.  For a list of SIC Codes, see the SEC's <a rel=\"nofollow\" target=\"_blank\" href=\"https://www.sec.gov/info/edgar/siccodes.htm\">SIC Code List</a>.
        should("test sicCode") {
            // uncomment below to test the property
            //modelInstance.sicCode shouldBe ("TODO")
        }

        // to test the property `sicDescription` - A description of this ticker's SIC code.
        should("test sicDescription") {
            // uncomment below to test the property
            //modelInstance.sicDescription shouldBe ("TODO")
        }

        // to test the property `tickerRoot` - The root of a specified ticker. For example, the root of BRK.A is BRK.
        should("test tickerRoot") {
            // uncomment below to test the property
            //modelInstance.tickerRoot shouldBe ("TODO")
        }

        // to test the property `tickerSuffix` - The suffix of a specified ticker. For example, the suffix of BRK.A is A.
        should("test tickerSuffix") {
            // uncomment below to test the property
            //modelInstance.tickerSuffix shouldBe ("TODO")
        }

        // to test the property `totalEmployees` - The approximate number of employees for the company.
        should("test totalEmployees") {
            // uncomment below to test the property
            //modelInstance.totalEmployees shouldBe ("TODO")
        }

        // to test the property `type` - The type of the asset. Find the types that we support via our [Ticker Types API](https://massive.com/docs/rest/stocks/tickers/ticker-types).
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `weightedSharesOutstanding` - The shares outstanding calculated assuming all shares of other share classes are converted to this share class.
        should("test weightedSharesOutstanding") {
            // uncomment below to test the property
            //modelInstance.weightedSharesOutstanding shouldBe ("TODO")
        }

    }
}
