/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.GetTicker200ResponseResultsBranding

class GetTicker200ResponseResultsBrandingTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetTicker200ResponseResultsBranding
        //val modelInstance = GetTicker200ResponseResultsBranding()

        // to test the property `iconUrl` - A link to this ticker's company's icon. Icon's are generally smaller, square images that represent the company at a glance. Note that you must provide an API key when accessing this URL. See the \"Authentication\" section at the top of this page for more details.
        should("test iconUrl") {
            // uncomment below to test the property
            //modelInstance.iconUrl shouldBe ("TODO")
        }

        // to test the property `logoUrl` - A link to this ticker's company's logo. Note that you must provide an API key when accessing this URL. See the \"Authentication\" section at the top of this page for more details.
        should("test logoUrl") {
            // uncomment below to test the property
            //modelInstance.logoUrl shouldBe ("TODO")
        }

    }
}
