/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ListIPOs200ResponseResultsInner

class ListIPOs200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListIPOs200ResponseResultsInner
        //val modelInstance = ListIPOs200ResponseResultsInner()

        // to test the property `ipoStatus` - The status of the IPO event. IPO events start out as status \"rumor\" or \"pending\". On listing day, the status changes to \"new\". After the listing day, the status changes to \"history\".  The status \"direct_listing_process\" corresponds to a type of offering where, instead of going through all the IPO processes, the company decides to list its shares directly on an exchange, without using an investment bank or other intermediaries. This is called a direct listing, direct placement, or direct public offering (DPO).
        should("test ipoStatus") {
            // uncomment below to test the property
            //modelInstance.ipoStatus shouldBe ("TODO")
        }

        // to test the property `issuerName` - Name of issuer.
        should("test issuerName") {
            // uncomment below to test the property
            //modelInstance.issuerName shouldBe ("TODO")
        }

        // to test the property `lastUpdated` - The date when the IPO event was last modified.
        should("test lastUpdated") {
            // uncomment below to test the property
            //modelInstance.lastUpdated shouldBe ("TODO")
        }

        // to test the property `securityType` - The classification of the stock. For example, \"CS\" stands for Common Stock.
        should("test securityType") {
            // uncomment below to test the property
            //modelInstance.securityType shouldBe ("TODO")
        }

        // to test the property `ticker` - The ticker symbol of the IPO event.
        should("test ticker") {
            // uncomment below to test the property
            //modelInstance.ticker shouldBe ("TODO")
        }

        // to test the property `announcedDate` - The date when the IPO event was announced.
        should("test announcedDate") {
            // uncomment below to test the property
            //modelInstance.announcedDate shouldBe ("TODO")
        }

        // to test the property `currencyCode` - Underlying currency of the security.
        should("test currencyCode") {
            // uncomment below to test the property
            //modelInstance.currencyCode shouldBe ("TODO")
        }

        // to test the property `finalIssuePrice` - The price set by the company and its underwriters before the IPO goes live.
        should("test finalIssuePrice") {
            // uncomment below to test the property
            //modelInstance.finalIssuePrice shouldBe ("TODO")
        }

        // to test the property `highestOfferPrice` - The highest price within the IPO price range that the company might use to price the shares.
        should("test highestOfferPrice") {
            // uncomment below to test the property
            //modelInstance.highestOfferPrice shouldBe ("TODO")
        }

        // to test the property `isin` - International Securities Identification Number. This is a unique twelve-digit code that is assigned to every security issuance in the world.
        should("test isin") {
            // uncomment below to test the property
            //modelInstance.isin shouldBe ("TODO")
        }

        // to test the property `listingDate` - First trading date for the newly listed entity.
        should("test listingDate") {
            // uncomment below to test the property
            //modelInstance.listingDate shouldBe ("TODO")
        }

        // to test the property `lotSize` - The minimum number of shares that can be bought or sold in a single transaction.
        should("test lotSize") {
            // uncomment below to test the property
            //modelInstance.lotSize shouldBe ("TODO")
        }

        // to test the property `lowestOfferPrice` - The lowest price within the IPO price range that the company is willing to offer its shares to investors.
        should("test lowestOfferPrice") {
            // uncomment below to test the property
            //modelInstance.lowestOfferPrice shouldBe ("TODO")
        }

        // to test the property `maxSharesOffered` - The upper limit of the shares that the company is offering to investors.
        should("test maxSharesOffered") {
            // uncomment below to test the property
            //modelInstance.maxSharesOffered shouldBe ("TODO")
        }

        // to test the property `minSharesOffered` - The lower limit of shares that the company is willing to sell in the IPO.
        should("test minSharesOffered") {
            // uncomment below to test the property
            //modelInstance.minSharesOffered shouldBe ("TODO")
        }

        // to test the property `primaryExchange` - Market Identifier Code (MIC) of the primary exchange where the security is listed. The Market Identifier Code (MIC) (ISO 10383) is a unique identification code used to identify securities trading exchanges, regulated and non-regulated trading markets.
        should("test primaryExchange") {
            // uncomment below to test the property
            //modelInstance.primaryExchange shouldBe ("TODO")
        }

        // to test the property `securityDescription` - Description of the security.
        should("test securityDescription") {
            // uncomment below to test the property
            //modelInstance.securityDescription shouldBe ("TODO")
        }

        // to test the property `sharesOutstanding` - The total number of shares that the company has issued and are held by investors.
        should("test sharesOutstanding") {
            // uncomment below to test the property
            //modelInstance.sharesOutstanding shouldBe ("TODO")
        }

        // to test the property `totalOfferSize` - The total amount raised by the company for IPO.
        should("test totalOfferSize") {
            // uncomment below to test the property
            //modelInstance.totalOfferSize shouldBe ("TODO")
        }

        // to test the property `usCode` - This is a unique nine-character alphanumeric code that identifies a North American financial security for the purposes of facilitating clearing and settlement of trades.
        should("test usCode") {
            // uncomment below to test the property
            //modelInstance.usCode shouldBe ("TODO")
        }

    }
}
