/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ListNews200ResponseResultsInnerInsightsInner

class ListNews200ResponseResultsInnerInsightsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListNews200ResponseResultsInnerInsightsInner
        //val modelInstance = ListNews200ResponseResultsInnerInsightsInner()

        // to test the property `sentiment` - The sentiment of the insight.
        should("test sentiment") {
            // uncomment below to test the property
            //modelInstance.sentiment shouldBe ("TODO")
        }

        // to test the property `sentimentReasoning` - The reasoning behind the sentiment.
        should("test sentimentReasoning") {
            // uncomment below to test the property
            //modelInstance.sentimentReasoning shouldBe ("TODO")
        }

        // to test the property `ticker` - The ticker symbol associated with the insight.
        should("test ticker") {
            // uncomment below to test the property
            //modelInstance.ticker shouldBe ("TODO")
        }

    }
}
