/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ListConditions200ResponseResultsInnerUpdateRulesConsolidated

class ListConditions200ResponseResultsInnerUpdateRulesConsolidatedTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListConditions200ResponseResultsInnerUpdateRulesConsolidated
        //val modelInstance = ListConditions200ResponseResultsInnerUpdateRulesConsolidated()

        // to test the property `updatesHighLow` - Whether or not trades with this condition update the high/low.
        should("test updatesHighLow") {
            // uncomment below to test the property
            //modelInstance.updatesHighLow shouldBe ("TODO")
        }

        // to test the property `updatesOpenClose` - Whether or not trades with this condition update the open/close.
        should("test updatesOpenClose") {
            // uncomment below to test the property
            //modelInstance.updatesOpenClose shouldBe ("TODO")
        }

        // to test the property `updatesVolume` - Whether or not trades with this condition update the volume.
        should("test updatesVolume") {
            // uncomment below to test the property
            //modelInstance.updatesVolume shouldBe ("TODO")
        }

    }
}
