/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ListProducts200ResponseResultsInner

class ListProducts200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListProducts200ResponseResultsInner
        //val modelInstance = ListProducts200ResponseResultsInner()

        // to test the property `productCode` - The unique identifier for the product.
        should("test productCode") {
            // uncomment below to test the property
            //modelInstance.productCode shouldBe ("TODO")
        }

        // to test the property `asOf` - The point-in-time date for the given product - e.g. if 'as_of' is set to 2024-11-05, then these were the details for this product on that day.
        should("test asOf") {
            // uncomment below to test the property
            //modelInstance.asOf shouldBe ("TODO")
        }

        // to test the property `assetClass` - The asset class to which the product belongs.
        should("test assetClass") {
            // uncomment below to test the property
            //modelInstance.assetClass shouldBe ("TODO")
        }

        // to test the property `assetSubClass` - The asset sub-class to which the product belongs.
        should("test assetSubClass") {
            // uncomment below to test the property
            //modelInstance.assetSubClass shouldBe ("TODO")
        }

        // to test the property `clearingChannel` - The clearing channel for this product. Indicates whether the product can be cleared only through exchanges or through both exchanges and over-the-counter.
        should("test clearingChannel") {
            // uncomment below to test the property
            //modelInstance.clearingChannel shouldBe ("TODO")
        }

        // to test the property `lastUpdated` - The date and time at which this product was last updated.
        should("test lastUpdated") {
            // uncomment below to test the property
            //modelInstance.lastUpdated shouldBe ("TODO")
        }

        // to test the property `name` - The full name of the product.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `priceQuotation` - The quoted price for this product.
        should("test priceQuotation") {
            // uncomment below to test the property
            //modelInstance.priceQuotation shouldBe ("TODO")
        }

        // to test the property `sector` - The sector to which the product belongs.
        should("test sector") {
            // uncomment below to test the property
            //modelInstance.sector shouldBe ("TODO")
        }

        // to test the property `settlementCurrencyCode` - The currency in which this product settles.
        should("test settlementCurrencyCode") {
            // uncomment below to test the property
            //modelInstance.settlementCurrencyCode shouldBe ("TODO")
        }

        // to test the property `settlementMethod` - The method of settlement for this product (Financially Settled or Deliverable).
        should("test settlementMethod") {
            // uncomment below to test the property
            //modelInstance.settlementMethod shouldBe ("TODO")
        }

        // to test the property `settlementType` - The type of settlement for this product.
        should("test settlementType") {
            // uncomment below to test the property
            //modelInstance.settlementType shouldBe ("TODO")
        }

        // to test the property `subSector` - The sub-sector to which the product belongs.
        should("test subSector") {
            // uncomment below to test the property
            //modelInstance.subSector shouldBe ("TODO")
        }

        // to test the property `tradeCurrencyCode` - The currency in which this product trades.
        should("test tradeCurrencyCode") {
            // uncomment below to test the property
            //modelInstance.tradeCurrencyCode shouldBe ("TODO")
        }

        // to test the property `tradingVenue` - The trading venue (MIC) for the exchange on which this contract trades.
        should("test tradingVenue") {
            // uncomment below to test the property
            //modelInstance.tradingVenue shouldBe ("TODO")
        }

        // to test the property `type` - The type of product, one of \"single\" or \"combo\".
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `unitOfMeasure` - The unit of measure for this product.
        should("test unitOfMeasure") {
            // uncomment below to test the property
            //modelInstance.unitOfMeasure shouldBe ("TODO")
        }

        // to test the property `unitOfMeasureQuantity` - The quantity of the unit of measure for this product.
        should("test unitOfMeasureQuantity") {
            // uncomment below to test the property
            //modelInstance.unitOfMeasureQuantity shouldBe ("TODO")
        }

    }
}
