/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.MarketsResultsInner

class MarketsResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MarketsResultsInner
        //val modelInstance = MarketsResultsInner()

        // to test the property `desc` - A description of the market.
        should("test desc") {
            // uncomment below to test the property
            //modelInstance.desc shouldBe ("TODO")
        }

        // to test the property `market` - The name of the market.
        should("test market") {
            // uncomment below to test the property
            //modelInstance.market shouldBe ("TODO")
        }

    }
}
