/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.MarketStatusExchanges

class MarketStatusExchangesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MarketStatusExchanges
        //val modelInstance = MarketStatusExchanges()

        // to test the property `nasdaq` - The status of the Nasdaq market.
        should("test nasdaq") {
            // uncomment below to test the property
            //modelInstance.nasdaq shouldBe ("TODO")
        }

        // to test the property `nyse` - The status of the NYSE market.
        should("test nyse") {
            // uncomment below to test the property
            //modelInstance.nyse shouldBe ("TODO")
        }

        // to test the property `otc` - The status of the OTC market.
        should("test otc") {
            // uncomment below to test the property
            //modelInstance.otc shouldBe ("TODO")
        }

    }
}
