/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ProductSchedules200ResponseResultsInner
import org.openapitools.client.models.ProductSchedules200ResponseResultsInnerScheduleInner

class ProductSchedules200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProductSchedules200ResponseResultsInner
        //val modelInstance = ProductSchedules200ResponseResultsInner()

        // to test the property `productCode` - The product code for the futures product to which this schedule applies.
        should("test productCode") {
            // uncomment below to test the property
            //modelInstance.productCode shouldBe ("TODO")
        }

        // to test the property `schedule`
        should("test schedule") {
            // uncomment below to test the property
            //modelInstance.schedule shouldBe ("TODO")
        }

        // to test the property `sessionEndDate` - The date on which the schedule's trading day ended (sometimes referred to as trading date) formatted as `YYYY-MM-DD`. Note that although there is no time component on this attribute, the day refers to Central Time.
        should("test sessionEndDate") {
            // uncomment below to test the property
            //modelInstance.sessionEndDate shouldBe ("TODO")
        }

        // to test the property `productName` - The name of the futures product to which this schedule applies.
        should("test productName") {
            // uncomment below to test the property
            //modelInstance.productName shouldBe ("TODO")
        }

        // to test the property `tradingVenue` - The trading venue (MIC) for the exchange on which this schedule's product trades.
        should("test tradingVenue") {
            // uncomment below to test the property
            //modelInstance.tradingVenue shouldBe ("TODO")
        }

    }
}
