/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ProductSchedules200Response
import org.openapitools.client.models.ProductSchedules200ResponseResultsInner

class ProductSchedules200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProductSchedules200Response
        //val modelInstance = ProductSchedules200Response()

        // to test the property `requestId` - The unique identifier for the request.
        should("test requestId") {
            // uncomment below to test the property
            //modelInstance.requestId shouldBe ("TODO")
        }

        // to test the property `status` - The status of the response.
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `error` - An optional error message for failed requests when available.
        should("test error") {
            // uncomment below to test the property
            //modelInstance.error shouldBe ("TODO")
        }

        // to test the property `nextUrl` - If present, this value can be used to fetch the next page of data.
        should("test nextUrl") {
            // uncomment below to test the property
            //modelInstance.nextUrl shouldBe ("TODO")
        }

        // to test the property `results` - The list of schedules for the specified product.
        should("test results") {
            // uncomment below to test the property
            //modelInstance.results shouldBe ("TODO")
        }

    }
}
