/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.StocksTickerResultsOTC
import org.openapitools.client.models.GetStocksAggregates200ResponseAllOfResultsInner

class StocksTickerResultsOTCTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StocksTickerResultsOTC
        //val modelInstance = StocksTickerResultsOTC()

        // to test the property `results` - An array of results containing the requested data.
        should("test results") {
            // uncomment below to test the property
            //modelInstance.results shouldBe ("TODO")
        }

    }
}
