/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.StocksOpenClose

class StocksOpenCloseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StocksOpenClose
        //val modelInstance = StocksOpenClose()

        // to test the property `close` - The close price for the symbol in the given time period.
        should("test close") {
            // uncomment below to test the property
            //modelInstance.close shouldBe ("TODO")
        }

        // to test the property `from` - The requested date.
        should("test from") {
            // uncomment below to test the property
            //modelInstance.from shouldBe ("TODO")
        }

        // to test the property `high` - The highest price for the symbol in the given time period.
        should("test high") {
            // uncomment below to test the property
            //modelInstance.high shouldBe ("TODO")
        }

        // to test the property `low` - The lowest price for the symbol in the given time period.
        should("test low") {
            // uncomment below to test the property
            //modelInstance.low shouldBe ("TODO")
        }

        // to test the property ``open`` - The open price for the symbol in the given time period.
        should("test `open`") {
            // uncomment below to test the property
            //modelInstance.`open` shouldBe ("TODO")
        }

        // to test the property `status` - The status of this request's response.
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `symbol` - The exchange symbol that this item is traded under.
        should("test symbol") {
            // uncomment below to test the property
            //modelInstance.symbol shouldBe ("TODO")
        }

        // to test the property `volume` - The trading volume of the symbol in the given time period.
        should("test volume") {
            // uncomment below to test the property
            //modelInstance.volume shouldBe ("TODO")
        }

        // to test the property `afterHours` - The close price of the ticker symbol in after hours trading.
        should("test afterHours") {
            // uncomment below to test the property
            //modelInstance.afterHours shouldBe ("TODO")
        }

        // to test the property `otc` - Whether or not this aggregate is for an OTC ticker. This field will be left off if false.
        should("test otc") {
            // uncomment below to test the property
            //modelInstance.otc shouldBe ("TODO")
        }

        // to test the property `preMarket` - The open price of the ticker symbol in pre-market trading.
        should("test preMarket") {
            // uncomment below to test the property
            //modelInstance.preMarket shouldBe ("TODO")
        }

    }
}
