/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.StocksSnapshotLastQuote

class StocksSnapshotLastQuoteTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StocksSnapshotLastQuote
        //val modelInstance = StocksSnapshotLastQuote()

        // to test the property `P` - The ask price.
        should("test P") {
            // uncomment below to test the property
            //modelInstance.P shouldBe ("TODO")
        }

        // to test the property `S` - The ask size in lots.
        should("test S") {
            // uncomment below to test the property
            //modelInstance.S shouldBe ("TODO")
        }

        // to test the property `p` - The bid price.
        should("test p") {
            // uncomment below to test the property
            //modelInstance.p shouldBe ("TODO")
        }

        // to test the property `s` - The bid size in lots.
        should("test s") {
            // uncomment below to test the property
            //modelInstance.s shouldBe ("TODO")
        }

        // to test the property `t` - The nanosecond accuracy SIP Unix Timestamp. This is the timestamp of when the SIP received this message from the exchange which produced it.
        should("test t") {
            // uncomment below to test the property
            //modelInstance.t shouldBe ("TODO")
        }

    }
}
