/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.massive.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.massive.client.models.ForexSnapshotLastQuote

class ForexSnapshotLastQuoteTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ForexSnapshotLastQuote
        //val modelInstance = ForexSnapshotLastQuote()

        // to test the property `a` - The ask price.
        should("test a") {
            // uncomment below to test the property
            //modelInstance.a shouldBe ("TODO")
        }

        // to test the property `b` - The bid price.
        should("test b") {
            // uncomment below to test the property
            //modelInstance.b shouldBe ("TODO")
        }

        // to test the property `t` - The millisecond accuracy timestamp of the quote.
        should("test t") {
            // uncomment below to test the property
            //modelInstance.t shouldBe ("TODO")
        }

        // to test the property `x` - The exchange ID on which this quote happened.
        should("test x") {
            // uncomment below to test the property
            //modelInstance.x shouldBe ("TODO")
        }

    }
}
