/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.massive.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.massive.client.models.GetBenzingaV1BullsBearsSay200ResponseResultsInner

class GetBenzingaV1BullsBearsSay200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetBenzingaV1BullsBearsSay200ResponseResultsInner
        //val modelInstance = GetBenzingaV1BullsBearsSay200ResponseResultsInner()

        // to test the property `bearCase` - A concise summary of the bearish investment thesis, highlighting potential risks, challenges, and reasons why the stock could decline in value.
        should("test bearCase") {
            // uncomment below to test the property
            //modelInstance.bearCase shouldBe ("TODO")
        }

        // to test the property `benzingaId` - The unique identifier used by Benzinga for this bull/bear case record.
        should("test benzingaId") {
            // uncomment below to test the property
            //modelInstance.benzingaId shouldBe ("TODO")
        }

        // to test the property `bullCase` - A concise summary of the bullish investment thesis, highlighting positive aspects, growth opportunities, and reasons why the stock could appreciate in value.
        should("test bullCase") {
            // uncomment below to test the property
            //modelInstance.bullCase shouldBe ("TODO")
        }

        // to test the property `lastUpdated` - The timestamp (formatted as an ISO 8601 timestamp) when the bull/bear case was last updated in the system.
        should("test lastUpdated") {
            // uncomment below to test the property
            //modelInstance.lastUpdated shouldBe ("TODO")
        }

        // to test the property `ticker` - The stock ticker symbol for the company associated with the bull and bear case summaries.
        should("test ticker") {
            // uncomment below to test the property
            //modelInstance.ticker shouldBe ("TODO")
        }

    }
}
