/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.massive.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.massive.client.models.GetFuturesV1Schedules200ResponseResultsInner

class GetFuturesV1Schedules200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetFuturesV1Schedules200ResponseResultsInner
        //val modelInstance = GetFuturesV1Schedules200ResponseResultsInner()

        // to test the property `event` - The type of session on the given trading date.
        should("test event") {
            // uncomment below to test the property
            //modelInstance.event shouldBe ("TODO")
        }

        // to test the property `productCode` - The product code of the futures contract.
        should("test productCode") {
            // uncomment below to test the property
            //modelInstance.productCode shouldBe ("TODO")
        }

        // to test the property `productName` - The name of the futures product to which this schedule applies.
        should("test productName") {
            // uncomment below to test the property
            //modelInstance.productName shouldBe ("TODO")
        }

        // to test the property `sessionEndDate` - The session end date for the schedules (also known as the trading date). This field is optional and can be used to filter results by a specific session end date. If left blank, schedules for all dates will be returned. Note that trading sessions end at 5 PM Central Time, so a session ending at 5 PM CT on January 1st would have a session_end_date of 2025-01-01.
        should("test sessionEndDate") {
            // uncomment below to test the property
            //modelInstance.sessionEndDate shouldBe ("TODO")
        }

        // to test the property `timestamp` - The timestamp for the given market event.
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

        // to test the property `tradingVenue` - The trading venue (MIC) for the exchange on which this schedule's product trades.
        should("test tradingVenue") {
            // uncomment below to test the property
            //modelInstance.tradingVenue shouldBe ("TODO")
        }

    }
}
