/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.massive.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.massive.client.models.GetFedV1FundingConditions200ResponseResultsInner

class GetFedV1FundingConditions200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetFedV1FundingConditions200ResponseResultsInner
        //val modelInstance = GetFedV1FundingConditions200ResponseResultsInner()

        // to test the property `date` - Calendar date of the observation (YYYY-MM-DD).
        should("test date") {
            // uncomment below to test the property
            //modelInstance.date shouldBe ("TODO")
        }

        // to test the property `effectiveFedFundsRate` - Federal Funds Effective Rate as a percentage (DFF series from FRED); published daily.
        should("test effectiveFedFundsRate") {
            // uncomment below to test the property
            //modelInstance.effectiveFedFundsRate shouldBe ("TODO")
        }

        // to test the property `effectiveFedFundsVolume` - Total transaction volume underlying the effective federal funds rate calculation, in billions of U.S. dollars; reported on business days.
        should("test effectiveFedFundsVolume") {
            // uncomment below to test the property
            //modelInstance.effectiveFedFundsVolume shouldBe ("TODO")
        }

        // to test the property `fedFundsTargetLower` - Lower bound of the federal funds target range as a percentage (DFEDTARL series from FRED); posted every calendar day.
        should("test fedFundsTargetLower") {
            // uncomment below to test the property
            //modelInstance.fedFundsTargetLower shouldBe ("TODO")
        }

        // to test the property `fedFundsTargetUpper` - Upper bound of the federal funds target range as a percentage (DFEDTARU series from FRED); posted every calendar day.
        should("test fedFundsTargetUpper") {
            // uncomment below to test the property
            //modelInstance.fedFundsTargetUpper shouldBe ("TODO")
        }

        // to test the property `fedOvernightRepoTreasuryAmount` - NY Fed overnight repo operation amount against Treasury collateral, in billions of U.S. dollars (RPONTSYD series from FRED); reported on business days.
        should("test fedOvernightRepoTreasuryAmount") {
            // uncomment below to test the property
            //modelInstance.fedOvernightRepoTreasuryAmount shouldBe ("TODO")
        }

        // to test the property `fedOvernightReverseRepoTreasuryAmount` - NY Fed overnight reverse repo operation amount against Treasury collateral, in billions of U.S. dollars (RRPONTSYD series from FRED); reported on business days.
        should("test fedOvernightReverseRepoTreasuryAmount") {
            // uncomment below to test the property
            //modelInstance.fedOvernightReverseRepoTreasuryAmount shouldBe ("TODO")
        }

        // to test the property `financialCommercialPaper90dRate` - 90-day AA financial commercial paper interest rate as a percentage, quoted on a discount basis (DCPF3M series from FRED); reported on business days, with occasional source-level gaps.
        should("test financialCommercialPaper90dRate") {
            // uncomment below to test the property
            //modelInstance.financialCommercialPaper90dRate shouldBe ("TODO")
        }

        // to test the property `interestOnReserveBalances` - Interest rate paid on reserve balances as a percentage (IORB series from FRED); posted every calendar day.
        should("test interestOnReserveBalances") {
            // uncomment below to test the property
            //modelInstance.interestOnReserveBalances shouldBe ("TODO")
        }

        // to test the property `nonfinancialCommercialPaper90dRate` - 90-day AA nonfinancial commercial paper interest rate as a percentage, quoted on a discount basis (DCPN3M series from FRED); reported on business days, with occasional source-level gaps.
        should("test nonfinancialCommercialPaper90dRate") {
            // uncomment below to test the property
            //modelInstance.nonfinancialCommercialPaper90dRate shouldBe ("TODO")
        }

        // to test the property `obfr25thPercentile` - 25th percentile transaction rate of the OBFR distribution as a percentage; posted on business days.
        should("test obfr25thPercentile") {
            // uncomment below to test the property
            //modelInstance.obfr25thPercentile shouldBe ("TODO")
        }

        // to test the property `obfr75thPercentile` - 75th percentile transaction rate of the OBFR distribution as a percentage; posted on business days.
        should("test obfr75thPercentile") {
            // uncomment below to test the property
            //modelInstance.obfr75thPercentile shouldBe ("TODO")
        }

        // to test the property `obfrVolume` - Total transaction volume underlying the OBFR calculation, in billions of U.S. dollars; reported on business days.
        should("test obfrVolume") {
            // uncomment below to test the property
            //modelInstance.obfrVolume shouldBe ("TODO")
        }

        // to test the property `overnightBankFundingRate` - Overnight Bank Funding Rate (OBFR) as a percentage; published by the Federal Reserve Bank of New York and reported on business days.
        should("test overnightBankFundingRate") {
            // uncomment below to test the property
            //modelInstance.overnightBankFundingRate shouldBe ("TODO")
        }

        // to test the property `securedOvernightFinancingRate` - Secured Overnight Financing Rate (SOFR) as a percentage; published by the Federal Reserve Bank of New York and reported on business days.
        should("test securedOvernightFinancingRate") {
            // uncomment below to test the property
            //modelInstance.securedOvernightFinancingRate shouldBe ("TODO")
        }

        // to test the property `sofr25thPercentile` - 25th percentile transaction rate of the SOFR distribution as a percentage; posted on business days.
        should("test sofr25thPercentile") {
            // uncomment below to test the property
            //modelInstance.sofr25thPercentile shouldBe ("TODO")
        }

        // to test the property `sofr75thPercentile` - 75th percentile transaction rate of the SOFR distribution as a percentage; posted on business days.
        should("test sofr75thPercentile") {
            // uncomment below to test the property
            //modelInstance.sofr75thPercentile shouldBe ("TODO")
        }

        // to test the property `sofrVolume` - Total transaction volume underlying the SOFR calculation, in billions of U.S. dollars; reported on business days.
        should("test sofrVolume") {
            // uncomment below to test the property
            //modelInstance.sofrVolume shouldBe ("TODO")
        }

        // to test the property `tgcr25thPercentile` - 25th percentile transaction rate of the TGCR distribution as a percentage; posted on business days.
        should("test tgcr25thPercentile") {
            // uncomment below to test the property
            //modelInstance.tgcr25thPercentile shouldBe ("TODO")
        }

        // to test the property `tgcr75thPercentile` - 75th percentile transaction rate of the TGCR distribution as a percentage; posted on business days.
        should("test tgcr75thPercentile") {
            // uncomment below to test the property
            //modelInstance.tgcr75thPercentile shouldBe ("TODO")
        }

        // to test the property `triPartyGeneralCollateralRate` - Tri-Party General Collateral Rate (TGCR) as a percentage; published by the Federal Reserve Bank of New York as a repo reference rate and reported on business days.
        should("test triPartyGeneralCollateralRate") {
            // uncomment below to test the property
            //modelInstance.triPartyGeneralCollateralRate shouldBe ("TODO")
        }

        // to test the property `triPartyGeneralCollateralVolume` - Total transaction volume underlying the TGCR calculation, in billions of U.S. dollars; reported on business days.
        should("test triPartyGeneralCollateralVolume") {
            // uncomment below to test the property
            //modelInstance.triPartyGeneralCollateralVolume shouldBe ("TODO")
        }

    }
}
