/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.massive.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.massive.client.models.GetFuturesV1Snapshot200ResponseResultsInner
import com.massive.client.models.GetFuturesV1Snapshot200ResponseResultsInnerDetails
import com.massive.client.models.GetFuturesV1Snapshot200ResponseResultsInnerLastMinute
import com.massive.client.models.GetFuturesV1Snapshot200ResponseResultsInnerLastQuote
import com.massive.client.models.GetFuturesV1Snapshot200ResponseResultsInnerLastTrade
import com.massive.client.models.GetFuturesV1Snapshot200ResponseResultsInnerSession

class GetFuturesV1Snapshot200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetFuturesV1Snapshot200ResponseResultsInner
        //val modelInstance = GetFuturesV1Snapshot200ResponseResultsInner()

        // to test the property `details`
        should("test details") {
            // uncomment below to test the property
            //modelInstance.details shouldBe ("TODO")
        }

        // to test the property `lastMinute`
        should("test lastMinute") {
            // uncomment below to test the property
            //modelInstance.lastMinute shouldBe ("TODO")
        }

        // to test the property `lastQuote`
        should("test lastQuote") {
            // uncomment below to test the property
            //modelInstance.lastQuote shouldBe ("TODO")
        }

        // to test the property `lastTrade`
        should("test lastTrade") {
            // uncomment below to test the property
            //modelInstance.lastTrade shouldBe ("TODO")
        }

        // to test the property `session`
        should("test session") {
            // uncomment below to test the property
            //modelInstance.session shouldBe ("TODO")
        }

    }
}
