/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.massive.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.massive.client.models.GetFuturesV1Snapshot200ResponseResultsInnerLastQuote

class GetFuturesV1Snapshot200ResponseResultsInnerLastQuoteTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetFuturesV1Snapshot200ResponseResultsInnerLastQuote
        //val modelInstance = GetFuturesV1Snapshot200ResponseResultsInnerLastQuote()

        // to test the property `ask` - The lowest price a seller is willing to accept.
        should("test ask") {
            // uncomment below to test the property
            //modelInstance.ask shouldBe ("TODO")
        }

        // to test the property `askSize` - The number of contracts available at the ask price.
        should("test askSize") {
            // uncomment below to test the property
            //modelInstance.askSize shouldBe ("TODO")
        }

        // to test the property `askTimestamp` - The time when the best ask price was last updated.
        should("test askTimestamp") {
            // uncomment below to test the property
            //modelInstance.askTimestamp shouldBe ("TODO")
        }

        // to test the property `bid` - The highest price a buyer is willing to pay.
        should("test bid") {
            // uncomment below to test the property
            //modelInstance.bid shouldBe ("TODO")
        }

        // to test the property `bidSize` - The number of contracts available at the bid price.
        should("test bidSize") {
            // uncomment below to test the property
            //modelInstance.bidSize shouldBe ("TODO")
        }

        // to test the property `bidTimestamp` - The time when the best bid price was last updated.
        should("test bidTimestamp") {
            // uncomment below to test the property
            //modelInstance.bidTimestamp shouldBe ("TODO")
        }

        // to test the property `lastUpdated` - The time when the quote was generated at the exchange to nanosecond precision.
        should("test lastUpdated") {
            // uncomment below to test the property
            //modelInstance.lastUpdated shouldBe ("TODO")
        }

        // to test the property `timeframe` - The timeliness of the data as determined by your subscription. One of REAL-TIME or DELAYED.
        should("test timeframe") {
            // uncomment below to test the property
            //modelInstance.timeframe shouldBe ("TODO")
        }

    }
}
