/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.massive.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.massive.client.models.GetFuturesV1TradesTicker200ResponseResultsInner

class GetFuturesV1TradesTicker200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetFuturesV1TradesTicker200ResponseResultsInner
        //val modelInstance = GetFuturesV1TradesTicker200ResponseResultsInner()

        // to test the property `channel` - The CME multicast channel this event was sourced from.
        should("test channel") {
            // uncomment below to test the property
            //modelInstance.channel shouldBe ("TODO")
        }

        // to test the property `reportSequence` - The reporting sequence number.
        should("test reportSequence") {
            // uncomment below to test the property
            //modelInstance.reportSequence shouldBe ("TODO")
        }

        // to test the property `sequenceNumber` - The unique sequence number assigned to this trade.
        should("test sequenceNumber") {
            // uncomment below to test the property
            //modelInstance.sequenceNumber shouldBe ("TODO")
        }

        // to test the property `ticker` - The futures contract identifier, including the base symbol and contract expiration (e.g., GCJ5 for the April 2025 gold contract).
        should("test ticker") {
            // uncomment below to test the property
            //modelInstance.ticker shouldBe ("TODO")
        }

        // to test the property `timestamp` - The time when the trade was generated at the exchange to nanosecond precision.
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

        // to test the property `price` - The price of the trade. This is the actual dollar value per whole contract of this trade. A trade of 100 contracts with a price of $2.00 would be worth a total dollar value of $200.00.
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

        // to test the property `sessionEndDate` - Also known as the trading date, the date of the end of the trading session, in YYYY-MM-DD format.
        should("test sessionEndDate") {
            // uncomment below to test the property
            //modelInstance.sessionEndDate shouldBe ("TODO")
        }

        // to test the property `propertySize` - The total number of contracts exchanged between buyers and sellers on a given trade.
        should("test propertySize") {
            // uncomment below to test the property
            //modelInstance.propertySize shouldBe ("TODO")
        }

    }
}
