/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.massive.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.massive.client.models.GetFuturesV1Snapshot200ResponseResultsInnerLastTrade

class GetFuturesV1Snapshot200ResponseResultsInnerLastTradeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetFuturesV1Snapshot200ResponseResultsInnerLastTrade
        //val modelInstance = GetFuturesV1Snapshot200ResponseResultsInnerLastTrade()

        // to test the property `lastUpdated` - The time when the trade was generated at the exchange to nanosecond precision.
        should("test lastUpdated") {
            // uncomment below to test the property
            //modelInstance.lastUpdated shouldBe ("TODO")
        }

        // to test the property `price` - The price of the trade. This is the actual dollar value per whole contract of this trade. A trade of 100 contracts with a price of $2.00 would be worth a total dollar value of $200.00.
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

        // to test the property `propertySize` - The total number of contracts exchanged between buyers and sellers on a given trade.
        should("test propertySize") {
            // uncomment below to test the property
            //modelInstance.propertySize shouldBe ("TODO")
        }

        // to test the property `timeframe` - The timeliness of the data as determined by your subscription. One of REAL-TIME or DELAYED.
        should("test timeframe") {
            // uncomment below to test the property
            //modelInstance.timeframe shouldBe ("TODO")
        }

    }
}
