/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.massive.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.massive.client.models.GetStocksFilingsVXForm4200ResponseResultsInner
import com.massive.client.models.GetStocksFilingsVXForm3200ResponseResultsInnerFootnotesInner

class GetStocksFilingsVXForm4200ResponseResultsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetStocksFilingsVXForm4200ResponseResultsInner
        //val modelInstance = GetStocksFilingsVXForm4200ResponseResultsInner()

        // to test the property `accessionNumber` - Unique SEC accession number for the filing (e.g., '0001209191-25-012345').
        should("test accessionNumber") {
            // uncomment below to test the property
            //modelInstance.accessionNumber shouldBe ("TODO")
        }

        // to test the property `aff10b5One` - Whether the transaction was made pursuant to a Rule 10b5-1 trading plan.
        should("test aff10b5One") {
            // uncomment below to test the property
            //modelInstance.aff10b5One shouldBe ("TODO")
        }

        // to test the property `dateOfOriginalSubmission` - Date of the original filing submission for amendment filings (4/A). Null for standard filings (formatted as YYYY-MM-DD).
        should("test dateOfOriginalSubmission") {
            // uncomment below to test the property
            //modelInstance.dateOfOriginalSubmission shouldBe ("TODO")
        }

        // to test the property `deemedExecutionDate` - Deemed execution date if different from transaction date (formatted as YYYY-MM-DD).
        should("test deemedExecutionDate") {
            // uncomment below to test the property
            //modelInstance.deemedExecutionDate shouldBe ("TODO")
        }

        // to test the property `directOrIndirect` - Whether ownership is direct ('D') or indirect ('I').
        should("test directOrIndirect") {
            // uncomment below to test the property
            //modelInstance.directOrIndirect shouldBe ("TODO")
        }

        // to test the property `equitySwapInvolved` - Whether an equity swap was involved in the transaction.
        should("test equitySwapInvolved") {
            // uncomment below to test the property
            //modelInstance.equitySwapInvolved shouldBe ("TODO")
        }

        // to test the property `exerciseDate` - Date exercisable for derivative securities (formatted as YYYY-MM-DD).
        should("test exerciseDate") {
            // uncomment below to test the property
            //modelInstance.exerciseDate shouldBe ("TODO")
        }

        // to test the property `exercisePrice` - Exercise or conversion price of derivative securities in USD.
        should("test exercisePrice") {
            // uncomment below to test the property
            //modelInstance.exercisePrice shouldBe ("TODO")
        }

        // to test the property `expirationDate` - Expiration date for derivative securities (formatted as YYYY-MM-DD).
        should("test expirationDate") {
            // uncomment below to test the property
            //modelInstance.expirationDate shouldBe ("TODO")
        }

        // to test the property `filingDate` - Date when the filing was submitted to the SEC (formatted as YYYY-MM-DD).
        should("test filingDate") {
            // uncomment below to test the property
            //modelInstance.filingDate shouldBe ("TODO")
        }

        // to test the property `filingUrl` - Direct URL to the filing on the SEC EDGAR website.
        should("test filingUrl") {
            // uncomment below to test the property
            //modelInstance.filingUrl shouldBe ("TODO")
        }

        // to test the property `footnotes` - List of footnotes from the filing that are relevant to this row, each with an id and description.
        should("test footnotes") {
            // uncomment below to test the property
            //modelInstance.footnotes shouldBe ("TODO")
        }

        // to test the property `formType` - SEC form type ('4' for standard filing, '4/A' for amendments).
        should("test formType") {
            // uncomment below to test the property
            //modelInstance.formType shouldBe ("TODO")
        }

        // to test the property `isDirector` - Whether the reporting owner is a director of the issuer.
        should("test isDirector") {
            // uncomment below to test the property
            //modelInstance.isDirector shouldBe ("TODO")
        }

        // to test the property `isOfficer` - Whether the reporting owner is an officer of the issuer.
        should("test isOfficer") {
            // uncomment below to test the property
            //modelInstance.isOfficer shouldBe ("TODO")
        }

        // to test the property `isOther` - Whether the reporting owner has another relationship with the issuer.
        should("test isOther") {
            // uncomment below to test the property
            //modelInstance.isOther shouldBe ("TODO")
        }

        // to test the property `isTenPercentOwner` - Whether the reporting owner holds 10% or more of a class of equity securities.
        should("test isTenPercentOwner") {
            // uncomment below to test the property
            //modelInstance.isTenPercentOwner shouldBe ("TODO")
        }

        // to test the property `issuerCik` - SEC Central Index Key of the issuer company (10 digits, zero-padded).
        should("test issuerCik") {
            // uncomment below to test the property
            //modelInstance.issuerCik shouldBe ("TODO")
        }

        // to test the property `issuerName` - Name of the issuer company as reported in the filing.
        should("test issuerName") {
            // uncomment below to test the property
            //modelInstance.issuerName shouldBe ("TODO")
        }

        // to test the property `natureOfOwnership` - Nature of indirect ownership (e.g., 'By Trust', 'By Spouse').
        should("test natureOfOwnership") {
            // uncomment below to test the property
            //modelInstance.natureOfOwnership shouldBe ("TODO")
        }

        // to test the property `notSubjectToSection16` - Whether the reporting owner is not subject to Section 16 of the Securities Exchange Act.
        should("test notSubjectToSection16") {
            // uncomment below to test the property
            //modelInstance.notSubjectToSection16 shouldBe ("TODO")
        }

        // to test the property `officerTitle` - Title of the officer, if the reporting owner is an officer.
        should("test officerTitle") {
            // uncomment below to test the property
            //modelInstance.officerTitle shouldBe ("TODO")
        }

        // to test the property `ownerCik` - SEC Central Index Key of the reporting owner (10 digits, zero-padded).
        should("test ownerCik") {
            // uncomment below to test the property
            //modelInstance.ownerCik shouldBe ("TODO")
        }

        // to test the property `ownerName` - Name of the reporting owner (individual or entity).
        should("test ownerName") {
            // uncomment below to test the property
            //modelInstance.ownerName shouldBe ("TODO")
        }

        // to test the property `periodOfReport` - Date of the event triggering the filing (formatted as YYYY-MM-DD).
        should("test periodOfReport") {
            // uncomment below to test the property
            //modelInstance.periodOfReport shouldBe ("TODO")
        }

        // to test the property `recordType` - Type of record in the filing (e.g., 'transaction', 'holding').
        should("test recordType") {
            // uncomment below to test the property
            //modelInstance.recordType shouldBe ("TODO")
        }

        // to test the property `remarks` - Additional remarks included in the filing.
        should("test remarks") {
            // uncomment below to test the property
            //modelInstance.remarks shouldBe ("TODO")
        }

        // to test the property `securityTitle` - Title or description of the security (e.g., 'Common Stock', 'Stock Option').
        should("test securityTitle") {
            // uncomment below to test the property
            //modelInstance.securityTitle shouldBe ("TODO")
        }

        // to test the property `securityType` - Type of security ('non-derivative' or 'derivative').
        should("test securityType") {
            // uncomment below to test the property
            //modelInstance.securityType shouldBe ("TODO")
        }

        // to test the property `sharesOwnedFollowingTransaction` - Total shares beneficially owned after the transaction.
        should("test sharesOwnedFollowingTransaction") {
            // uncomment below to test the property
            //modelInstance.sharesOwnedFollowingTransaction shouldBe ("TODO")
        }

        // to test the property `tickers` - A list of ticker symbols for the issuer company. Multiple symbols may indicate different share classes.
        should("test tickers") {
            // uncomment below to test the property
            //modelInstance.tickers shouldBe ("TODO")
        }

        // to test the property `transactionAcquiredDisposed` - Whether shares were acquired ('A') or disposed of ('D').
        should("test transactionAcquiredDisposed") {
            // uncomment below to test the property
            //modelInstance.transactionAcquiredDisposed shouldBe ("TODO")
        }

        // to test the property `transactionCode` - SEC transaction code indicating the type of transaction (e.g., 'P' for purchase, 'S' for sale, 'A' for grant/award, 'M' for exercise/conversion).
        should("test transactionCode") {
            // uncomment below to test the property
            //modelInstance.transactionCode shouldBe ("TODO")
        }

        // to test the property `transactionDate` - Date of the transaction (formatted as YYYY-MM-DD).
        should("test transactionDate") {
            // uncomment below to test the property
            //modelInstance.transactionDate shouldBe ("TODO")
        }

        // to test the property `transactionPricePerShare` - Price per share of the transaction in USD.
        should("test transactionPricePerShare") {
            // uncomment below to test the property
            //modelInstance.transactionPricePerShare shouldBe ("TODO")
        }

        // to test the property `transactionShares` - Number of shares involved in the transaction.
        should("test transactionShares") {
            // uncomment below to test the property
            //modelInstance.transactionShares shouldBe ("TODO")
        }

        // to test the property `transactionTimeliness` - Timeliness of the filing: 'O' (on time) or 'L' (late).
        should("test transactionTimeliness") {
            // uncomment below to test the property
            //modelInstance.transactionTimeliness shouldBe ("TODO")
        }

        // to test the property `transactionValue` - Total value of the transaction in USD (transaction_shares x transaction_price_per_share). Null when shares or price is not reported.
        should("test transactionValue") {
            // uncomment below to test the property
            //modelInstance.transactionValue shouldBe ("TODO")
        }

        // to test the property `underlyingSecurityShares` - Number of underlying shares for derivative transactions.
        should("test underlyingSecurityShares") {
            // uncomment below to test the property
            //modelInstance.underlyingSecurityShares shouldBe ("TODO")
        }

        // to test the property `underlyingSecurityTitle` - Title of the underlying security for derivative transactions.
        should("test underlyingSecurityTitle") {
            // uncomment below to test the property
            //modelInstance.underlyingSecurityTitle shouldBe ("TODO")
        }

    }
}
