/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.massive.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.massive.client.models.GetStocksSnapshotDirection200Response
import com.massive.client.models.GetStocksSnapshotTickers200ResponseAllOfTickersInner

class GetStocksSnapshotDirection200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetStocksSnapshotDirection200Response
        //val modelInstance = GetStocksSnapshotDirection200Response()

        // to test the property `status` - The status of this request's response.
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `tickers` - An array of snapshot data for the specified tickers.
        should("test tickers") {
            // uncomment below to test the property
            //modelInstance.tickers shouldBe ("TODO")
        }

    }
}
