/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.massive.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.massive.client.models.ListConditions200ResponseResultsInnerSipMapping

class ListConditions200ResponseResultsInnerSipMappingTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListConditions200ResponseResultsInnerSipMapping
        //val modelInstance = ListConditions200ResponseResultsInnerSipMapping()

        // to test the property `CTA` - Condition code from the Consolidated Tape Association (CTA).
        should("test CTA") {
            // uncomment below to test the property
            //modelInstance.CTA shouldBe ("TODO")
        }

        // to test the property `OPRA` - Condition code from the Options Price Reporting Authority (OPRA).
        should("test OPRA") {
            // uncomment below to test the property
            //modelInstance.OPRA shouldBe ("TODO")
        }

        // to test the property `UTP` - Condition code from UTP Plan (UTP).
        should("test UTP") {
            // uncomment below to test the property
            //modelInstance.UTP shouldBe ("TODO")
        }

    }
}
