/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.massive.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.massive.client.models.ListOptionsContracts200ResponseResultsInnerAdditionalUnderlyingsInner

class ListOptionsContracts200ResponseResultsInnerAdditionalUnderlyingsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListOptionsContracts200ResponseResultsInnerAdditionalUnderlyingsInner
        //val modelInstance = ListOptionsContracts200ResponseResultsInnerAdditionalUnderlyingsInner()

        // to test the property `amount` - The number of shares per contract of the additional underlying, or the cash-in-lieu amount of the currency.
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `type` - The type of the additional underlying asset, either equity or currency.
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `underlying` - The name of the additional underlying asset.
        should("test underlying") {
            // uncomment below to test the property
            //modelInstance.underlying shouldBe ("TODO")
        }

    }
}
