/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.massive.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.massive.client.models.PaginationHooksBase

class PaginationHooksBaseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaginationHooksBase
        //val modelInstance = PaginationHooksBase()

        // to test the property `nextUrl` - If present, this value can be used to fetch the next page of data.
        should("test nextUrl") {
            // uncomment below to test the property
            //modelInstance.nextUrl shouldBe ("TODO")
        }

    }
}
