/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CryptoLastTradeLast

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param symbol The symbol pair that was evaluated from the request.
 * @param last 
 */


data class CryptoLastTrade (

    /* The symbol pair that was evaluated from the request. */
    @Json(name = "symbol")
    val symbol: kotlin.String,

    @Json(name = "last")
    val last: CryptoLastTradeLast? = null

) {


}

