/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id The exchange ID. See <a href=\"https://polygon.io/docs/stocks/get_v3_reference_exchanges\" alt=\"Exchanges\">Exchanges</a> for Polygon.io's mapping of exchange IDs.
 * @param market Market data type this exchange contains ( crypto only currently )
 * @param name Name of the exchange
 * @param type Type of exchange feed
 * @param url URL of this exchange
 */


data class CryptoExchangeInner (

    /* The exchange ID. See <a href=\"https://polygon.io/docs/stocks/get_v3_reference_exchanges\" alt=\"Exchanges\">Exchanges</a> for Polygon.io's mapping of exchange IDs. */
    @Json(name = "id")
    val id: kotlin.Int,

    /* Market data type this exchange contains ( crypto only currently ) */
    @Json(name = "market")
    val market: kotlin.String,

    /* Name of the exchange */
    @Json(name = "name")
    val name: kotlin.String,

    /* Type of exchange feed */
    @Json(name = "type")
    val type: kotlin.String,

    /* URL of this exchange */
    @Json(name = "url")
    val url: kotlin.String

) {


}

