/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param a The ask price.
 * @param b The bid price.
 * @param t The Unix millisecond timestamp for the start of the aggregate window.
 * @param x The exchange ID. See <a href=\"https://polygon.io/docs/forex/get_v3_reference_exchanges\" alt=\"Exchanges\">Exchanges</a> for Polygon.io's mapping of exchange IDs.
 */


data class DeprecatedGetHistoricForexQuotes200ResponseAllOfTicksInner (

    /* The ask price. */
    @Json(name = "a")
    val a: kotlin.Double,

    /* The bid price. */
    @Json(name = "b")
    val b: kotlin.Double,

    /* The Unix millisecond timestamp for the start of the aggregate window. */
    @Json(name = "t")
    val t: kotlin.Int,

    /* The exchange ID. See <a href=\"https://polygon.io/docs/forex/get_v3_reference_exchanges\" alt=\"Exchanges\">Exchanges</a> for Polygon.io's mapping of exchange IDs. */
    @Json(name = "x")
    val x: kotlin.Int

) {


}

