/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DeprecatedGetHistoricForexQuotes200ResponseAllOfTicksInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status The status of this request's response.
 * @param day The date that was evaluated from the request.
 * @param map A map for shortened result keys.
 * @param msLatency The milliseconds of latency for the query results.
 * @param pair The currency pair that was evaluated from the request.
 * @param ticks 
 */


data class DeprecatedGetHistoricForexQuotes200Response (

    /* The status of this request's response. */
    @Json(name = "status")
    val status: kotlin.String,

    /* The date that was evaluated from the request. */
    @Json(name = "day")
    val day: java.time.LocalDate,

    /* A map for shortened result keys. */
    @Json(name = "map")
    val map: kotlin.Any,

    /* The milliseconds of latency for the query results. */
    @Json(name = "msLatency")
    val msLatency: kotlin.Int,

    /* The currency pair that was evaluated from the request. */
    @Json(name = "pair")
    val pair: kotlin.String,

    @Json(name = "ticks")
    val ticks: kotlin.collections.List<DeprecatedGetHistoricForexQuotes200ResponseAllOfTicksInner>

) {


}

