/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param code A unique identifier for the exchange internal to Polygon.io.  This is not an industry code or ISO standard.
 * @param id The ID of the exchange.
 * @param market The market data type that this exchange contains.
 * @param mic The Market Identification Code or MIC as defined in ISO 10383 (<a rel=\"nofollow\" target=\"_blank\" href=\"https://en.wikipedia.org/wiki/Market_Identifier_Code\">https://en.wikipedia.org/wiki/Market_Identifier_Code</a>).
 * @param name The name of the exchange.
 * @param tape The tape id of the exchange.
 * @param type The type of exchange. - TRF = Trade Reporting Facility - exchange = Reporting exchange on the tape 
 */


data class ExchangeInner (

    /* A unique identifier for the exchange internal to Polygon.io.  This is not an industry code or ISO standard. */
    @Json(name = "code")
    val code: kotlin.String? = null,

    /* The ID of the exchange. */
    @Json(name = "id")
    val id: java.math.BigDecimal? = null,

    /* The market data type that this exchange contains. */
    @Json(name = "market")
    val market: kotlin.String? = null,

    /* The Market Identification Code or MIC as defined in ISO 10383 (<a rel=\"nofollow\" target=\"_blank\" href=\"https://en.wikipedia.org/wiki/Market_Identifier_Code\">https://en.wikipedia.org/wiki/Market_Identifier_Code</a>). */
    @Json(name = "mic")
    val mic: kotlin.String? = null,

    /* The name of the exchange. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* The tape id of the exchange. */
    @Json(name = "tape")
    val tape: kotlin.String? = null,

    /* The type of exchange. - TRF = Trade Reporting Facility - exchange = Reporting exchange on the tape  */
    @Json(name = "type")
    val type: kotlin.String? = null

) {


}

