/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param benzingaId A unique identifier assigned by Benzinga to the guidance record.
 * @param companyName The name of the company issuing guidance.
 * @param currency The ISO 4217 code representing the currency in which the company issued its guidance figures.
 * @param date The calendar date (formatted as YYYY-MM-DD) when the guidance was issued.
 * @param epsMethod The methodology of the EPS figure. Possible values are gaap (standardized financials under Generally Accepted Accounting Principles), ffo (Funds From Operations, a non-GAAP metric commonly used to assess the operating performance of REITs), and adj (adjusted, non-GAAP).
 * @param estimatedEpsGuidance The midpoint or central earnings per share (EPS) value the company expects for the given fiscal period.
 * @param estimatedRevenueGuidance The midpoint or central revenue figure the company expects for the given fiscal period.
 * @param fiscalPeriod The fiscal quarter to which the guidance applies, such as Q1, Q2, Q3, or Q4.
 * @param fiscalYear The fiscal year corresponding to the period for which the guidance is issued.
 * @param importance A subjective indicator of the importance of the event, on a scale from 0 (lowest) to 5 (highest).
 * @param lastUpdated The timestamp (formatted as an ISO 8601 timestamp) when the record was last updated in the system.
 * @param maxEpsGuidance The highest EPS value the company expects for the fiscal period if a range was provided.
 * @param maxRevenueGuidance The highest revenue figure the company expects for the fiscal period if a range was provided.
 * @param minEpsGuidance The lowest EPS value the company expects for the fiscal period if a range was provided.
 * @param minRevenueGuidance The lowest revenue figure the company expects for the fiscal period if a range was provided.
 * @param notes Additional descriptive text or commentary provided about the guidance record.
 * @param positioning Indicates how a particular guidance value is presented relative to other figures disclosed by the company. Possible values are 'primary' (the emphasized figure) and 'secondary' (a supporting or alternate figure)
 * @param previousMaxEpsGuidance The highest EPS value issued in a previous guidance record for the same fiscal period.
 * @param previousMaxRevenueGuidance The highest revenue value issued in a previous guidance record for the same fiscal period.
 * @param previousMinEpsGuidance The lowest EPS value issued in a previous guidance record for the same fiscal period.
 * @param previousMinRevenueGuidance The lowest revenue value issued in a previous guidance record for the same fiscal period.
 * @param releaseType Indicates whether the guidance was issued as part of a scheduled earnings release ('official') or as an unscheduled update ('preliminary').
 * @param revenueMethod The methodology of the revenue figure. Possible values are gaap (standardized financials under Generally Accepted Accounting Principles) and adj (adjusted, non-GAAP).
 * @param ticker The stock symbol of the company issuing guidance.
 * @param time The time of day the guidance was announced, in HH:mm:ss format.
 */


data class GetBenzingaV1Guidance200ResponseResultsInner (

    /* A unique identifier assigned by Benzinga to the guidance record. */
    @Json(name = "benzinga_id")
    val benzingaId: kotlin.String? = null,

    /* The name of the company issuing guidance. */
    @Json(name = "company_name")
    val companyName: kotlin.String? = null,

    /* The ISO 4217 code representing the currency in which the company issued its guidance figures. */
    @Json(name = "currency")
    val currency: kotlin.String? = null,

    /* The calendar date (formatted as YYYY-MM-DD) when the guidance was issued. */
    @Json(name = "date")
    val date: kotlin.String? = null,

    /* The methodology of the EPS figure. Possible values are gaap (standardized financials under Generally Accepted Accounting Principles), ffo (Funds From Operations, a non-GAAP metric commonly used to assess the operating performance of REITs), and adj (adjusted, non-GAAP). */
    @Json(name = "eps_method")
    val epsMethod: kotlin.String? = null,

    /* The midpoint or central earnings per share (EPS) value the company expects for the given fiscal period. */
    @Json(name = "estimated_eps_guidance")
    val estimatedEpsGuidance: kotlin.Double? = null,

    /* The midpoint or central revenue figure the company expects for the given fiscal period. */
    @Json(name = "estimated_revenue_guidance")
    val estimatedRevenueGuidance: kotlin.Double? = null,

    /* The fiscal quarter to which the guidance applies, such as Q1, Q2, Q3, or Q4. */
    @Json(name = "fiscal_period")
    val fiscalPeriod: kotlin.String? = null,

    /* The fiscal year corresponding to the period for which the guidance is issued. */
    @Json(name = "fiscal_year")
    val fiscalYear: kotlin.Long? = null,

    /* A subjective indicator of the importance of the event, on a scale from 0 (lowest) to 5 (highest). */
    @Json(name = "importance")
    val importance: kotlin.Long? = null,

    /* The timestamp (formatted as an ISO 8601 timestamp) when the record was last updated in the system. */
    @Json(name = "last_updated")
    val lastUpdated: kotlin.String? = null,

    /* The highest EPS value the company expects for the fiscal period if a range was provided. */
    @Json(name = "max_eps_guidance")
    val maxEpsGuidance: kotlin.Double? = null,

    /* The highest revenue figure the company expects for the fiscal period if a range was provided. */
    @Json(name = "max_revenue_guidance")
    val maxRevenueGuidance: kotlin.Double? = null,

    /* The lowest EPS value the company expects for the fiscal period if a range was provided. */
    @Json(name = "min_eps_guidance")
    val minEpsGuidance: kotlin.Double? = null,

    /* The lowest revenue figure the company expects for the fiscal period if a range was provided. */
    @Json(name = "min_revenue_guidance")
    val minRevenueGuidance: kotlin.Double? = null,

    /* Additional descriptive text or commentary provided about the guidance record. */
    @Json(name = "notes")
    val notes: kotlin.String? = null,

    /* Indicates how a particular guidance value is presented relative to other figures disclosed by the company. Possible values are 'primary' (the emphasized figure) and 'secondary' (a supporting or alternate figure) */
    @Json(name = "positioning")
    val positioning: kotlin.String? = null,

    /* The highest EPS value issued in a previous guidance record for the same fiscal period. */
    @Json(name = "previous_max_eps_guidance")
    val previousMaxEpsGuidance: kotlin.Double? = null,

    /* The highest revenue value issued in a previous guidance record for the same fiscal period. */
    @Json(name = "previous_max_revenue_guidance")
    val previousMaxRevenueGuidance: kotlin.Double? = null,

    /* The lowest EPS value issued in a previous guidance record for the same fiscal period. */
    @Json(name = "previous_min_eps_guidance")
    val previousMinEpsGuidance: kotlin.Double? = null,

    /* The lowest revenue value issued in a previous guidance record for the same fiscal period. */
    @Json(name = "previous_min_revenue_guidance")
    val previousMinRevenueGuidance: kotlin.Double? = null,

    /* Indicates whether the guidance was issued as part of a scheduled earnings release ('official') or as an unscheduled update ('preliminary'). */
    @Json(name = "release_type")
    val releaseType: kotlin.String? = null,

    /* The methodology of the revenue figure. Possible values are gaap (standardized financials under Generally Accepted Accounting Principles) and adj (adjusted, non-GAAP). */
    @Json(name = "revenue_method")
    val revenueMethod: kotlin.String? = null,

    /* The stock symbol of the company issuing guidance. */
    @Json(name = "ticker")
    val ticker: kotlin.String? = null,

    /* The time of day the guidance was announced, in HH:mm:ss format. */
    @Json(name = "time")
    val time: kotlin.String? = null

) {


}

