/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param error A message describing the source of the error.
 * @param requestId A request id assigned by the server.
 * @param status The status of this request's response.
 */


data class GetBenzingaV1AnalystInsights400Response (

    /* A message describing the source of the error. */
    @Json(name = "error")
    val error: kotlin.String,

    /* A request id assigned by the server. */
    @Json(name = "request_id")
    val requestId: kotlin.String,

    /* The status of this request's response. */
    @Json(name = "status")
    val status: GetBenzingaV1AnalystInsights400Response.Status

) {

    /**
     * The status of this request's response.
     *
     * Values: eRROR
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "ERROR") eRROR("ERROR");
    }

}

