/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param bearCase A concise summary of the bearish investment thesis, highlighting potential risks, challenges, and reasons why the stock could decline in value.
 * @param benzingaId The unique identifier used by Benzinga for this bull/bear case record.
 * @param bullCase A concise summary of the bullish investment thesis, highlighting positive aspects, growth opportunities, and reasons why the stock could appreciate in value.
 * @param lastUpdated The timestamp (formatted as an ISO 8601 timestamp) when the bull/bear case was last updated in the system.
 * @param ticker The stock ticker symbol for the company associated with the bull and bear case summaries.
 */


data class GetBenzingaV1BullsBearsSay200ResponseResultsInner (

    /* A concise summary of the bearish investment thesis, highlighting potential risks, challenges, and reasons why the stock could decline in value. */
    @Json(name = "bear_case")
    val bearCase: kotlin.String? = null,

    /* The unique identifier used by Benzinga for this bull/bear case record. */
    @Json(name = "benzinga_id")
    val benzingaId: kotlin.String? = null,

    /* A concise summary of the bullish investment thesis, highlighting positive aspects, growth opportunities, and reasons why the stock could appreciate in value. */
    @Json(name = "bull_case")
    val bullCase: kotlin.String? = null,

    /* The timestamp (formatted as an ISO 8601 timestamp) when the bull/bear case was last updated in the system. */
    @Json(name = "last_updated")
    val lastUpdated: java.time.OffsetDateTime? = null,

    /* The stock ticker symbol for the company associated with the bull and bear case summaries. */
    @Json(name = "ticker")
    val ticker: kotlin.String? = null

) {


}

