/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetCurrencyConversion200ResponseLast

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param converted The result of the conversion.
 * @param from The \"from\" currency symbol.
 * @param initialAmount The amount to convert.
 * @param requestId A request id assigned by the server.
 * @param status The status of this request's response.
 * @param symbol The symbol pair that was evaluated from the request.
 * @param to The \"to\" currency symbol.
 * @param last 
 */


data class GetCurrencyConversion200Response (

    /* The result of the conversion. */
    @Json(name = "converted")
    val converted: kotlin.Double,

    /* The \"from\" currency symbol. */
    @Json(name = "from")
    val from: kotlin.String,

    /* The amount to convert. */
    @Json(name = "initialAmount")
    val initialAmount: kotlin.Double,

    /* A request id assigned by the server. */
    @Json(name = "request_id")
    val requestId: kotlin.String,

    /* The status of this request's response. */
    @Json(name = "status")
    val status: kotlin.String,

    /* The symbol pair that was evaluated from the request. */
    @Json(name = "symbol")
    val symbol: kotlin.String,

    /* The \"to\" currency symbol. */
    @Json(name = "to")
    val to: kotlin.String,

    @Json(name = "last")
    val last: GetCurrencyConversion200ResponseLast? = null

) {


}

