/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetCryptoEMA200ResponseResultsUnderlying
import org.openapitools.client.models.GetCryptoEMA200ResponseResultsValuesInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param underlying 
 * @param propertyValues 
 */


data class GetCryptoSMA200ResponseResults (

    @Json(name = "underlying")
    val underlying: GetCryptoEMA200ResponseResultsUnderlying? = null,

    @Json(name = "values")
    val propertyValues: kotlin.collections.List<GetCryptoEMA200ResponseResultsValuesInner>? = null

) {


}

