/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param histogram The indicator value for this period.
 * @param signal The indicator value for this period.
 * @param timestamp The Unix Msec timestamp from the last aggregate used in this calculation.
 * @param `value` The indicator value for this period.
 */


data class GetCryptoMACD200ResponseResultsValuesInner (

    /* The indicator value for this period. */
    @Json(name = "histogram")
    val histogram: kotlin.Float? = null,

    /* The indicator value for this period. */
    @Json(name = "signal")
    val signal: kotlin.Float? = null,

    /* The Unix Msec timestamp from the last aggregate used in this calculation. */
    @Json(name = "timestamp")
    val timestamp: kotlin.Long? = null,

    /* The indicator value for this period. */
    @Json(name = "value")
    val `value`: kotlin.Float? = null

) {


}

