/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetCryptoSnapshotTickers200ResponseAllOfTickersInnerDay
import org.openapitools.client.models.GetCryptoSnapshotTickers200ResponseAllOfTickersInnerLastTrade
import org.openapitools.client.models.GetCryptoSnapshotTickers200ResponseAllOfTickersInnerMin
import org.openapitools.client.models.GetCryptoSnapshotTickers200ResponseAllOfTickersInnerPrevDay

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Contains the requested snapshot data for the specified ticker.
 *
 * @param day 
 * @param lastTrade 
 * @param min 
 * @param prevDay 
 * @param ticker The exchange symbol that this item is traded under.
 * @param todaysChange The value of the change from the previous day.
 * @param todaysChangePerc The percentage change since the previous day.
 * @param updated The last updated timestamp.
 * @param fmv Fair market value is only available on Business plans. It is our proprietary algorithm to generate a real-time, accurate, fair market value of a tradable security. For more information, <a rel=\"nofollow\" target=\"_blank\" href=\"https://polygon.io/contact\">contact us</a>.
 */


data class GetCryptoSnapshotTicker200ResponseAllOfTicker (

    @Json(name = "day")
    val day: GetCryptoSnapshotTickers200ResponseAllOfTickersInnerDay,

    @Json(name = "lastTrade")
    val lastTrade: GetCryptoSnapshotTickers200ResponseAllOfTickersInnerLastTrade,

    @Json(name = "min")
    val min: GetCryptoSnapshotTickers200ResponseAllOfTickersInnerMin,

    @Json(name = "prevDay")
    val prevDay: GetCryptoSnapshotTickers200ResponseAllOfTickersInnerPrevDay,

    /* The exchange symbol that this item is traded under. */
    @Json(name = "ticker")
    val ticker: kotlin.String,

    /* The value of the change from the previous day. */
    @Json(name = "todaysChange")
    val todaysChange: kotlin.Double,

    /* The percentage change since the previous day. */
    @Json(name = "todaysChangePerc")
    val todaysChangePerc: kotlin.Double,

    /* The last updated timestamp. */
    @Json(name = "updated")
    val updated: kotlin.Int,

    /* Fair market value is only available on Business plans. It is our proprietary algorithm to generate a real-time, accurate, fair market value of a tradable security. For more information, <a rel=\"nofollow\" target=\"_blank\" href=\"https://polygon.io/contact\">contact us</a>. */
    @Json(name = "fmv")
    val fmv: kotlin.Double? = null

) {


}

