/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DeprecatedGetHistoricCryptoTrades200ResponseAllOfTicksInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param close The close price for the symbol in the given time period.
 * @param closingTrades An array of results containing the requested data.
 * @param day The date requested.
 * @param isUTC Whether or not the timestamps are in UTC timezone.
 * @param `open` The open price for the symbol in the given time period.
 * @param openTrades An array of results containing the requested data.
 * @param symbol The symbol pair that was evaluated from the request.
 */


data class GetCryptoOpenClose200Response (

    /* The close price for the symbol in the given time period. */
    @Json(name = "close")
    val close: kotlin.Double,

    /* An array of results containing the requested data. */
    @Json(name = "closingTrades")
    val closingTrades: kotlin.collections.List<DeprecatedGetHistoricCryptoTrades200ResponseAllOfTicksInner>,

    /* The date requested. */
    @Json(name = "day")
    val day: java.time.LocalDate,

    /* Whether or not the timestamps are in UTC timezone. */
    @Json(name = "isUTC")
    val isUTC: kotlin.Boolean,

    /* The open price for the symbol in the given time period. */
    @Json(name = "open")
    val `open`: kotlin.Double,

    /* An array of results containing the requested data. */
    @Json(name = "openTrades")
    val openTrades: kotlin.collections.List<DeprecatedGetHistoricCryptoTrades200ResponseAllOfTicksInner>,

    /* The symbol pair that was evaluated from the request. */
    @Json(name = "symbol")
    val symbol: kotlin.String

) {


}

