/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param compositeTicker The stock ticker symbol used to identify this ETF on exchanges.
 * @param effectiveDate The date showing when the information was accurate or valid; some issuers, such as Vanguard, release their data on a delay, so the effective_date can be several weeks earlier than the processed_date.
 * @param fundFlow The net daily capital flow into or out of the ETF through the creation and redemption process, where positive values indicate inflows and negative values indicate outflows.
 * @param nav The net asset value per share, representing the per-share value of the ETF's underlying holdings.
 * @param processedDate The date showing when ETF Global received and processed the data.
 * @param sharesOutstanding The total number of ETF shares currently issued and outstanding in the market.
 */


data class GetEtfGlobalV1FundFlows200ResponseResultsInner (

    /* The stock ticker symbol used to identify this ETF on exchanges. */
    @Json(name = "composite_ticker")
    val compositeTicker: kotlin.String? = null,

    /* The date showing when the information was accurate or valid; some issuers, such as Vanguard, release their data on a delay, so the effective_date can be several weeks earlier than the processed_date. */
    @Json(name = "effective_date")
    val effectiveDate: java.time.LocalDate? = null,

    /* The net daily capital flow into or out of the ETF through the creation and redemption process, where positive values indicate inflows and negative values indicate outflows. */
    @Json(name = "fund_flow")
    val fundFlow: kotlin.Double? = null,

    /* The net asset value per share, representing the per-share value of the ETF's underlying holdings. */
    @Json(name = "nav")
    val nav: kotlin.Double? = null,

    /* The date showing when ETF Global received and processed the data. */
    @Json(name = "processed_date")
    val processedDate: java.time.LocalDate? = null,

    /* The total number of ETF shares currently issued and outstanding in the market. */
    @Json(name = "shares_outstanding")
    val sharesOutstanding: kotlin.Double? = null

) {


}

