/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetEvents200ResponseResultsEventsInnerOneOfTickerChange

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param date The date the event took place
 * @param eventType The type of historical event for the asset
 * @param tickerChange 
 */


data class GetEvents200ResponseResultsEventsInnerOneOf (

    /* The date the event took place */
    @Json(name = "date")
    val date: java.time.LocalDate,

    /* The type of historical event for the asset */
    @Json(name = "event_type")
    val eventType: kotlin.String,

    @Json(name = "ticker_change")
    val tickerChange: GetEvents200ResponseResultsEventsInnerOneOfTickerChange? = null

) {


}

