/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetEtfGlobalV1Profiles200ResponseResultsInnerCouponExposureInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param leverageStyle Indicates whether the ETF uses leverage to amplify returns ('leveraged'), or does not use leverage ('unleveraged').
 * @param managementClassification Defines whether an ETF is considered active under SEC rules, with managers making investment decisions, or passive, tracking an index.
 * @param productType Indicates whether the product is an Exchange-Traded Note ('etn') or an Exchange-Traded Fund ('etf').
 * @param administrator The administrator of the ETF.
 * @param advisor The investment advisor of the ETF.
 * @param assetClass The primary type of assets held by the ETF, such as equities, bonds, commodities, or other securities.
 * @param aum The total assets under management, representing the current market value of all assets held by the ETF.
 * @param avgDailyTradingVolume The average number of shares traded daily over the past month, indicating liquidity and investor interest.
 * @param bidAskSpread The average intraday bid-ask spread as a percentage, calculated by dividing the spread by the lowest ask price sampled during the day.
 * @param callVolume Call options volume.
 * @param category The broad investment category that describes the ETF's investment focus and strategy.
 * @param compositeTicker The stock ticker symbol used to identify this ETF product on exchanges.
 * @param couponExposure Coupon exposure breakdown for fixed income ETFs.
 * @param creationFee The fee for creating new shares of the ETF.
 * @param creationUnitSize The size of creation units for the ETF.
 * @param currencyExposure Currency exposure breakdown of the ETF.
 * @param custodian The custodian of the ETF assets.
 * @param description The official name and description of the ETF product.
 * @param developmentClass The economic development classification of the markets the ETF invests in, such as developed, emerging, or frontier markets.
 * @param discountPremium Discount or premium to net asset value.
 * @param distributionFrequency How frequently the ETF makes distributions.
 * @param distributor The distributor of the ETF.
 * @param effectiveDate The date showing when the information was accurate or valid; some issuers, such as Vanguard, release their data on a delay, so the effective_date can be several weeks earlier than the processed_date.
 * @param feeWaivers Any fee waivers applied to the ETF.
 * @param fiscalYearEnd The fiscal year end date for the ETF.
 * @param focus The specific investment focus or exposure that the ETF provides, such as sector, geography, or investment style.
 * @param futuresCommissionMerchant The futures commission merchant, if applicable.
 * @param geographicExposure Geographic exposure breakdown of the ETF.
 * @param inceptionDate The date when this ETF was first launched and became available for trading.
 * @param industryExposure Industry exposure breakdown of the ETF.
 * @param industryGroupExposure Industry group exposure breakdown of the ETF.
 * @param issuer The financial institution or fund company that created and sponsors this ETF.
 * @param leadMarketMaker The lead market maker for the ETF.
 * @param leveredAmount The leverage multiplier applied by the ETF, where positive numbers indicate leveraged exposure and negative numbers indicate inverse exposure.
 * @param listingExchange The primary exchange where the ETF is listed.
 * @param managementFee The annual fee charged by the fund manager for managing the ETF's portfolio and operations.
 * @param maturityExposure Maturity exposure breakdown for fixed income ETFs.
 * @param netExpenses Net expenses after waivers.
 * @param numHoldings Number of holdings in the ETF.
 * @param optionsAvailable Availability of options on the ETF.
 * @param optionsVolume Options trading volume for the ETF.
 * @param otherExpenses Other expenses charged by the ETF.
 * @param portfolioManager The portfolio manager of the ETF.
 * @param primaryBenchmark The main index or benchmark that this ETF is designed to track or replicate.
 * @param processedDate The date showing when ETF Global received and processed the data.
 * @param putCallRatio Put/call ratio for options on the ETF.
 * @param putVolume Put options volume.
 * @param region The geographic region or area of the world where the ETF concentrates its investments.
 * @param sectorExposure Sector exposure breakdown of the ETF.
 * @param shortInterest Short interest in the ETF.
 * @param subadvisor The subadvisor of the ETF, if applicable.
 * @param subindustryExposure Sub-industry exposure breakdown of the ETF.
 * @param taxClassification The tax structure of the ETF, determining whether investors receive 1099 or K1 tax forms (RIC, Partnership, or UIT).
 * @param totalExpenses The total annual expense ratio of the ETF, including all fees and costs passed on to investors.
 * @param transferAgent The transfer agent for the ETF.
 * @param trustee The trustee of the ETF.
 */


data class GetEtfGlobalV1Profiles200ResponseResultsInner (

    /* Indicates whether the ETF uses leverage to amplify returns ('leveraged'), or does not use leverage ('unleveraged'). */
    @Json(name = "leverage_style")
    val leverageStyle: kotlin.String,

    /* Defines whether an ETF is considered active under SEC rules, with managers making investment decisions, or passive, tracking an index. */
    @Json(name = "management_classification")
    val managementClassification: kotlin.String,

    /* Indicates whether the product is an Exchange-Traded Note ('etn') or an Exchange-Traded Fund ('etf'). */
    @Json(name = "product_type")
    val productType: kotlin.String,

    /* The administrator of the ETF. */
    @Json(name = "administrator")
    val administrator: kotlin.String? = null,

    /* The investment advisor of the ETF. */
    @Json(name = "advisor")
    val advisor: kotlin.String? = null,

    /* The primary type of assets held by the ETF, such as equities, bonds, commodities, or other securities. */
    @Json(name = "asset_class")
    val assetClass: kotlin.String? = null,

    /* The total assets under management, representing the current market value of all assets held by the ETF. */
    @Json(name = "aum")
    val aum: kotlin.Double? = null,

    /* The average number of shares traded daily over the past month, indicating liquidity and investor interest. */
    @Json(name = "avg_daily_trading_volume")
    val avgDailyTradingVolume: kotlin.Double? = null,

    /* The average intraday bid-ask spread as a percentage, calculated by dividing the spread by the lowest ask price sampled during the day. */
    @Json(name = "bid_ask_spread")
    val bidAskSpread: kotlin.Double? = null,

    /* Call options volume. */
    @Json(name = "call_volume")
    val callVolume: kotlin.Double? = null,

    /* The broad investment category that describes the ETF's investment focus and strategy. */
    @Json(name = "category")
    val category: kotlin.String? = null,

    /* The stock ticker symbol used to identify this ETF product on exchanges. */
    @Json(name = "composite_ticker")
    val compositeTicker: kotlin.String? = null,

    /* Coupon exposure breakdown for fixed income ETFs. */
    @Json(name = "coupon_exposure")
    val couponExposure: kotlin.collections.List<GetEtfGlobalV1Profiles200ResponseResultsInnerCouponExposureInner>? = null,

    /* The fee for creating new shares of the ETF. */
    @Json(name = "creation_fee")
    val creationFee: kotlin.Double? = null,

    /* The size of creation units for the ETF. */
    @Json(name = "creation_unit_size")
    val creationUnitSize: kotlin.Double? = null,

    /* Currency exposure breakdown of the ETF. */
    @Json(name = "currency_exposure")
    val currencyExposure: kotlin.collections.List<GetEtfGlobalV1Profiles200ResponseResultsInnerCouponExposureInner>? = null,

    /* The custodian of the ETF assets. */
    @Json(name = "custodian")
    val custodian: kotlin.String? = null,

    /* The official name and description of the ETF product. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* The economic development classification of the markets the ETF invests in, such as developed, emerging, or frontier markets. */
    @Json(name = "development_class")
    val developmentClass: kotlin.String? = null,

    /* Discount or premium to net asset value. */
    @Json(name = "discount_premium")
    val discountPremium: kotlin.Double? = null,

    /* How frequently the ETF makes distributions. */
    @Json(name = "distribution_frequency")
    val distributionFrequency: kotlin.String? = null,

    /* The distributor of the ETF. */
    @Json(name = "distributor")
    val distributor: kotlin.String? = null,

    /* The date showing when the information was accurate or valid; some issuers, such as Vanguard, release their data on a delay, so the effective_date can be several weeks earlier than the processed_date. */
    @Json(name = "effective_date")
    val effectiveDate: java.time.LocalDate? = null,

    /* Any fee waivers applied to the ETF. */
    @Json(name = "fee_waivers")
    val feeWaivers: kotlin.Double? = null,

    /* The fiscal year end date for the ETF. */
    @Json(name = "fiscal_year_end")
    val fiscalYearEnd: kotlin.String? = null,

    /* The specific investment focus or exposure that the ETF provides, such as sector, geography, or investment style. */
    @Json(name = "focus")
    val focus: kotlin.String? = null,

    /* The futures commission merchant, if applicable. */
    @Json(name = "futures_commission_merchant")
    val futuresCommissionMerchant: kotlin.String? = null,

    /* Geographic exposure breakdown of the ETF. */
    @Json(name = "geographic_exposure")
    val geographicExposure: kotlin.collections.List<GetEtfGlobalV1Profiles200ResponseResultsInnerCouponExposureInner>? = null,

    /* The date when this ETF was first launched and became available for trading. */
    @Json(name = "inception_date")
    val inceptionDate: java.time.LocalDate? = null,

    /* Industry exposure breakdown of the ETF. */
    @Json(name = "industry_exposure")
    val industryExposure: kotlin.collections.List<GetEtfGlobalV1Profiles200ResponseResultsInnerCouponExposureInner>? = null,

    /* Industry group exposure breakdown of the ETF. */
    @Json(name = "industry_group_exposure")
    val industryGroupExposure: kotlin.collections.List<GetEtfGlobalV1Profiles200ResponseResultsInnerCouponExposureInner>? = null,

    /* The financial institution or fund company that created and sponsors this ETF. */
    @Json(name = "issuer")
    val issuer: kotlin.String? = null,

    /* The lead market maker for the ETF. */
    @Json(name = "lead_market_maker")
    val leadMarketMaker: kotlin.String? = null,

    /* The leverage multiplier applied by the ETF, where positive numbers indicate leveraged exposure and negative numbers indicate inverse exposure. */
    @Json(name = "levered_amount")
    val leveredAmount: kotlin.Double? = null,

    /* The primary exchange where the ETF is listed. */
    @Json(name = "listing_exchange")
    val listingExchange: kotlin.String? = null,

    /* The annual fee charged by the fund manager for managing the ETF's portfolio and operations. */
    @Json(name = "management_fee")
    val managementFee: kotlin.Double? = null,

    /* Maturity exposure breakdown for fixed income ETFs. */
    @Json(name = "maturity_exposure")
    val maturityExposure: kotlin.collections.List<GetEtfGlobalV1Profiles200ResponseResultsInnerCouponExposureInner>? = null,

    /* Net expenses after waivers. */
    @Json(name = "net_expenses")
    val netExpenses: kotlin.Double? = null,

    /* Number of holdings in the ETF. */
    @Json(name = "num_holdings")
    val numHoldings: kotlin.Double? = null,

    /* Availability of options on the ETF. */
    @Json(name = "options_available")
    val optionsAvailable: kotlin.Int? = null,

    /* Options trading volume for the ETF. */
    @Json(name = "options_volume")
    val optionsVolume: kotlin.Double? = null,

    /* Other expenses charged by the ETF. */
    @Json(name = "other_expenses")
    val otherExpenses: kotlin.Double? = null,

    /* The portfolio manager of the ETF. */
    @Json(name = "portfolio_manager")
    val portfolioManager: kotlin.String? = null,

    /* The main index or benchmark that this ETF is designed to track or replicate. */
    @Json(name = "primary_benchmark")
    val primaryBenchmark: kotlin.String? = null,

    /* The date showing when ETF Global received and processed the data. */
    @Json(name = "processed_date")
    val processedDate: java.time.LocalDate? = null,

    /* Put/call ratio for options on the ETF. */
    @Json(name = "put_call_ratio")
    val putCallRatio: kotlin.Double? = null,

    /* Put options volume. */
    @Json(name = "put_volume")
    val putVolume: kotlin.Double? = null,

    /* The geographic region or area of the world where the ETF concentrates its investments. */
    @Json(name = "region")
    val region: kotlin.String? = null,

    /* Sector exposure breakdown of the ETF. */
    @Json(name = "sector_exposure")
    val sectorExposure: kotlin.collections.List<GetEtfGlobalV1Profiles200ResponseResultsInnerCouponExposureInner>? = null,

    /* Short interest in the ETF. */
    @Json(name = "short_interest")
    val shortInterest: kotlin.Double? = null,

    /* The subadvisor of the ETF, if applicable. */
    @Json(name = "subadvisor")
    val subadvisor: kotlin.String? = null,

    /* Sub-industry exposure breakdown of the ETF. */
    @Json(name = "subindustry_exposure")
    val subindustryExposure: kotlin.collections.List<GetEtfGlobalV1Profiles200ResponseResultsInnerCouponExposureInner>? = null,

    /* The tax structure of the ETF, determining whether investors receive 1099 or K1 tax forms (RIC, Partnership, or UIT). */
    @Json(name = "tax_classification")
    val taxClassification: kotlin.String? = null,

    /* The total annual expense ratio of the ETF, including all fees and costs passed on to investors. */
    @Json(name = "total_expenses")
    val totalExpenses: kotlin.Double? = null,

    /* The transfer agent for the ETF. */
    @Json(name = "transfer_agent")
    val transferAgent: kotlin.String? = null,

    /* The trustee of the ETF. */
    @Json(name = "trustee")
    val trustee: kotlin.String? = null

) {


}

