/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param leverageStyle Indicates whether the ETF uses leverage to amplify returns ('leveraged'), or does not use leverage ('unleveraged').
 * @param managementClassification Defines whether an ETF is considered active under SEC rules, with managers making investment decisions, or passive, tracking an index.
 * @param productType Indicates whether the product is an Exchange-Traded Note ('etn') or an Exchange-Traded Fund ('etf').
 * @param assetClass The primary type of assets held by the ETF, such as equities, bonds, commodities, or other securities.
 * @param category The broad investment category that describes the ETF's investment focus and strategy.
 * @param compositeTicker The stock ticker symbol used to identify this ETF product on exchanges.
 * @param country The specific country focus of the ETF, if applicable.
 * @param creditQualityRating Credit quality rating for fixed income ETFs.
 * @param description The official name and description of the ETF product.
 * @param developmentClass The economic development classification of the markets the ETF invests in, such as developed, emerging, or frontier markets.
 * @param duration The duration characteristics for fixed income ETFs.
 * @param effectiveDate The date showing when the information was accurate or valid; some issuers, such as Vanguard, release their data on a delay, so the effective_date can be several weeks earlier than the processed_date.
 * @param esg Environmental, Social, and Governance characteristics.
 * @param exposureMechanism The mechanism used to achieve exposure.
 * @param factor Factor exposure characteristics of the ETF.
 * @param focus The specific investment focus or exposure that the ETF provides, such as sector, geography, or investment style.
 * @param hedgeReset The frequency of hedge reset, if applicable.
 * @param holdingsDisclosureFrequency How frequently holdings are disclosed.
 * @param inceptionDate The date when this ETF was first launched and became available for trading.
 * @param isin The International Securities Identification Number, a global standard code for uniquely identifying this ETF worldwide.
 * @param issuer The financial institution or fund company that created and sponsors this ETF.
 * @param leverageReset The frequency of leverage reset, if applicable.
 * @param leveredAmount The leverage multiplier applied by the ETF, where positive numbers indicate leveraged exposure and negative numbers indicate inverse exposure.
 * @param managementStyle Indicates whether an ETF is managed actively or passively, and the level of transparency or replication method used.
 * @param maturity The maturity profile for fixed income ETFs.
 * @param objective The primary investment objective of the ETF.
 * @param primaryBenchmark The main index or benchmark that this ETF is designed to track or replicate.
 * @param processedDate The date showing when ETF Global received and processed the data.
 * @param rebalanceFrequency How frequently the ETF rebalances its holdings.
 * @param reconstitutionFrequency How frequently the index is reconstituted.
 * @param region The geographic region or area of the world where the ETF concentrates its investments.
 * @param secondaryObjective The secondary investment objective, if applicable.
 * @param selectionMethodology The methodology used to select securities.
 * @param selectionUniverse The universe from which securities are selected.
 * @param strategicFocus The strategic investment focus of the ETF.
 * @param targetedFocus The targeted investment focus of the ETF.
 * @param taxClassification The tax structure of the ETF, determining whether investors receive 1099 or K1 tax forms (RIC, Partnership, or UIT).
 * @param usCode A unique identifier code that identifies this ETF in US markets.
 * @param weightingMethodology The methodology used to weight holdings.
 */


data class GetEtfGlobalV1Taxonomies200ResponseResultsInner (

    /* Indicates whether the ETF uses leverage to amplify returns ('leveraged'), or does not use leverage ('unleveraged'). */
    @Json(name = "leverage_style")
    val leverageStyle: kotlin.String,

    /* Defines whether an ETF is considered active under SEC rules, with managers making investment decisions, or passive, tracking an index. */
    @Json(name = "management_classification")
    val managementClassification: kotlin.String,

    /* Indicates whether the product is an Exchange-Traded Note ('etn') or an Exchange-Traded Fund ('etf'). */
    @Json(name = "product_type")
    val productType: kotlin.String,

    /* The primary type of assets held by the ETF, such as equities, bonds, commodities, or other securities. */
    @Json(name = "asset_class")
    val assetClass: kotlin.String? = null,

    /* The broad investment category that describes the ETF's investment focus and strategy. */
    @Json(name = "category")
    val category: kotlin.String? = null,

    /* The stock ticker symbol used to identify this ETF product on exchanges. */
    @Json(name = "composite_ticker")
    val compositeTicker: kotlin.String? = null,

    /* The specific country focus of the ETF, if applicable. */
    @Json(name = "country")
    val country: kotlin.String? = null,

    /* Credit quality rating for fixed income ETFs. */
    @Json(name = "credit_quality_rating")
    val creditQualityRating: kotlin.String? = null,

    /* The official name and description of the ETF product. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* The economic development classification of the markets the ETF invests in, such as developed, emerging, or frontier markets. */
    @Json(name = "development_class")
    val developmentClass: kotlin.String? = null,

    /* The duration characteristics for fixed income ETFs. */
    @Json(name = "duration")
    val duration: kotlin.String? = null,

    /* The date showing when the information was accurate or valid; some issuers, such as Vanguard, release their data on a delay, so the effective_date can be several weeks earlier than the processed_date. */
    @Json(name = "effective_date")
    val effectiveDate: java.time.LocalDate? = null,

    /* Environmental, Social, and Governance characteristics. */
    @Json(name = "esg")
    val esg: kotlin.String? = null,

    /* The mechanism used to achieve exposure. */
    @Json(name = "exposure_mechanism")
    val exposureMechanism: kotlin.String? = null,

    /* Factor exposure characteristics of the ETF. */
    @Json(name = "factor")
    val factor: kotlin.String? = null,

    /* The specific investment focus or exposure that the ETF provides, such as sector, geography, or investment style. */
    @Json(name = "focus")
    val focus: kotlin.String? = null,

    /* The frequency of hedge reset, if applicable. */
    @Json(name = "hedge_reset")
    val hedgeReset: kotlin.String? = null,

    /* How frequently holdings are disclosed. */
    @Json(name = "holdings_disclosure_frequency")
    val holdingsDisclosureFrequency: kotlin.String? = null,

    /* The date when this ETF was first launched and became available for trading. */
    @Json(name = "inception_date")
    val inceptionDate: java.time.LocalDate? = null,

    /* The International Securities Identification Number, a global standard code for uniquely identifying this ETF worldwide. */
    @Json(name = "isin")
    val isin: kotlin.String? = null,

    /* The financial institution or fund company that created and sponsors this ETF. */
    @Json(name = "issuer")
    val issuer: kotlin.String? = null,

    /* The frequency of leverage reset, if applicable. */
    @Json(name = "leverage_reset")
    val leverageReset: kotlin.String? = null,

    /* The leverage multiplier applied by the ETF, where positive numbers indicate leveraged exposure and negative numbers indicate inverse exposure. */
    @Json(name = "levered_amount")
    val leveredAmount: kotlin.Double? = null,

    /* Indicates whether an ETF is managed actively or passively, and the level of transparency or replication method used. */
    @Json(name = "management_style")
    val managementStyle: kotlin.String? = null,

    /* The maturity profile for fixed income ETFs. */
    @Json(name = "maturity")
    val maturity: kotlin.String? = null,

    /* The primary investment objective of the ETF. */
    @Json(name = "objective")
    val objective: kotlin.String? = null,

    /* The main index or benchmark that this ETF is designed to track or replicate. */
    @Json(name = "primary_benchmark")
    val primaryBenchmark: kotlin.String? = null,

    /* The date showing when ETF Global received and processed the data. */
    @Json(name = "processed_date")
    val processedDate: java.time.LocalDate? = null,

    /* How frequently the ETF rebalances its holdings. */
    @Json(name = "rebalance_frequency")
    val rebalanceFrequency: kotlin.String? = null,

    /* How frequently the index is reconstituted. */
    @Json(name = "reconstitution_frequency")
    val reconstitutionFrequency: kotlin.String? = null,

    /* The geographic region or area of the world where the ETF concentrates its investments. */
    @Json(name = "region")
    val region: kotlin.String? = null,

    /* The secondary investment objective, if applicable. */
    @Json(name = "secondary_objective")
    val secondaryObjective: kotlin.String? = null,

    /* The methodology used to select securities. */
    @Json(name = "selection_methodology")
    val selectionMethodology: kotlin.String? = null,

    /* The universe from which securities are selected. */
    @Json(name = "selection_universe")
    val selectionUniverse: kotlin.String? = null,

    /* The strategic investment focus of the ETF. */
    @Json(name = "strategic_focus")
    val strategicFocus: kotlin.String? = null,

    /* The targeted investment focus of the ETF. */
    @Json(name = "targeted_focus")
    val targetedFocus: kotlin.String? = null,

    /* The tax structure of the ETF, determining whether investors receive 1099 or K1 tax forms (RIC, Partnership, or UIT). */
    @Json(name = "tax_classification")
    val taxClassification: kotlin.String? = null,

    /* A unique identifier code that identifies this ETF in US markets. */
    @Json(name = "us_code")
    val usCode: kotlin.String? = null,

    /* The methodology used to weight holdings. */
    @Json(name = "weighting_methodology")
    val weightingMethodology: kotlin.String? = null

) {


}

