/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param participantTimestamp The nanosecond Exchange Unix Timestamp. This is the timestamp of when the quote was generated at the exchange.
 * @param askExchange The ask exchange ID
 * @param askPrice The ask price.
 * @param bidExchange The bid exchange ID
 * @param bidPrice The bid price.
 */


data class GetForexQuotes200ResponseResultsInner (

    /* The nanosecond Exchange Unix Timestamp. This is the timestamp of when the quote was generated at the exchange. */
    @Json(name = "participant_timestamp")
    val participantTimestamp: kotlin.Long,

    /* The ask exchange ID */
    @Json(name = "ask_exchange")
    val askExchange: kotlin.Int? = null,

    /* The ask price. */
    @Json(name = "ask_price")
    val askPrice: kotlin.Double? = null,

    /* The bid exchange ID */
    @Json(name = "bid_exchange")
    val bidExchange: kotlin.Int? = null,

    /* The bid price. */
    @Json(name = "bid_price")
    val bidPrice: kotlin.Double? = null

) {


}

