/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param marketEvent The current status of the market for the product.
 * @param name The name of the futures product.
 * @param productCode The product code of the futures contracts for which you want statuses.
 * @param sessionEndDate The trading date for the current session.
 * @param timestamp The timestamp for the given market event.
 * @param tradingVenue The trading venue (MIC) for the exchange on which the corresponding product trades.
 */


data class GetFuturesVXMarketStatus200ResponseResultsInner (

    /* The current status of the market for the product. */
    @Json(name = "market_event")
    val marketEvent: kotlin.String? = null,

    /* The name of the futures product. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* The product code of the futures contracts for which you want statuses. */
    @Json(name = "product_code")
    val productCode: kotlin.String? = null,

    /* The trading date for the current session. */
    @Json(name = "session_end_date")
    val sessionEndDate: kotlin.String? = null,

    /* The timestamp for the given market event. */
    @Json(name = "timestamp")
    val timestamp: kotlin.String? = null,

    /* The trading venue (MIC) for the exchange on which the corresponding product trades. */
    @Json(name = "trading_venue")
    val tradingVenue: kotlin.String? = null

) {


}

