/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param change The change in price during this session.
 * @param changePercent The percentage change in price during this session.
 * @param close The price at the end of the session.
 * @param high The highest price reached in the session.
 * @param low The lowest price reached in the session.
 * @param `open` The opening price at the start of the session.
 * @param previousSettlement The settlement price of the previous session.
 * @param settlementPrice The final settlement price at the end of the session.
 * @param volume The number of contracts traded in the session.
 */


data class GetFuturesVXSnapshot200ResponseResultsInnerSession (

    /* The change in price during this session. */
    @Json(name = "change")
    val change: kotlin.Double? = null,

    /* The percentage change in price during this session. */
    @Json(name = "change_percent")
    val changePercent: kotlin.Double? = null,

    /* The price at the end of the session. */
    @Json(name = "close")
    val close: kotlin.Double? = null,

    /* The highest price reached in the session. */
    @Json(name = "high")
    val high: kotlin.Double? = null,

    /* The lowest price reached in the session. */
    @Json(name = "low")
    val low: kotlin.Double? = null,

    /* The opening price at the start of the session. */
    @Json(name = "open")
    val `open`: kotlin.Double? = null,

    /* The settlement price of the previous session. */
    @Json(name = "previous_settlement")
    val previousSettlement: kotlin.Double? = null,

    /* The final settlement price at the end of the session. */
    @Json(name = "settlement_price")
    val settlementPrice: kotlin.Double? = null,

    /* The number of contracts traded in the session. */
    @Json(name = "volume")
    val volume: kotlin.Double? = null

) {


}

