/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param sessionEndDate Also known as the trading date, the date of the end of the trading session, in YYYY-MM-DD format.
 * @param ticker The futures contract identifier, including the base symbol and contract expiration (e.g., GCJ5 for the April 2025 gold contract).
 * @param timestamp The time when the quote was generated at the exchange to nanosecond precision.
 * @param askPrice The ask price is expressed per unit of the underlying asset, and you apply the contract multiplier to get the full contract value.
 * @param askSize The quote size represents the number of futures contracts available at the given ask price.
 * @param askTimestamp The time when the ask price was submitted to the exchange.
 * @param bidPrice The bid price is expressed per unit of the underlying asset, and you apply the contract multiplier to get the full contract value.
 * @param bidSize The quote size represents the number of futures contracts available at the given bid price.
 * @param bidTimestamp The time when the bid price was submitted to the exchange.
 */


data class GetFuturesQuotes200ResponseResultsInner (

    /* Also known as the trading date, the date of the end of the trading session, in YYYY-MM-DD format. */
    @Json(name = "session_end_date")
    val sessionEndDate: kotlin.String,

    /* The futures contract identifier, including the base symbol and contract expiration (e.g., GCJ5 for the April 2025 gold contract). */
    @Json(name = "ticker")
    val ticker: kotlin.String,

    /* The time when the quote was generated at the exchange to nanosecond precision. */
    @Json(name = "timestamp")
    val timestamp: kotlin.Int,

    /* The ask price is expressed per unit of the underlying asset, and you apply the contract multiplier to get the full contract value. */
    @Json(name = "ask_price")
    val askPrice: kotlin.Double? = null,

    /* The quote size represents the number of futures contracts available at the given ask price. */
    @Json(name = "ask_size")
    val askSize: kotlin.Double? = null,

    /* The time when the ask price was submitted to the exchange. */
    @Json(name = "ask_timestamp")
    val askTimestamp: kotlin.Int? = null,

    /* The bid price is expressed per unit of the underlying asset, and you apply the contract multiplier to get the full contract value. */
    @Json(name = "bid_price")
    val bidPrice: kotlin.Double? = null,

    /* The quote size represents the number of futures contracts available at the given bid price. */
    @Json(name = "bid_size")
    val bidSize: kotlin.Double? = null,

    /* The time when the bid price was submitted to the exchange. */
    @Json(name = "bid_timestamp")
    val bidTimestamp: kotlin.Int? = null

) {


}

