/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param date Calendar date of the yield observation (YYYY‑MM‑DD).
 * @param yield10Year Market Yield on U.S. Treasury Securities at 10‑Year Constant Maturity, Quoted on an Investment Basis
 * @param yield1Month Market Yield on U.S. Treasury Securities at 1‑Month Constant Maturity, Quoted on an Investment Basis
 * @param yield1Year Market Yield on U.S. Treasury Securities at 1‑Year Constant Maturity, Quoted on an Investment Basis
 * @param yield20Year Market Yield on U.S. Treasury Securities at 20‑Year Constant Maturity, Quoted on an Investment Basis
 * @param yield2Year Market Yield on U.S. Treasury Securities at 2‑Year Constant Maturity, Quoted on an Investment Basis
 * @param yield30Year Market Yield on U.S. Treasury Securities at 30‑Year Constant Maturity, Quoted on an Investment Basis
 * @param yield3Month Market Yield on U.S. Treasury Securities at 3‑Month Constant Maturity, Quoted on an Investment Basis
 * @param yield3Year Market Yield on U.S. Treasury Securities at 3‑Year Constant Maturity, Quoted on an Investment Basis
 * @param yield5Year Market Yield on U.S. Treasury Securities at 5‑Year Constant Maturity, Quoted on an Investment Basis
 * @param yield6Month Market Yield on U.S. Treasury Securities at 6‑Month Constant Maturity, Quoted on an Investment Basis
 * @param yield7Year Market Yield on U.S. Treasury Securities at 7‑Year Constant Maturity, Quoted on an Investment Basis
 */


data class GetFedV1TreasuryYields200ResponseResultsInner (

    /* Calendar date of the yield observation (YYYY‑MM‑DD). */
    @Json(name = "date")
    val date: kotlin.String? = null,

    /* Market Yield on U.S. Treasury Securities at 10‑Year Constant Maturity, Quoted on an Investment Basis */
    @Json(name = "yield_10_year")
    val yield10Year: kotlin.Float? = null,

    /* Market Yield on U.S. Treasury Securities at 1‑Month Constant Maturity, Quoted on an Investment Basis */
    @Json(name = "yield_1_month")
    val yield1Month: kotlin.Float? = null,

    /* Market Yield on U.S. Treasury Securities at 1‑Year Constant Maturity, Quoted on an Investment Basis */
    @Json(name = "yield_1_year")
    val yield1Year: kotlin.Float? = null,

    /* Market Yield on U.S. Treasury Securities at 20‑Year Constant Maturity, Quoted on an Investment Basis */
    @Json(name = "yield_20_year")
    val yield20Year: kotlin.Float? = null,

    /* Market Yield on U.S. Treasury Securities at 2‑Year Constant Maturity, Quoted on an Investment Basis */
    @Json(name = "yield_2_year")
    val yield2Year: kotlin.Float? = null,

    /* Market Yield on U.S. Treasury Securities at 30‑Year Constant Maturity, Quoted on an Investment Basis */
    @Json(name = "yield_30_year")
    val yield30Year: kotlin.Float? = null,

    /* Market Yield on U.S. Treasury Securities at 3‑Month Constant Maturity, Quoted on an Investment Basis */
    @Json(name = "yield_3_month")
    val yield3Month: kotlin.Float? = null,

    /* Market Yield on U.S. Treasury Securities at 3‑Year Constant Maturity, Quoted on an Investment Basis */
    @Json(name = "yield_3_year")
    val yield3Year: kotlin.Float? = null,

    /* Market Yield on U.S. Treasury Securities at 5‑Year Constant Maturity, Quoted on an Investment Basis */
    @Json(name = "yield_5_year")
    val yield5Year: kotlin.Float? = null,

    /* Market Yield on U.S. Treasury Securities at 6‑Month Constant Maturity, Quoted on an Investment Basis */
    @Json(name = "yield_6_month")
    val yield6Month: kotlin.Float? = null,

    /* Market Yield on U.S. Treasury Securities at 7‑Year Constant Maturity, Quoted on an Investment Basis */
    @Json(name = "yield_7_year")
    val yield7Year: kotlin.Float? = null

) {


}

