/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Numeric identifier for the futures exchange or trading venue.
 * @param name Full official name of the futures exchange (e.g., 'Chicago Mercantile Exchange', 'New York Mercantile Exchange').
 * @param type Type of venue - 'exchange' for futures exchanges and derivatives trading platforms.
 * @param acronym Well-known acronym for the exchange (e.g., 'CME', 'NYMEX', 'CBOT', 'COMEX').
 * @param locale Geographic location code where the exchange operates.
 * @param mic Market Identifier Code (MIC) - ISO 10383 standard four-character code for the futures market.
 * @param operatingMic Operating Market Identifier Code for the futures exchange.
 * @param url Official website URL of the futures exchange organization.
 */


data class GetFuturesVXExchanges200ResponseResultsInner (

    /* Numeric identifier for the futures exchange or trading venue. */
    @Json(name = "id")
    val id: kotlin.String,

    /* Full official name of the futures exchange (e.g., 'Chicago Mercantile Exchange', 'New York Mercantile Exchange'). */
    @Json(name = "name")
    val name: kotlin.String,

    /* Type of venue - 'exchange' for futures exchanges and derivatives trading platforms. */
    @Json(name = "type")
    val type: kotlin.String,

    /* Well-known acronym for the exchange (e.g., 'CME', 'NYMEX', 'CBOT', 'COMEX'). */
    @Json(name = "acronym")
    val acronym: kotlin.String? = null,

    /* Geographic location code where the exchange operates. */
    @Json(name = "locale")
    val locale: kotlin.String? = null,

    /* Market Identifier Code (MIC) - ISO 10383 standard four-character code for the futures market. */
    @Json(name = "mic")
    val mic: kotlin.String? = null,

    /* Operating Market Identifier Code for the futures exchange. */
    @Json(name = "operating_mic")
    val operatingMic: kotlin.String? = null,

    /* Official website URL of the futures exchange organization. */
    @Json(name = "url")
    val url: kotlin.String? = null

) {


}

