/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The most recent minute bar for this ticker.
 *
 * @param c The close price for the symbol in the given time period.
 * @param h The highest price for the symbol in the given time period.
 * @param l The lowest price for the symbol in the given time period.
 * @param n The number of transactions in the aggregate window.
 * @param o The open price for the symbol in the given time period.
 * @param t The Unix millisecond timestamp for the start of the aggregate window.
 * @param v The trading volume of the symbol in the given time period.
 */


data class GetForexSnapshotTickers200ResponseAllOfTickersInnerMin (

    /* The close price for the symbol in the given time period. */
    @Json(name = "c")
    val c: kotlin.Double? = null,

    /* The highest price for the symbol in the given time period. */
    @Json(name = "h")
    val h: kotlin.Double? = null,

    /* The lowest price for the symbol in the given time period. */
    @Json(name = "l")
    val l: kotlin.Double? = null,

    /* The number of transactions in the aggregate window. */
    @Json(name = "n")
    val n: kotlin.Int? = null,

    /* The open price for the symbol in the given time period. */
    @Json(name = "o")
    val o: kotlin.Double? = null,

    /* The Unix millisecond timestamp for the start of the aggregate window. */
    @Json(name = "t")
    val t: kotlin.Int? = null,

    /* The trading volume of the symbol in the given time period. */
    @Json(name = "v")
    val v: kotlin.Double? = null

) {


}

