/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param cpi Consumer Price Index (CPI) for All Urban Consumers — a standard measure of headline inflation based on a fixed basket of goods and services, not seasonally adjusted.
 * @param cpiCore Core Consumer Price Index — the CPI excluding food and energy, used to understand underlying inflation trends without short-term volatility.
 * @param cpiYearOverYear Year-over-year percentage change in the headline CPI — the most commonly cited inflation rate in public discourse and economic policy.
 * @param date Calendar date of the observation (YYYY‑MM‑DD).
 * @param pce Personal Consumption Expenditures (PCE) Price Index — a broader measure of inflation used by the Federal Reserve, reflecting actual consumer spending patterns and updated basket weights.
 * @param pceCore Core PCE Price Index — excludes food and energy prices from the PCE index, and is the Fed's preferred measure of underlying inflation.
 * @param pceSpending Nominal Personal Consumption Expenditures — total dollar value of consumer spending in the U.S. economy, reported in billions of dollars and not adjusted for inflation.
 */


data class GetFedV1Inflation200ResponseResultsInner (

    /* Consumer Price Index (CPI) for All Urban Consumers — a standard measure of headline inflation based on a fixed basket of goods and services, not seasonally adjusted. */
    @Json(name = "cpi")
    val cpi: kotlin.Float? = null,

    /* Core Consumer Price Index — the CPI excluding food and energy, used to understand underlying inflation trends without short-term volatility. */
    @Json(name = "cpi_core")
    val cpiCore: kotlin.Float? = null,

    /* Year-over-year percentage change in the headline CPI — the most commonly cited inflation rate in public discourse and economic policy. */
    @Json(name = "cpi_year_over_year")
    val cpiYearOverYear: kotlin.Float? = null,

    /* Calendar date of the observation (YYYY‑MM‑DD). */
    @Json(name = "date")
    val date: kotlin.String? = null,

    /* Personal Consumption Expenditures (PCE) Price Index — a broader measure of inflation used by the Federal Reserve, reflecting actual consumer spending patterns and updated basket weights. */
    @Json(name = "pce")
    val pce: kotlin.Float? = null,

    /* Core PCE Price Index — excludes food and energy prices from the PCE index, and is the Fed's preferred measure of underlying inflation. */
    @Json(name = "pce_core")
    val pceCore: kotlin.Float? = null,

    /* Nominal Personal Consumption Expenditures — total dollar value of consumer spending in the U.S. economy, reported in billions of dollars and not adjusted for inflation. */
    @Json(name = "pce_spending")
    val pceSpending: kotlin.Float? = null

) {


}

