/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param lastUpdated The time when the trade was generated at the exchange to nanosecond precision.
 * @param price The price of the trade. This is the actual dollar value per whole contract of this trade. A trade of 100 contracts with a price of $2.00 would be worth a total dollar value of $200.00.
 * @param propertySize The total number of contracts exchanged between buyers and sellers on a given trade.
 * @param timeframe 
 */


data class GetFuturesVXSnapshot200ResponseResultsInnerLastTrade (

    /* The time when the trade was generated at the exchange to nanosecond precision. */
    @Json(name = "last_updated")
    val lastUpdated: kotlin.Long? = null,

    /* The price of the trade. This is the actual dollar value per whole contract of this trade. A trade of 100 contracts with a price of $2.00 would be worth a total dollar value of $200.00. */
    @Json(name = "price")
    val price: kotlin.Double? = null,

    /* The total number of contracts exchanged between buyers and sellers on a given trade. */
    @Json(name = "size")
    val propertySize: kotlin.Long? = null,

    @Json(name = "timeframe")
    val timeframe: kotlin.String? = null

) {


}

