/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param T The exchange symbol that this item is traded under.
 * @param c The close price for the symbol in the given time period.
 * @param h The highest price for the symbol in the given time period.
 * @param l The lowest price for the symbol in the given time period.
 * @param o The open price for the symbol in the given time period.
 * @param t The Unix millisecond timestamp for the end of the aggregate window.
 * @param v The trading volume of the symbol in the given time period.
 * @param n The number of transactions in the aggregate window.
 * @param vw The volume weighted average price.
 */


data class GetGroupedCryptoAggregates200ResponseAllOfResultsInner (

    /* The exchange symbol that this item is traded under. */
    @Json(name = "T")
    val T: kotlin.String,

    /* The close price for the symbol in the given time period. */
    @Json(name = "c")
    val c: kotlin.Double,

    /* The highest price for the symbol in the given time period. */
    @Json(name = "h")
    val h: kotlin.Double,

    /* The lowest price for the symbol in the given time period. */
    @Json(name = "l")
    val l: kotlin.Double,

    /* The open price for the symbol in the given time period. */
    @Json(name = "o")
    val o: kotlin.Double,

    /* The Unix millisecond timestamp for the end of the aggregate window. */
    @Json(name = "t")
    val t: kotlin.Int,

    /* The trading volume of the symbol in the given time period. */
    @Json(name = "v")
    val v: kotlin.Double,

    /* The number of transactions in the aggregate window. */
    @Json(name = "n")
    val n: kotlin.Int? = null,

    /* The volume weighted average price. */
    @Json(name = "vw")
    val vw: kotlin.Double? = null

) {


}

