/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param sequenceNumber The sequence number represents the sequence in which quote events happened. These are increasing and unique per ticker symbol, but will not always be sequential (e.g., 1, 2, 6, 9, 10, 11).
 * @param sipTimestamp The nanosecond accuracy SIP Unix Timestamp. This is the timestamp of when the SIP received this quote from the exchange which produced it.
 * @param askExchange The ask exchange ID
 * @param askPrice The ask price.
 * @param askSize The ask size. This represents the number of round lot orders at the given ask price. The normal round lot size is 100 shares. An ask size of 2 means there are 200 shares available to purchase at the given ask price.
 * @param bidExchange The bid exchange ID
 * @param bidPrice The bid price.
 * @param bidSize The bid size. This represents the number of round lot orders at the given bid price. The normal round lot size is 100 shares. A bid size of 2 means there are 200 shares for purchase at the given bid price.
 */


data class GetOptionsQuotes200ResponseResultsInner (

    /* The sequence number represents the sequence in which quote events happened. These are increasing and unique per ticker symbol, but will not always be sequential (e.g., 1, 2, 6, 9, 10, 11). */
    @Json(name = "sequence_number")
    val sequenceNumber: kotlin.Long,

    /* The nanosecond accuracy SIP Unix Timestamp. This is the timestamp of when the SIP received this quote from the exchange which produced it. */
    @Json(name = "sip_timestamp")
    val sipTimestamp: kotlin.Long,

    /* The ask exchange ID */
    @Json(name = "ask_exchange")
    val askExchange: kotlin.Int? = null,

    /* The ask price. */
    @Json(name = "ask_price")
    val askPrice: kotlin.Double? = null,

    /* The ask size. This represents the number of round lot orders at the given ask price. The normal round lot size is 100 shares. An ask size of 2 means there are 200 shares available to purchase at the given ask price. */
    @Json(name = "ask_size")
    val askSize: kotlin.Double? = null,

    /* The bid exchange ID */
    @Json(name = "bid_exchange")
    val bidExchange: kotlin.Int? = null,

    /* The bid price. */
    @Json(name = "bid_price")
    val bidPrice: kotlin.Double? = null,

    /* The bid size. This represents the number of round lot orders at the given bid price. The normal round lot size is 100 shares. A bid size of 2 means there are 200 shares for purchase at the given bid price. */
    @Json(name = "bid_size")
    val bidSize: kotlin.Double? = null

) {


}

