/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetOptionsChain200ResponseResultsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param requestId A request id assigned by the server.
 * @param status The status of this request's response.
 * @param nextUrl If present, this value can be used to fetch the next page of data.
 * @param results 
 */


data class GetOptionContract200Response (

    /* A request id assigned by the server. */
    @Json(name = "request_id")
    val requestId: kotlin.String,

    /* The status of this request's response. */
    @Json(name = "status")
    val status: kotlin.String,

    /* If present, this value can be used to fetch the next page of data. */
    @Json(name = "next_url")
    val nextUrl: kotlin.String? = null,

    @Json(name = "results")
    val results: GetOptionsChain200ResponseResultsInner? = null

) {


}

