/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param c The close value for the symbol in the given time period.
 * @param h The highest value for the symbol in the given time period.
 * @param l The lowest value for the symbol in the given time period.
 * @param o The open value for the symbol in the given time period.
 * @param t The Unix millisecond timestamp for the start of the aggregate window.
 */


data class GetPreviousIndicesAggregates200ResponseAllOfResultsInner (

    /* The close value for the symbol in the given time period. */
    @Json(name = "c")
    val c: kotlin.Double,

    /* The highest value for the symbol in the given time period. */
    @Json(name = "h")
    val h: kotlin.Double,

    /* The lowest value for the symbol in the given time period. */
    @Json(name = "l")
    val l: kotlin.Double,

    /* The open value for the symbol in the given time period. */
    @Json(name = "o")
    val o: kotlin.Double,

    /* The Unix millisecond timestamp for the start of the aggregate window. */
    @Json(name = "t")
    val t: kotlin.Int

) {


}

