/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.GetRelatedCompanies200ResponseResultsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param requestId A request id assigned by the server.
 * @param results An array of results containing the requested data.
 * @param status The status of this request's response.
 * @param ticker The ticker being queried.
 */


data class GetRelatedCompanies200Response (

    /* A request id assigned by the server. */
    @Json(name = "request_id")
    val requestId: kotlin.String? = null,

    /* An array of results containing the requested data. */
    @Json(name = "results")
    val results: kotlin.collections.List<GetRelatedCompanies200ResponseResultsInner>? = null,

    /* The status of this request's response. */
    @Json(name = "status")
    val status: kotlin.String? = null,

    /* The ticker being queried. */
    @Json(name = "ticker")
    val ticker: kotlin.String? = null

) {


}

