/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param cik SEC Central Index Key (10 digits, zero-padded).
 * @param filingDate Date when the filing was submitted to the SEC (formatted as YYYY-MM-DD).
 * @param filingUrl SEC URL source for the full filing.
 * @param formType SEC form type (e.g., '10-K' for annual reports, '10-Q' for quarterly reports).
 * @param periodEnd Period end date that the filing relates to (formatted as YYYY-MM-DD).
 * @param section Standardized section identifier from the filing (e.g. 'business', 'risk_factors', etc.).
 * @param text Full raw text content of the section, including headers and formatting.
 * @param ticker Stock ticker symbol for the company.
 */


data class GetStocksFilingsVXText200ResponseResultsInner (

    /* SEC Central Index Key (10 digits, zero-padded). */
    @Json(name = "cik")
    val cik: kotlin.String? = null,

    /* Date when the filing was submitted to the SEC (formatted as YYYY-MM-DD). */
    @Json(name = "filing_date")
    val filingDate: java.time.LocalDate? = null,

    /* SEC URL source for the full filing. */
    @Json(name = "filing_url")
    val filingUrl: kotlin.String? = null,

    /* SEC form type (e.g., '10-K' for annual reports, '10-Q' for quarterly reports). */
    @Json(name = "form_type")
    val formType: kotlin.String? = null,

    /* Period end date that the filing relates to (formatted as YYYY-MM-DD). */
    @Json(name = "period_end")
    val periodEnd: java.time.LocalDate? = null,

    /* Standardized section identifier from the filing (e.g. 'business', 'risk_factors', etc.). */
    @Json(name = "section")
    val section: kotlin.String? = null,

    /* Full raw text content of the section, including headers and formatting. */
    @Json(name = "text")
    val text: kotlin.String? = null,

    /* Stock ticker symbol for the company. */
    @Json(name = "ticker")
    val ticker: kotlin.String? = null

) {


}

