/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The most recent minute aggregate for this stock.
 *
 * @param close The closing value for the minute aggreate.
 * @param high The highest value for the minute aggregate.
 * @param low The lowest value for the minute aggregate.
 * @param `open` The open value for the minute aggregate.
 * @param transactions The number of transactions that took place within the minute aggregate.
 * @param volume The trading volume for the minute aggregate.
 * @param vwap The trading volume weighted average price for the minute aggregate.
 */


data class GetSnapshots200ResponseResultsInnerLastMinute (

    /* The closing value for the minute aggreate. */
    @Json(name = "close")
    val close: kotlin.Double,

    /* The highest value for the minute aggregate. */
    @Json(name = "high")
    val high: kotlin.Double,

    /* The lowest value for the minute aggregate. */
    @Json(name = "low")
    val low: kotlin.Double,

    /* The open value for the minute aggregate. */
    @Json(name = "open")
    val `open`: kotlin.Double,

    /* The number of transactions that took place within the minute aggregate. */
    @Json(name = "transactions")
    val transactions: kotlin.Int,

    /* The trading volume for the minute aggregate. */
    @Json(name = "volume")
    val volume: kotlin.Double,

    /* The trading volume weighted average price for the minute aggregate. */
    @Json(name = "vwap")
    val vwap: kotlin.Double

) {


}

