/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param histogram The difference between the MACD line (value) and the signal line (signal). Positive histogram values indicate upward (bullish) momentum, while negative histogram values indicate downward (bearish) momentum.
 * @param signal The signal line value, calculated as the exponential moving average (EMA) of the MACD line (value) over the signal period defined in the request parameters. Traders typically use crossovers between the MACD and signal lines as trading signals.
 * @param timestamp The Unix Msec timestamp from the last aggregate used in this calculation.
 * @param `value` The MACD line value, calculated as the difference between the short-term and long-term exponential moving averages (EMAs) based on the periods specified in the request parameters.
 */


data class GetStocksMACD200ResponseResultsValuesInner (

    /* The difference between the MACD line (value) and the signal line (signal). Positive histogram values indicate upward (bullish) momentum, while negative histogram values indicate downward (bearish) momentum. */
    @Json(name = "histogram")
    val histogram: kotlin.Float? = null,

    /* The signal line value, calculated as the exponential moving average (EMA) of the MACD line (value) over the signal period defined in the request parameters. Traders typically use crossovers between the MACD and signal lines as trading signals. */
    @Json(name = "signal")
    val signal: kotlin.Float? = null,

    /* The Unix Msec timestamp from the last aggregate used in this calculation. */
    @Json(name = "timestamp")
    val timestamp: kotlin.Long? = null,

    /* The MACD line value, calculated as the difference between the short-term and long-term exponential moving averages (EMAs) based on the periods specified in the request parameters. */
    @Json(name = "value")
    val `value`: kotlin.Float? = null

) {


}

