/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The greeks for this contract. There are certain circumstances where greeks will not be returned, such as options contracts that are deep in the money. See this <a href=\"https://polygon.io/blog/greeks-and-implied-volatility/#testing\" alt=\"link\">article</a> for more information.
 *
 * @param delta The change in the option's price per $0.01 increment in the price of the underlying asset.
 * @param gamma The change in delta per $0.01 change in the price of the underlying asset.
 * @param theta The change in the option's price per day.
 * @param vega The change in the option's price per 1% increment in volatility.
 */


data class GetSnapshots200ResponseResultsInnerGreeks (

    /* The change in the option's price per $0.01 increment in the price of the underlying asset. */
    @Json(name = "delta")
    val delta: kotlin.Double,

    /* The change in delta per $0.01 change in the price of the underlying asset. */
    @Json(name = "gamma")
    val gamma: kotlin.Double,

    /* The change in the option's price per day. */
    @Json(name = "theta")
    val theta: kotlin.Double,

    /* The change in the option's price per 1% increment in volatility. */
    @Json(name = "vega")
    val vega: kotlin.Double

) {


}

