/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The most recent quote for this contract. This is only returned if your current plan includes trades.
 *
 * @param price The price of the trade. This is the actual dollar value per whole share of this trade. A trade of 100 shares with a price of $2.00 would be worth a total dollar value of $200.00.
 * @param propertySize The size of a trade (also known as volume).
 * @param conditions A list of condition codes.
 * @param exchange The exchange ID. See <a href=\"https://polygon.io/docs/stocks/get_v3_reference_exchanges\" alt=\"Exchanges\">Exchanges</a> for Polygon.io's mapping of exchange IDs.
 * @param id The Trade ID which uniquely identifies a trade. These are unique per combination of ticker, exchange, and TRF. For example: A trade for AAPL executed on NYSE and a trade for AAPL executed on NASDAQ could potentially have the same Trade ID.
 * @param lastUpdated The nanosecond timestamp of when this information was updated.
 * @param participantTimestamp The nanosecond Exchange Unix Timestamp. This is the timestamp of when the trade was generated at the exchange.
 * @param sipTimestamp The nanosecond accuracy SIP Unix Timestamp. This is the timestamp of when the SIP received this trade from the exchange which produced it.
 * @param timeframe The time relevance of the data.
 */


data class GetSnapshots200ResponseResultsInnerLastTrade (

    /* The price of the trade. This is the actual dollar value per whole share of this trade. A trade of 100 shares with a price of $2.00 would be worth a total dollar value of $200.00. */
    @Json(name = "price")
    val price: kotlin.Double,

    /* The size of a trade (also known as volume). */
    @Json(name = "size")
    val propertySize: kotlin.Int,

    /* A list of condition codes. */
    @Json(name = "conditions")
    val conditions: kotlin.collections.List<kotlin.Int>? = null,

    /* The exchange ID. See <a href=\"https://polygon.io/docs/stocks/get_v3_reference_exchanges\" alt=\"Exchanges\">Exchanges</a> for Polygon.io's mapping of exchange IDs. */
    @Json(name = "exchange")
    val exchange: kotlin.Int? = null,

    /* The Trade ID which uniquely identifies a trade. These are unique per combination of ticker, exchange, and TRF. For example: A trade for AAPL executed on NYSE and a trade for AAPL executed on NASDAQ could potentially have the same Trade ID. */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* The nanosecond timestamp of when this information was updated. */
    @Json(name = "last_updated")
    val lastUpdated: kotlin.Long? = null,

    /* The nanosecond Exchange Unix Timestamp. This is the timestamp of when the trade was generated at the exchange. */
    @Json(name = "participant_timestamp")
    val participantTimestamp: kotlin.Long? = null,

    /* The nanosecond accuracy SIP Unix Timestamp. This is the timestamp of when the SIP received this trade from the exchange which produced it. */
    @Json(name = "sip_timestamp")
    val sipTimestamp: kotlin.Long? = null,

    /* The time relevance of the data. */
    @Json(name = "timeframe")
    val timeframe: GetSnapshots200ResponseResultsInnerLastTrade.Timeframe? = null

) {

    /**
     * The time relevance of the data.
     *
     * Values: dELAYED,rEALMinusTIME
     */
    @JsonClass(generateAdapter = false)
    enum class Timeframe(val value: kotlin.String) {
        @Json(name = "DELAYED") dELAYED("DELAYED"),
        @Json(name = "REAL-TIME") rEALMinusTIME("REAL-TIME");
    }

}

