/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Information on the underlying stock for this options contract.  The market data returned depends on your current stocks plan.
 *
 * @param changeToBreakEven The change in price for the contract to break even.
 * @param ticker The ticker symbol for the contract's underlying asset.
 * @param lastUpdated The nanosecond timestamp of when this information was updated.
 * @param price The price of the trade. This is the actual dollar value per whole share of this trade. A trade of 100 shares with a price of $2.00 would be worth a total dollar value of $200.00.
 * @param timeframe The time relevance of the data.
 * @param `value` The value of the underlying index.
 */


data class GetSnapshots200ResponseResultsInnerUnderlyingAsset (

    /* The change in price for the contract to break even. */
    @Json(name = "change_to_break_even")
    val changeToBreakEven: kotlin.Double,

    /* The ticker symbol for the contract's underlying asset. */
    @Json(name = "ticker")
    val ticker: kotlin.String,

    /* The nanosecond timestamp of when this information was updated. */
    @Json(name = "last_updated")
    val lastUpdated: kotlin.Long? = null,

    /* The price of the trade. This is the actual dollar value per whole share of this trade. A trade of 100 shares with a price of $2.00 would be worth a total dollar value of $200.00. */
    @Json(name = "price")
    val price: kotlin.Double? = null,

    /* The time relevance of the data. */
    @Json(name = "timeframe")
    val timeframe: GetSnapshots200ResponseResultsInnerUnderlyingAsset.Timeframe? = null,

    /* The value of the underlying index. */
    @Json(name = "value")
    val `value`: kotlin.Double? = null

) {

    /**
     * The time relevance of the data.
     *
     * Values: dELAYED,rEALMinusTIME
     */
    @JsonClass(generateAdapter = false)
    enum class Timeframe(val value: kotlin.String) {
        @Json(name = "DELAYED") dELAYED("DELAYED"),
        @Json(name = "REAL-TIME") rEALMinusTIME("REAL-TIME");
    }

}

