/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ListConditions200ResponseResultsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param count The total number of results for this request.
 * @param requestId A request ID assigned by the server.
 * @param results An array of conditions that match your query.
 * @param status The status of this request's response.
 * @param nextUrl If present, this value can be used to fetch the next page of data.
 */


data class ListConditions400Response (

    /* The total number of results for this request. */
    @Json(name = "count")
    val count: kotlin.Int,

    /* A request ID assigned by the server. */
    @Json(name = "request_id")
    val requestId: kotlin.String,

    /* An array of conditions that match your query. */
    @Json(name = "results")
    val results: kotlin.collections.List<ListConditions200ResponseResultsInner>,

    /* The status of this request's response. */
    @Json(name = "status")
    val status: kotlin.String,

    /* If present, this value can be used to fetch the next page of data. */
    @Json(name = "next_url")
    val nextUrl: kotlin.String? = null

) {


}

