/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Details the source of the news article, including the publisher's name, logo, and homepage URLs. This information helps users identify and access the original source of news content.
 *
 * @param homepageUrl The publisher's homepage URL.
 * @param logoUrl The publisher's logo URL.
 * @param name The publisher's name.
 * @param faviconUrl The publisher's homepage favicon URL.
 */


data class ListNews200ResponseResultsInnerPublisher (

    /* The publisher's homepage URL. */
    @Json(name = "homepage_url")
    val homepageUrl: kotlin.String,

    /* The publisher's logo URL. */
    @Json(name = "logo_url")
    val logoUrl: kotlin.String,

    /* The publisher's name. */
    @Json(name = "name")
    val name: kotlin.String,

    /* The publisher's homepage favicon URL. */
    @Json(name = "favicon_url")
    val faviconUrl: kotlin.String? = null

) {


}

