/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param active Whether or not this contract was tradeable at the given point-in-time specified in the 'as_of' attribute (a contract was active if the given day was after the 'first_trade_date' and before the 'last_trade_date').
 * @param firstTradeDate The date on which this contract first became tradeable.
 * @param lastTradeDate The date on which this contract last became tradeable.
 * @param productCode The unique identifier for the product to which this contract belongs.
 * @param ticker The unique identifier for the contract, typically consisting of the product code and expiration date.
 * @param tradingVenue The trading venue (MIC) for the exchange on which this contract trades.
 * @param type The type of contract, one of \"single\" or \"combo\".
 * @param asOf The point-in-time date for the given contract - e.g. if 'as_of' is set to 2021-04-25, then the data retrieved describes the contract(s) as of 2021-04-25.
 * @param daysToMaturity The number of days until this contract matures (since the point-in-time date). Note that the absence of this field means there are 0 days until maturity.
 * @param maturity This field provides the calendar month reflected in the instrument symbol. For futures spreads and options spreads, this field contains the first leg's calendar month reflected in the instrument symbol. For daily products, this tag contains the full calendar date (YYYYMMDD) as reflected in the instrument symbol.
 * @param maxOrderQuantity The maximum order quantity for this contract.
 * @param minOrderQuantity The minimum order quantity for this contract.
 * @param name The name of the contract.
 * @param settlementDate The final settlement date for the contract.
 * @param settlementTickSize The settlement tick size for this contract.
 * @param spreadTickSize The spread tick size for this contract.
 * @param tradeTickSize The tick size for this contract.
 */


data class ListContracts200ResponseResultsInner (

    /* Whether or not this contract was tradeable at the given point-in-time specified in the 'as_of' attribute (a contract was active if the given day was after the 'first_trade_date' and before the 'last_trade_date'). */
    @Json(name = "active")
    val active: kotlin.Boolean,

    /* The date on which this contract first became tradeable. */
    @Json(name = "first_trade_date")
    val firstTradeDate: java.time.LocalDate,

    /* The date on which this contract last became tradeable. */
    @Json(name = "last_trade_date")
    val lastTradeDate: java.time.LocalDate,

    /* The unique identifier for the product to which this contract belongs. */
    @Json(name = "product_code")
    val productCode: kotlin.String,

    /* The unique identifier for the contract, typically consisting of the product code and expiration date. */
    @Json(name = "ticker")
    val ticker: kotlin.String,

    /* The trading venue (MIC) for the exchange on which this contract trades. */
    @Json(name = "trading_venue")
    val tradingVenue: kotlin.String,

    /* The type of contract, one of \"single\" or \"combo\". */
    @Json(name = "type")
    val type: kotlin.String,

    /* The point-in-time date for the given contract - e.g. if 'as_of' is set to 2021-04-25, then the data retrieved describes the contract(s) as of 2021-04-25. */
    @Json(name = "as_of")
    val asOf: java.time.LocalDate? = null,

    /* The number of days until this contract matures (since the point-in-time date). Note that the absence of this field means there are 0 days until maturity. */
    @Json(name = "days_to_maturity")
    val daysToMaturity: kotlin.Int? = null,

    /* This field provides the calendar month reflected in the instrument symbol. For futures spreads and options spreads, this field contains the first leg's calendar month reflected in the instrument symbol. For daily products, this tag contains the full calendar date (YYYYMMDD) as reflected in the instrument symbol. */
    @Json(name = "maturity")
    val maturity: kotlin.String? = null,

    /* The maximum order quantity for this contract. */
    @Json(name = "max_order_quantity")
    val maxOrderQuantity: kotlin.Int? = null,

    /* The minimum order quantity for this contract. */
    @Json(name = "min_order_quantity")
    val minOrderQuantity: kotlin.Int? = null,

    /* The name of the contract. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* The final settlement date for the contract. */
    @Json(name = "settlement_date")
    val settlementDate: java.time.LocalDate? = null,

    /* The settlement tick size for this contract. */
    @Json(name = "settlement_tick_size")
    val settlementTickSize: java.math.BigDecimal? = null,

    /* The spread tick size for this contract. */
    @Json(name = "spread_tick_size")
    val spreadTickSize: java.math.BigDecimal? = null,

    /* The tick size for this contract. */
    @Json(name = "trade_tick_size")
    val tradeTickSize: java.math.BigDecimal? = null

) {


}

