/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param desc A description of the market.
 * @param market The name of the market.
 */


data class MarketsResultsInner (

    /* A description of the market. */
    @Json(name = "desc")
    val desc: kotlin.String? = null,

    /* The name of the market. */
    @Json(name = "market")
    val market: kotlin.String? = null

) {


}

