/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param nasdaq The status of the Nasdaq market.
 * @param nyse The status of the NYSE market.
 * @param otc The status of the OTC market.
 */


data class MarketStatusExchanges (

    /* The status of the Nasdaq market. */
    @Json(name = "nasdaq")
    val nasdaq: kotlin.String? = null,

    /* The status of the NYSE market. */
    @Json(name = "nyse")
    val nyse: kotlin.String? = null,

    /* The status of the OTC market. */
    @Json(name = "otc")
    val otc: kotlin.String? = null

) {


}

