/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ListProducts200ResponseResultsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param requestId A unique identifier for this request.
 * @param status The status of this request's response.
 * @param results 
 */


data class ProductDetails200Response (

    /* A unique identifier for this request. */
    @Json(name = "request_id")
    val requestId: kotlin.String,

    /* The status of this request's response. */
    @Json(name = "status")
    val status: kotlin.String,

    @Json(name = "results")
    val results: ListProducts200ResponseResultsInner? = null

) {


}

