/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param av The accumulated volume.
 * @param c The close price for the symbol in the given time period.
 * @param h The highest price for the symbol in the given time period.
 * @param l The lowest price for the symbol in the given time period.
 * @param n The number of transactions in the aggregate window.
 * @param o The open price for the symbol in the given time period.
 * @param t The Unix millisecond timestamp for the start of the aggregate window.
 * @param v The trading volume of the symbol in the given time period.
 * @param vw The volume weighted average price.
 * @param otc Whether or not this aggregate is for an OTC ticker. This field will be left off if false.
 */


data class StocksSnapshotMinuteOTC (

    /* The accumulated volume. */
    @Json(name = "av")
    val av: kotlin.Int,

    /* The close price for the symbol in the given time period. */
    @Json(name = "c")
    val c: kotlin.Double,

    /* The highest price for the symbol in the given time period. */
    @Json(name = "h")
    val h: kotlin.Double,

    /* The lowest price for the symbol in the given time period. */
    @Json(name = "l")
    val l: kotlin.Double,

    /* The number of transactions in the aggregate window. */
    @Json(name = "n")
    val n: kotlin.Int,

    /* The open price for the symbol in the given time period. */
    @Json(name = "o")
    val o: kotlin.Double,

    /* The Unix millisecond timestamp for the start of the aggregate window. */
    @Json(name = "t")
    val t: kotlin.Int,

    /* The trading volume of the symbol in the given time period. */
    @Json(name = "v")
    val v: kotlin.Double,

    /* The volume weighted average price. */
    @Json(name = "vw")
    val vw: kotlin.Double,

    /* Whether or not this aggregate is for an OTC ticker. This field will be left off if false. */
    @Json(name = "otc")
    val otc: kotlin.Boolean? = null

) {


}

