/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DeprecatedGetHistoricStocksQuotes200ResponseAllOfResultsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param results 
 */


data class StocksV2NBBOs (

    @Json(name = "results")
    val results: kotlin.collections.List<DeprecatedGetHistoricStocksQuotes200ResponseAllOfResultsInner>? = null

) {


}

