/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param requestId A request id assigned by the server.
 * @param status The status of this request's response.
 */


data class V2LastBase (

    /* A request id assigned by the server. */
    @Json(name = "request_id")
    val requestId: kotlin.String,

    /* The status of this request's response. */
    @Json(name = "status")
    val status: kotlin.String

) {


}

