/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.massive.client.models

import com.massive.client.models.GetGroupedCryptoAggregates200ResponseAllOfResultsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param results An array of results containing the requested data.
 */


data class ForexPreviousClose (

    /* An array of results containing the requested data. */
    @Json(name = "results")
    val results: kotlin.collections.List<GetGroupedCryptoAggregates200ResponseAllOfResultsInner>? = null

) {


}

