/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.massive.client.models

import com.massive.client.models.GetEvents200ResponseResultsEventsInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Contains the requested event data for the specified ticker.
 *
 * @param events An array of event containing the requested data.
 * @param name The name of the asset.
 */


data class GetEvents200ResponseResults (

    /* An array of event containing the requested data. */
    @Json(name = "events")
    val events: kotlin.collections.List<GetEvents200ResponseResultsEventsInner>? = null,

    /* The name of the asset. */
    @Json(name = "name")
    val name: kotlin.String? = null

) {


}

