/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.massive.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param date Calendar date of the observation (YYYY-MM-DD).
 * @param effectiveFedFundsRate Federal Funds Effective Rate as a percentage (DFF series from FRED); published daily.
 * @param effectiveFedFundsVolume Total transaction volume underlying the effective federal funds rate calculation, in billions of U.S. dollars; reported on business days.
 * @param fedFundsTargetLower Lower bound of the federal funds target range as a percentage (DFEDTARL series from FRED); posted every calendar day.
 * @param fedFundsTargetUpper Upper bound of the federal funds target range as a percentage (DFEDTARU series from FRED); posted every calendar day.
 * @param fedOvernightRepoTreasuryAmount NY Fed overnight repo operation amount against Treasury collateral, in billions of U.S. dollars (RPONTSYD series from FRED); reported on business days.
 * @param fedOvernightReverseRepoTreasuryAmount NY Fed overnight reverse repo operation amount against Treasury collateral, in billions of U.S. dollars (RRPONTSYD series from FRED); reported on business days.
 * @param financialCommercialPaper90dRate 90-day AA financial commercial paper interest rate as a percentage, quoted on a discount basis (DCPF3M series from FRED); reported on business days, with occasional source-level gaps.
 * @param interestOnReserveBalances Interest rate paid on reserve balances as a percentage (IORB series from FRED); posted every calendar day.
 * @param nonfinancialCommercialPaper90dRate 90-day AA nonfinancial commercial paper interest rate as a percentage, quoted on a discount basis (DCPN3M series from FRED); reported on business days, with occasional source-level gaps.
 * @param obfr25thPercentile 25th percentile transaction rate of the OBFR distribution as a percentage; posted on business days.
 * @param obfr75thPercentile 75th percentile transaction rate of the OBFR distribution as a percentage; posted on business days.
 * @param obfrVolume Total transaction volume underlying the OBFR calculation, in billions of U.S. dollars; reported on business days.
 * @param overnightBankFundingRate Overnight Bank Funding Rate (OBFR) as a percentage; published by the Federal Reserve Bank of New York and reported on business days.
 * @param securedOvernightFinancingRate Secured Overnight Financing Rate (SOFR) as a percentage; published by the Federal Reserve Bank of New York and reported on business days.
 * @param sofr25thPercentile 25th percentile transaction rate of the SOFR distribution as a percentage; posted on business days.
 * @param sofr75thPercentile 75th percentile transaction rate of the SOFR distribution as a percentage; posted on business days.
 * @param sofrVolume Total transaction volume underlying the SOFR calculation, in billions of U.S. dollars; reported on business days.
 * @param tgcr25thPercentile 25th percentile transaction rate of the TGCR distribution as a percentage; posted on business days.
 * @param tgcr75thPercentile 75th percentile transaction rate of the TGCR distribution as a percentage; posted on business days.
 * @param triPartyGeneralCollateralRate Tri-Party General Collateral Rate (TGCR) as a percentage; published by the Federal Reserve Bank of New York as a repo reference rate and reported on business days.
 * @param triPartyGeneralCollateralVolume Total transaction volume underlying the TGCR calculation, in billions of U.S. dollars; reported on business days.
 */


data class GetFedV1FundingConditions200ResponseResultsInner (

    /* Calendar date of the observation (YYYY-MM-DD). */
    @Json(name = "date")
    val date: java.time.LocalDate? = null,

    /* Federal Funds Effective Rate as a percentage (DFF series from FRED); published daily. */
    @Json(name = "effective_fed_funds_rate")
    val effectiveFedFundsRate: kotlin.Float? = null,

    /* Total transaction volume underlying the effective federal funds rate calculation, in billions of U.S. dollars; reported on business days. */
    @Json(name = "effective_fed_funds_volume")
    val effectiveFedFundsVolume: kotlin.Float? = null,

    /* Lower bound of the federal funds target range as a percentage (DFEDTARL series from FRED); posted every calendar day. */
    @Json(name = "fed_funds_target_lower")
    val fedFundsTargetLower: kotlin.Float? = null,

    /* Upper bound of the federal funds target range as a percentage (DFEDTARU series from FRED); posted every calendar day. */
    @Json(name = "fed_funds_target_upper")
    val fedFundsTargetUpper: kotlin.Float? = null,

    /* NY Fed overnight repo operation amount against Treasury collateral, in billions of U.S. dollars (RPONTSYD series from FRED); reported on business days. */
    @Json(name = "fed_overnight_repo_treasury_amount")
    val fedOvernightRepoTreasuryAmount: kotlin.Float? = null,

    /* NY Fed overnight reverse repo operation amount against Treasury collateral, in billions of U.S. dollars (RRPONTSYD series from FRED); reported on business days. */
    @Json(name = "fed_overnight_reverse_repo_treasury_amount")
    val fedOvernightReverseRepoTreasuryAmount: kotlin.Float? = null,

    /* 90-day AA financial commercial paper interest rate as a percentage, quoted on a discount basis (DCPF3M series from FRED); reported on business days, with occasional source-level gaps. */
    @Json(name = "financial_commercial_paper_90d_rate")
    val financialCommercialPaper90dRate: kotlin.Float? = null,

    /* Interest rate paid on reserve balances as a percentage (IORB series from FRED); posted every calendar day. */
    @Json(name = "interest_on_reserve_balances")
    val interestOnReserveBalances: kotlin.Float? = null,

    /* 90-day AA nonfinancial commercial paper interest rate as a percentage, quoted on a discount basis (DCPN3M series from FRED); reported on business days, with occasional source-level gaps. */
    @Json(name = "nonfinancial_commercial_paper_90d_rate")
    val nonfinancialCommercialPaper90dRate: kotlin.Float? = null,

    /* 25th percentile transaction rate of the OBFR distribution as a percentage; posted on business days. */
    @Json(name = "obfr_25th_percentile")
    val obfr25thPercentile: kotlin.Float? = null,

    /* 75th percentile transaction rate of the OBFR distribution as a percentage; posted on business days. */
    @Json(name = "obfr_75th_percentile")
    val obfr75thPercentile: kotlin.Float? = null,

    /* Total transaction volume underlying the OBFR calculation, in billions of U.S. dollars; reported on business days. */
    @Json(name = "obfr_volume")
    val obfrVolume: kotlin.Float? = null,

    /* Overnight Bank Funding Rate (OBFR) as a percentage; published by the Federal Reserve Bank of New York and reported on business days. */
    @Json(name = "overnight_bank_funding_rate")
    val overnightBankFundingRate: kotlin.Float? = null,

    /* Secured Overnight Financing Rate (SOFR) as a percentage; published by the Federal Reserve Bank of New York and reported on business days. */
    @Json(name = "secured_overnight_financing_rate")
    val securedOvernightFinancingRate: kotlin.Float? = null,

    /* 25th percentile transaction rate of the SOFR distribution as a percentage; posted on business days. */
    @Json(name = "sofr_25th_percentile")
    val sofr25thPercentile: kotlin.Float? = null,

    /* 75th percentile transaction rate of the SOFR distribution as a percentage; posted on business days. */
    @Json(name = "sofr_75th_percentile")
    val sofr75thPercentile: kotlin.Float? = null,

    /* Total transaction volume underlying the SOFR calculation, in billions of U.S. dollars; reported on business days. */
    @Json(name = "sofr_volume")
    val sofrVolume: kotlin.Float? = null,

    /* 25th percentile transaction rate of the TGCR distribution as a percentage; posted on business days. */
    @Json(name = "tgcr_25th_percentile")
    val tgcr25thPercentile: kotlin.Float? = null,

    /* 75th percentile transaction rate of the TGCR distribution as a percentage; posted on business days. */
    @Json(name = "tgcr_75th_percentile")
    val tgcr75thPercentile: kotlin.Float? = null,

    /* Tri-Party General Collateral Rate (TGCR) as a percentage; published by the Federal Reserve Bank of New York as a repo reference rate and reported on business days. */
    @Json(name = "tri_party_general_collateral_rate")
    val triPartyGeneralCollateralRate: kotlin.Float? = null,

    /* Total transaction volume underlying the TGCR calculation, in billions of U.S. dollars; reported on business days. */
    @Json(name = "tri_party_general_collateral_volume")
    val triPartyGeneralCollateralVolume: kotlin.Float? = null

) {


}

