/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.massive.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param active Whether or not a given contract was tradeable at the given point in time. Active is true when (first_trade_date <= date >= last_trade_date) and false otherwise.
 * @param date A date string in the format YYYY-MM-DD. This parameter will return point-in-time information about contracts for the specified day.
 * @param daysToMaturity The number of calendar days between the 'date' and the contract's final settlement date.
 * @param firstTradeDate The first day on which the contract was tradeable.
 * @param groupCode An identifier used to identify logical groups of products. The group_code is only populated for contracts listed for trading on CME Globex.
 * @param lastTradeDate The last day on which the contract was tradeable.
 * @param maxOrderQuantity The maximum order quantity.
 * @param minOrderQuantity The minimum order quantity.
 * @param name The name of this contract.
 * @param productCode The identifier for the contract's product.
 * @param settlementDate The date on which this contract settles.
 * @param settlementTickSize The tick size for settlement.
 * @param spreadTickSize The tick size for spreads.
 * @param ticker The ticker for the contract.
 * @param tradeTickSize The tick size for trades.
 * @param tradingVenue The trading venue (MIC) for the exchange on which this contract trades.
 * @param type The type of contract, one of 'single' or 'combo'. Leaving this filter blank will query for contracts where type is 'single', 'combo' or empty. This field only exists on contracts as of 2025-03-12 and later. It will be null when date < 2025-03-12.
 */


data class GetFuturesV1Contracts200ResponseResultsInner (

    /* Whether or not a given contract was tradeable at the given point in time. Active is true when (first_trade_date <= date >= last_trade_date) and false otherwise. */
    @Json(name = "active")
    val active: kotlin.Boolean,

    /* A date string in the format YYYY-MM-DD. This parameter will return point-in-time information about contracts for the specified day. */
    @Json(name = "date")
    val date: java.time.LocalDate,

    /* The number of calendar days between the 'date' and the contract's final settlement date. */
    @Json(name = "days_to_maturity")
    val daysToMaturity: kotlin.Long? = null,

    /* The first day on which the contract was tradeable. */
    @Json(name = "first_trade_date")
    val firstTradeDate: java.time.LocalDate? = null,

    /* An identifier used to identify logical groups of products. The group_code is only populated for contracts listed for trading on CME Globex. */
    @Json(name = "group_code")
    val groupCode: kotlin.String? = null,

    /* The last day on which the contract was tradeable. */
    @Json(name = "last_trade_date")
    val lastTradeDate: java.time.LocalDate? = null,

    /* The maximum order quantity. */
    @Json(name = "max_order_quantity")
    val maxOrderQuantity: kotlin.Long? = null,

    /* The minimum order quantity. */
    @Json(name = "min_order_quantity")
    val minOrderQuantity: kotlin.Long? = null,

    /* The name of this contract. */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* The identifier for the contract's product. */
    @Json(name = "product_code")
    val productCode: kotlin.String? = null,

    /* The date on which this contract settles. */
    @Json(name = "settlement_date")
    val settlementDate: java.time.LocalDate? = null,

    /* The tick size for settlement. */
    @Json(name = "settlement_tick_size")
    val settlementTickSize: kotlin.Double? = null,

    /* The tick size for spreads. */
    @Json(name = "spread_tick_size")
    val spreadTickSize: kotlin.Double? = null,

    /* The ticker for the contract. */
    @Json(name = "ticker")
    val ticker: kotlin.String? = null,

    /* The tick size for trades. */
    @Json(name = "trade_tick_size")
    val tradeTickSize: kotlin.Double? = null,

    /* The trading venue (MIC) for the exchange on which this contract trades. */
    @Json(name = "trading_venue")
    val tradingVenue: kotlin.String? = null,

    /* The type of contract, one of 'single' or 'combo'. Leaving this filter blank will query for contracts where type is 'single', 'combo' or empty. This field only exists on contracts as of 2025-03-12 and later. It will be null when date < 2025-03-12. */
    @Json(name = "type")
    val type: kotlin.String? = null

) {


}

