/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.massive.client.models

import com.massive.client.models.GetMarketStatus200ResponseCurrencies
import com.massive.client.models.GetMarketStatus200ResponseExchanges
import com.massive.client.models.GetMarketStatus200ResponseIndicesGroups

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param afterHours Whether or not the market is in post-market hours.
 * @param currencies 
 * @param earlyHours Whether or not the market is in pre-market hours.
 * @param exchanges 
 * @param indicesGroups 
 * @param market The status of the market as a whole.
 * @param serverTime The current time of the server, returned as a date-time in RFC3339 format.
 */


data class GetMarketStatus200Response (

    /* Whether or not the market is in post-market hours. */
    @Json(name = "afterHours")
    val afterHours: kotlin.Boolean? = null,

    @Json(name = "currencies")
    val currencies: GetMarketStatus200ResponseCurrencies? = null,

    /* Whether or not the market is in pre-market hours. */
    @Json(name = "earlyHours")
    val earlyHours: kotlin.Boolean? = null,

    @Json(name = "exchanges")
    val exchanges: GetMarketStatus200ResponseExchanges? = null,

    @Json(name = "indicesGroups")
    val indicesGroups: GetMarketStatus200ResponseIndicesGroups? = null,

    /* The status of the market as a whole. */
    @Json(name = "market")
    val market: kotlin.String? = null,

    /* The current time of the server, returned as a date-time in RFC3339 format. */
    @Json(name = "serverTime")
    val serverTime: kotlin.String? = null

) {


}

