/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.massive.client.models

import com.massive.client.models.GetStocksSnapshotTickers200ResponseAllOfTickersInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status The status of this request's response.
 * @param tickers An array of snapshot data for the specified tickers.
 */


data class GetStocksSnapshotDirection200Response (

    /* The status of this request's response. */
    @Json(name = "status")
    val status: kotlin.String,

    /* An array of snapshot data for the specified tickers. */
    @Json(name = "tickers")
    val tickers: kotlin.collections.List<GetStocksSnapshotTickers200ResponseAllOfTickersInner>? = null

) {


}

