/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.massive.client.models

import com.massive.client.models.GetStocksSnapshotTickers200ResponseAllOfTickersInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status The status of this request's response.
 * @param requestId A request id assigned by the server.
 * @param ticker 
 */


data class GetStocksSnapshotTicker200Response (

    /* The status of this request's response. */
    @Json(name = "status")
    val status: kotlin.String,

    /* A request id assigned by the server. */
    @Json(name = "request_id")
    val requestId: kotlin.String,

    @Json(name = "ticker")
    val ticker: GetStocksSnapshotTickers200ResponseAllOfTickersInner? = null

) {


}

