/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.massive.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param effectiveDate The effective date of the free float measurement.
 * @param freeFloat Number of shares freely tradable in the market. Free float shares represent the portion of a company's outstanding shares that is freely tradable in the market, excluding any holdings considered strategic, controlling, or long term. This excludes insiders, directors, founders, 5 percent plus shareholders, cross holdings, government stakes except pensions, restricted or locked up shares, employee plans, and any entities with board influence, leaving only shares that are genuinely available for public trading.
 * @param freeFloatPercent Percentage of total shares outstanding that are available for public trading, rounded to two decimal places.
 * @param ticker The primary ticker symbol for the stock.
 */


data class GetStocksVXFloat200ResponseResultsInner (

    /* The effective date of the free float measurement. */
    @Json(name = "effective_date")
    val effectiveDate: java.time.LocalDate? = null,

    /* Number of shares freely tradable in the market. Free float shares represent the portion of a company's outstanding shares that is freely tradable in the market, excluding any holdings considered strategic, controlling, or long term. This excludes insiders, directors, founders, 5 percent plus shareholders, cross holdings, government stakes except pensions, restricted or locked up shares, employee plans, and any entities with board influence, leaving only shares that are genuinely available for public trading. */
    @Json(name = "free_float")
    val freeFloat: kotlin.Long? = null,

    /* Percentage of total shares outstanding that are available for public trading, rounded to two decimal places. */
    @Json(name = "free_float_percent")
    val freeFloatPercent: kotlin.Double? = null,

    /* The primary ticker symbol for the stock. */
    @Json(name = "ticker")
    val ticker: kotlin.String? = null

) {


}

