/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.massive.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accessionNumber SEC accession number uniquely identifying the filing (e.g., '0000320193-24-000123').
 * @param cik SEC Central Index Key (CIK) identifying the filing entity.
 * @param filingDate Date when the filing was submitted to the SEC (formatted as YYYY-MM-DD).
 * @param filingUrl Direct URL to the filing on the SEC EDGAR website.
 * @param formType SEC form type (e.g., '10-K', '10-Q', '8-K', 'S-1', '4', etc.).
 * @param issuerName Name of the company or entity that submitted the filing.
 * @param ticker Stock ticker symbol for the filing entity, if available.
 */


data class GetStocksFilingsVXIndex200ResponseResultsInner (

    /* SEC accession number uniquely identifying the filing (e.g., '0000320193-24-000123'). */
    @Json(name = "accession_number")
    val accessionNumber: kotlin.String? = null,

    /* SEC Central Index Key (CIK) identifying the filing entity. */
    @Json(name = "cik")
    val cik: kotlin.String? = null,

    /* Date when the filing was submitted to the SEC (formatted as YYYY-MM-DD). */
    @Json(name = "filing_date")
    val filingDate: java.time.LocalDate? = null,

    /* Direct URL to the filing on the SEC EDGAR website. */
    @Json(name = "filing_url")
    val filingUrl: kotlin.String? = null,

    /* SEC form type (e.g., '10-K', '10-Q', '8-K', 'S-1', '4', etc.). */
    @Json(name = "form_type")
    val formType: kotlin.String? = null,

    /* Name of the company or entity that submitted the filing. */
    @Json(name = "issuer_name")
    val issuerName: kotlin.String? = null,

    /* Stock ticker symbol for the filing entity, if available. */
    @Json(name = "ticker")
    val ticker: kotlin.String? = null

) {


}

