/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.massive.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param amount The number of shares per contract of the additional underlying, or the cash-in-lieu amount of the currency.
 * @param type The type of the additional underlying asset, either equity or currency.
 * @param underlying The name of the additional underlying asset.
 */


data class ListOptionsContracts200ResponseResultsInnerAdditionalUnderlyingsInner (

    /* The number of shares per contract of the additional underlying, or the cash-in-lieu amount of the currency. */
    @Json(name = "amount")
    val amount: java.math.BigDecimal? = null,

    /* The type of the additional underlying asset, either equity or currency. */
    @Json(name = "type")
    val type: kotlin.String? = null,

    /* The name of the additional underlying asset. */
    @Json(name = "underlying")
    val underlying: kotlin.String? = null

) {


}

